### ISSUE TITLE
How can I use ssaa and msaa for every api? 

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#104]
Someone said to me that it's possible to use ssaa with that for every api,so does this work for msaa too?
Because it would be nice to use it for non vulkan games.
And if that all works,how can I use that?
I didn't found anything with a google search.

**Comment by Plagman** [comment]
Not MSAA, just SSAA / downsampling. The normal syntax would work, so if you're on 1080p but want to get 4x SSAA by downsampling from 4k, you can set Steam launch options to this and then set it fullscreen with Win+F:

`gamescope -w 3840 -h 2160 -- %command%`

**Comment by Toadfield** [comment]
thanks,but would it work in windowed mode?

**Comment by Plagman** [comment]
Yes, you can just resize the window to have the dimensions you want, or pass -W / -H to specify the output window dimensions you want. So `-w 2560 -h 1440 -W 1280 -H 720' would be 4x SSAA by downsampling from 1440p to a 720p output window.

**Comment by Toadfield** [comment]
I tested gmod with `gamescope -w 3840 -h 2160 -- %command%` in the launch options,but if I try it I have a window that's smaller than my screen.

**Comment by Oschowa** [comment]
Have you considered looking at the readme?
https://github.com/Plagman/gamescope#keyboard-shortcuts
You can also pass `-f` to start in fullscreen.

**Comment by Plagman** [comment]
He mentioned above he wanted it windowed, so maybe it's just a matter of resizing it to the right size? -W and -H will give you the initial size you want too. Or you can alt-tab and resize it with the WM, alt-right click, etc.

**Comment by Toadfield** [comment]
With those keybinds I can size it to the size I want.
But I have another problem,if I load a map in gmod,it freezes,that never happened when I didn't use gamescope.
And if I start gmod,there are some graphic glitches:https://i.imgur.com/MYoxNcW.png
And vkbasalt doesn't work.

**Comment by Toadfield** [comment]
If I go into a map,this error comes up:https://i.imgur.com/9ajZ37t.png
I will test it on other games later.

**Comment by Toadfield** [comment]
I tested it with Half-Life and it didn't even start.

**Comment by Toadfield** [comment]
I reposted the issue I mentioned in the comments,because this issue is closed
https://github.com/Plagman/gamescope/issues/108
