### ISSUE TITLE
How can I use ssaa in Lutris games?

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#106]
If I want for example play i 4k,downsampled to 1080p,how can I do that?

**Comment by Oschowa** [comment]
How to downsample form 4k was already explained to you here https://github.com/Plagman/gamescope/issues/104#issuecomment-691774145
This repo has nothing to do with lutris, so ask on their support forums or discord if you need help setting it up there.

**Comment by Toadfield** [comment]
What I don't get is if I just have to set "gamescope=-w 3840 -h 2160" as an environment variable or something other,because he answered me how to use it in steam,but there was no "=" do I don't know if it would work like Environment Variables or not.

**Comment by Oschowa** [comment]
No, it is not a environment variable, gamescope is a separate program. You have to use it exactly as explained in the comment or the readme to make it work for games on steam. Of course you have to compile and install gamescope first.
To use it outside of steam you do:
`gamescope $some_options -- $game` (steam substitutes %command% with the game's executable)
