### ISSUE TITLE
Games don't work with ssaa

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#108]
I already posted it in the comments of another issue I had,but that issue is closed,so I post it here,if that isn't a problem.
If I start gmod,there are some graphic glitches and it freezes if I load a map.
The graphical glitches:https://i.imgur.com/MYoxNcW.png
If I try Half-Life it won't start at all.
I never had problems with those games without gamescope.

**Comment by Plagman** [comment]
What's your GPU and driver version? Both Half-Life and Garry's Mod work fine here with `gamescope -- %command%` set in Steam:

![image](https://user-images.githubusercontent.com/529930/93651226-97ddf200-f9c5-11ea-8e4c-2b19ddf8f6d2.png)

**Comment by Toadfield** [comment]
I have a RX580 8gb and I use RADV 20.1.7

**Comment by Toadfield** [comment]
The problem just was,that the package I installed was crap,after building it myself,it works.
