### ISSUE TITLE
Gamescope crashes with black screen 

### ISSUE THREAD

**Issue by shanefagan** [Plagman/gamescope#111]
So this one will take a little explanation. I was preparing a patch to build a snap package, it can either be in the main repo or an external one, I just think it would be easier to test builds using snap than building from source so I wanted to share I guess. I originally ran gamescope on my system to make sure the build worked and I tested with CSGO (it fixed an issue I had with CSGO where the UI didn't render correctly) and then made a snapcraft.yml. The build works and runs just fine but doesn't work with CSGO so I tested with VKCube and got a dump of the output from the terminal (attached). I'm running on Ubuntu 20.04 with mesa git and the xanmod kernel. 

[snapcraft.yaml.zip](https://github.com/Plagman/gamescope/files/5287533/snapcraft.yaml.zip)

[dump.log](https://github.com/Plagman/gamescope/files/5287532/dump.log)

You can copy my build with just making a snap in the root of the project and running snapcraft.

**Comment by emersion** [comment]
Are you running on an Intel GPU?

**Comment by shanefagan** [comment]
Nope, rtx480
