### ISSUE TITLE
Fullscreen doesnt work properly with compiz/cairo-dock

### ISSUE THREAD

**Issue by AlexanderWKoenig** [Plagman/gamescope#112]
Hi,
I've noticed, that some fullscreen properties seems to be missing. 
The problem is, that my dock reveals itself, when the mouse moves where the dock is. Normaly if I run a game with wine in fullscreen, it will disable all "screen edges actions" from compiz and the mouse gets grabbed by the application, and the dock is not recallable while playing.

If I run this game via gamescope, "screen edges actions" from compiz gets correctly disabled but cairo-dock is recallable.

A similar issue occurs when i try to run GTA 5 with gamescope. First it will launch the splash screen from the Rockstar Launcher. here the mouse gets correctly grabbed, then the launcher starts and then the game. Now all "screen edges actions" from compiz will be executed while in fullscreen and cairo-dock still is recallable.

**Comment by Plagman** [comment]
That's interesting. It just uses SDL2 fullscreen and mouse grabbing. Do other native games have similar issues? If someone knows offhand what GNOME is looking for there to change its panel behaviour, should be fixable.

**Comment by AlexanderWKoenig** [comment]
I've now tested SuperTuxKart 1.2 which should be using SDL2 now: `Much better gamepad support, by using SDL2 instead of Irrlicht for window creation`

And the issue is also there. So is this just an SDL2 issue?

**Comment by AlexanderWKoenig** [comment]
Even the issue i've reported here https://github.com/Plagman/gamescope/issues/92 seems to be an SDL2 issue. Since it happened also with SuperTuxKart

**Comment by AlexanderWKoenig** [comment]
After some more testing with the game xonotic i've found out, that running it without gamescope doesnt disable screen edges actions in the game-menu, but ingame the mouse gets grabed and compiz screen edges actions are disabled.

Running it with gamescope disables screen edges actions in any case.
With or without gamescope cairo-dock is still recallable, so I opened an issue on thier bugtracker:
https://bugs.launchpad.net/cairo-dock-core/+bug/1899190

So I think the first part of my issue isnt a gamescopeB issue, but the second part where GTA5 launches multiple windows before it starts and every screen edge action isnt disabled, should be a gamescope issue?

**Comment by AlexanderWKoenig** [comment]
The cairo-dock issue got fixed with the linked bug report for me.
For the issue with gta5.exe that allowes compiz screen edge actions if got a workaround.

When stating the game in a vitzual desktio within wine, the issue doesnt occure. This is the command I use;

`gamescope -f -w 1920 -h 1080 -- wine explorer /desktop=name,1920x1080 /mnt/home/Games/GTAV/GTAVLauncher.exe -noChunkedDownload`

I think this issue happens because multiple windows launch before the game starts. This also happens when the updating wineprefix dialog is shown before a game starts
