### ISSUE TITLE
How can I build it?

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#113]
Because of that problem https://github.com/Plagman/gamescope/issues/108
I want to build it myself,because I want to know if that's the problem,but I don't build programs myself,so which file if for building and how can I build it?

**Comment by AlexanderWKoenig** [comment]
The wiki says:
Configure with meson and build with ninja.

I dont know excatly how to build it, but you can look at the makepkg script from the aur for arch:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gamescope-git

**Comment by Scrumplex** [comment]
> you can look at the makepkg script from the aur for arch:

I guess that's an example on how to build it.

Some notes about that:

- `--prefix /usr` is only recommended when packaging, leave that out
- `"$srcdir/$_pkgname"` is the source directory


So all in all something like this:

```
# Prepare
$ cd gamescope
$ meson --buildtype=release . build

# Build
$ ninja -C build 

# Install
$ sudo ninja -C build install
```

**Comment by Toadfield** [comment]
If I do `$ meson --buildtype=release . build` ,I get this error: `ERROR: Subproject exists but has no meson.build file`

**Comment by Toadfield** [comment]
And I get this log:
[meson-log.txt](https://github.com/Plagman/gamescope/files/5361783/meson-log.txt)

**Comment by Joshua-Ashton** [comment]
You probably didn't clone recursively.

**Comment by Toadfield** [comment]
What do you mean?

**Comment by tatsujb** [comment]
git clone -b master https://github.com/Plagman/gamescope.git --recursive

**Comment by Toadfield** [comment]
thanks,that worked.
