### ISSUE TITLE
Some applications are scaled, even when setting both input and output to native resolution

### ISSUE THREAD

**Issue by aqxa1** [Plagman/gamescope#122]
For example, using the following command with `glxgears`:

`gamescope -w 2560 -h 1440 -W 2560 -H 1440 -n -- glxgears`

results in an obviously low resolution output. This can be worked around by setting "-fullscreen" to `glxgears`, but this is not needed when running natively. Adding "-f" to gamescope's options doesn't help either.

I'm using Sway on Wayland with a RX 5700XT, in case there is any issues with the window handling.

**Comment by Faalagorn** [comment]
I have the same issue, also running Sway on Wayland (AMD RX 580) – for the long time I thought I'm doing something wrong and didn't troubleshoot it, but seeing as I'm not alone, it may be something.

**Comment by Plagman** [comment]
glxgears defaults to a 300x300 window size. Games tend to adapt to the native resolution a bit more by default, but sometimes still have to be configured to the right resolution, like you're doing here with -fullscreen.

gamescope won't forcefully resize a client window, as a lot of game apps won't respond well to that, unlike glxgears.

**Comment by VoodaGod** [comment]
is there any way to resize a window inside gamescope? if not, might it in future?

**Comment by massatt212** [comment]
When im playing Forza Horizon 5 the only way i can use FSR is in Windowed mode and it keeps resetting back to fullscreen, is their a way to get FSR working in Fullscreen Mode in some games.
