### ISSUE TITLE
Support Steam video capture

### ISSUE THREAD

**Issue by MayeulC** [Plagman/gamescope#130]
Well, this is more of a Steam issue, but allowing the Steam client to leverage gamescope for video capture (and input device emulation) would help a lot with https://github.com/ValveSoftware/steam-for-linux/issues/6148

This would allow Steam "in-home" streaming to work just by launching a game as a gamescope client.

Adding such support could either be done using the [various wlroots protocols](https://hg.sr.ht/~scoopta/wlrobs/browse/proto?rev=tip), or with a private API.

Use-cases:
* launch a headless gamescope instance (maybe as a headless sway client if not directly supported by gamescope) with Steam as a client, to stream games from a computer while it is being used (sort of a virtual seat to be used with a Steam Link).
* Make streaming compatible with wayland compositors and clients
* Only stream the child window, not the OS (alternatively, allow selecting)
* Possibly improve latency for streaming (plus, gamescope also controls game input)

**Comment by dron1885** [comment]
It actually working. At least under sway.

**Comment by emersion** [comment]
If everything is going through Xwayland, Steam Play should be working fine (works on my setup for instance). Are you trying to use Steam Play + gamescope, or just Steam Play?

**Comment by MayeulC** [comment]
Thank you for your answers. I appreciate the help, but don't really want to pollute that issue thread with Steam troubleshooting for my specific setup... This issue was more about video capture under gamescope, regardless of whether the client is X11 or Wayland.

---
However, since you asked:

I have not tried steamplay+gamescope that I remember. Is it more likely to succeed that way?

I mostly tried gamescope with glxgears, but the result wasn't that promising (20 FPS and very low resolution output, but that's another issue).

I performed some detailed tests in the linked issue (https://github.com/ValveSoftware/steam-for-linux/issues/6148). It never worked for me on sway, and it seems to be the case for many more users. I am not at liberty to try it right now (maybe in ~10 hours), but my last attempt was two weeks ago with a steam link as a client, and "Don't starve together" as a game. It worked under lxqt and plasma/openbox but not sway, nor plasma/kwin_wayland (black screen as stream output), using flatpaked steam.

I am pretty sure the game clients I have tried were running on Xwayland.

If you'd like to investigate this further, you can also ping me in #sway on freenode, or @mayeul:mayeul.net on Matrix, or maybe in that other issue :)

**Comment by emersion** [comment]
Gamescope doesn't support Wayland clients. However gamescope does create a new X11 server, trying to capture gamescope's window without connecting to the inner X11 server won't work well.

**Comment by emersion** [comment]
https://github.com/Plagman/gamescope/pull/219 should help with this.

**Comment by kode54** [comment]
Wow, that took a while to appear. Now to get Steam to support this, heh.

**Comment by Plagman** [comment]
Should all work now!
