### ISSUE TITLE
Is there a way to use Gamescope globally?

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#133]
I wanna use it for every program.

**Comment by emersion** [comment]
You mean every game? I don't think so, no.

**Comment by Toadfield** [comment]
then,for the developers,if you see this,could you add an option like that?

**Comment by Faalagorn** [comment]
Not exactly, what you want but take a look if [stl](https://github.com/frostworx/steamtinkerlaunch) helps you with that.

**Comment by Toadfield** [comment]
That won't work for every executable,but only for steam games. (if I road the stl github page right)

**Comment by Joshua-Ashton** [comment]
It's not possible to use it globally for every game because gamescope cannot distinguish games from regular applications.

Just launch whatever you want (edit the .desktop file or Steam launch parameters) to be ``gamescope -- [app launch thing]``.

``[app launch thing]`` should be ``%command%`` for Steam apps.

**Comment by Toadfield** [comment]
> It's not possible to use it globally for every game because gamescope cannot distinguish games from regular applications.

How do programs like Rivatuner or driver settings be global enabled in windows?
Cause back in my windows days those worked for every program,so does something like this work for Linux too?

> Just launch whatever you want (edit the .desktop file or Steam launch parameters) to be gamescope -- [app launch thing].

[app launch thing] should be %command% for Steam apps.

I hate to do things manually and I hate that Linux doesn't have an option that Windows offers (or I'm to dumb to use it).

**Comment by emersion** [comment]
Closing because this isn't something we can support.

**Comment by Toadfield** [comment]
Then what about a way to enable it for every executable globally not only games?
I know rn that would be dumb cause gamescope is too buggy to use it for every program,but in the future it would make sense.

**Comment by Valmar33** [comment]
No, it wouldn't.

Gamescope's purpose is, basically, to allow custom resolutions for games, as well as limiting FPS.

**Comment by Toadfield** [comment]
But what about the vulkan compositing?
I mean are there other programs that do that?

**Comment by Toadfield** [comment]
I have a better idea,a env var for gamescope,with that you could enable it globally.
That would be good for the future.
