### ISSUE TITLE
Doesn't work with MangoHUD

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#137]
I tried it to use for some shortcuts of games.
I tried to upscale my resolution from 1080p to 2160p for the game [aleph one (Marathon Source Port)](https://aur.archlinux.org/packages/alephone-git/) with this command:
`MANGOHUD=1 MANGOHUD_DLSYM=1 ENABLE_VKBASALT=1 mangohud gamescope -w 3840 -h 2160 -- alephone-marathon`
It works with MangoHud,but if I start it with the gamescope command,it won't launch and this happens on many programs that I wanna start with a shortcut instead of in steam.

**Comment by emersion** [comment]
What if you try without the HUD?

**Comment by Toadfield** [comment]
With `gamescope -w 3840 -h 2160 -- alephone-marathon`it works,but I wanna use MangoHud.

**Comment by Valmar33** [comment]
You're running it wrong. Indeed, I made this mistake myself, at first...

You need to run it as so

    MANGOHUD=1 MANGOHUD_DLSYM=1 ENABLE_VKBASALT=1 gamescope -w 3840 -h 2160 -- mangohud alephone-marathon

MangoHUD needs to run within Gamescope, so Gamescope takes priority.

Indeed, this is true for any set of commands you need to run in Gamescope.

So, this should be classed as "not a bug" ~ but should also require clarification in the README.

**Comment by Toadfield** [comment]
That works for that game,but the problem is,if I don't start the game with `ENABLE_VKBASALT=1,so with `MANGOHUD=1 MANGOHUD_DLSYM=1 gamescope -w 3840 -h 2160 -- mangohud alephone-marathon`,then it doesn't launch.
And the game looks normally like [this](https://i.imgur.com/dDlkRDt.jpg) (with only `gamescope -w 3840 -h 2160 -- mangohud alephone-marathon`),but with vkbasalt (so `MANGOHUD=1 MANGOHUD_DLSYM=1 ENABLE_VKBASALT=1 gamescope -w 3840 -h 2160 -- mangohud alephone-marathon`) it looks [very buggy](https://i.imgur.com/xHj8B6H.jpg).
I don't know if that is a vkbasalt or Gamescope bug,but I only saw that on OpenGL games with the Gamescope vulkan compositor,cause that also happens on system shock 2 (it uses OpenGL) with Gamescope.
Also I tested Gta 3 with `MANGOHUD=1 gamescope -w 3840 -h 2160 -W 1920 -H 1080 -- mangohud %command%` anfd it doesn't launch,but it launches with only gamescope.

**Comment by Valmar33** [comment]
> ... but with vkbasalt ...

Must be a VkBasalt bug.

> and it doesn't launch,but it launches with only gamescope.

Try launching without `MANGOHUD=1`.

**Comment by Toadfield** [comment]
Without `MANGOHUD=1` it works,but then Mangohud doesn't work.
I don't know if that is a Mangohud or gamescope problem,but the work for themself,but not combined.

**Comment by Valmar33** [comment]
Hmmmmmm. This might be a Mesa problem.

Just adding `NODEVICE_SELECT=1` into the mix.

**Comment by Toadfield** [comment]
With `MANGOHUD=1 NODEVICE_SELECT=1 gamescope -w 3840 -h 2160 -- %command%` it still doesn't start.

**Comment by Valmar33** [comment]
Get rid of the `MANGOHUD=1` and add `mangohud` in between the `--` and the `%command%`.

Hmmmmm... what is your Proton version? 5.13 is currently known to be broken with MangoHUD and VkBasalt due to the Solider runtime being kind of broken with Vulkan layers.

**Comment by Toadfield** [comment]
> Get rid of the 'MANGOHUD=1' and add 'mangohud' in between the '--' and the '%command%'.

If you mean that it would look like `gamescope -w 3840 -h 2160 -- mangohud %command%` then the game launches,but Mangohud doesn't work.
Correct me if I'm wrong,but for vulkan games I need to use `MANGOHUD=1`.

> Hmmmmm... what is your Proton version? 5.13 is currently known to be broken with MangoHUD and VkBasalt due to the Solider runtime being kind of broken with Vulkan layers.

I play the game with Proton 5.0-10.

**Comment by Valmar33** [comment]
Yeah, your entire setup seems quite broken, if you're getting this seemingly random brokenness.

Because I simply cannot reproduce your issues on my end.

**Comment by Toadfield** [comment]
> Because I simply cannot reproduce your issues on my end.

So does it work for you with MangoHud?

**Comment by Valmar33** [comment]
Yes. And has for quite some time.

I use https://aur.archlinux.org/packages/mangohud-git

**Comment by Toadfield** [comment]
Which Gamescope Package do you have?

**Comment by Valmar33** [comment]
I just use Gamescope master. Nothing special.

**Comment by Toadfield** [comment]
Tomorrow I will try it with Mangohud-git and gamescope master,so I can test if the problem is cause of my packages.

**Comment by Toadfield** [comment]
So I tried that with newest stable gamescope version and that mangohud package you linked,but it still doesn't work.
Btw it happens on all games.
Now I have to give some information that could solve the problem,my specs are:
Video Card:Radeon Sapphire Rx580 with 8gb vram
Cpu:Ryzen 5 3600
Ram:2x 8gb G.Skill
Mainboard:Asrock x370 Pro4
Drive:Sandisk 2tb Sata SSD with sata 3 cables
I use the normal foss drivers that are build into Kernel 5,9 and have also installed the kernel headers.
I use Manjaro Kde.
I use newest stable Mesa version.

**Comment by kermeat** [comment]
It works for me
```
MANGOHUD_CONFIG=fps_limit=60,cpu_temp,gpu_temp,gpu_power,ram,vram,vsync=0 gamescope -w 2560 -h 1440 -W 2560 -H 1440 -b -f --  mangohud %command%
```

Fedora 33
gamescope-3.7
mangohud-0.6.1

**Comment by fractal-fumbler** [comment]
this is working command for mangohud for me 
`gamescope -w 3840 -h 2160 -- env MANGOHUD=1 MANGOHUD_DLSYM=1 ENABLE_VKBASALT=1 mangohud alephone-marathon`

**Comment by emersion** [comment]
Seems like an issue with your MangoHUD setup, since it works fine on other setups.

**Comment by jarrard** [comment]
-- env MANGOHUD=1   

This worked for me; before that I was getting DOUBLE mangohud elements which was a bit off putting.
