### ISSUE TITLE
Programs look buggy

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#138]
For example,qzdl looks like [this](https://i.imgur.com/GoCsXmJ.png) normally,but with `gamescope -- ` it looks like [this](https://i.imgur.com/XFJHRNh.png) and I can't launch doom at all with this cause the mouse is buggy there.

**Comment by emersion** [comment]
Doesn't look buggy to me…

**Comment by Toadfield** [comment]
There are black borders at the top and bottom and everything is smaller.

**Comment by emersion** [comment]
Yes, this is expected. gamescope will scale the game/app to 720p by default, and add black letter-boxing if necessary. You can use the -w/-h/-W/-H flags to change it.

**Comment by Toadfield** [comment]
So I tried it with `gamescope -w 3840 -h 2160 -W 1920 -H 1080 -- ` and now it looks zoomed in,like [this](https://i.imgur.com/YT5Cn0k.png) and another problem is that I can't move my cursor out of the window to close it.
Another problem is that now I can click on "launch",but doom closes immediantly.

**Comment by emersion** [comment]
>now it looks zoomed in,like this

Looks like it's working as expected.

>another problem is that I can't move my cursor out of the window to close it.

This is by design. Games want to capture the mouse in general.

**Comment by Toadfield** [comment]
> Looks like it's working as expected.

I found out that with `gamescope -w 3840 -h 2160 --` it looks not zoomed in.

> This is by design. Games want to capture the mouse in general.

Can I set that this only happens if a game sets that it happens?
Cause normally if a game doesn't want that the mouse goes out of the window,it sets that automatically.

**Comment by emersion** [comment]
Opened https://github.com/Plagman/gamescope/issues/216 for the mouse capture suggestion.
