### ISSUE TITLE
Force Pointer Confinement

### ISSUE THREAD

**Issue by pschichtel** [Plagman/gamescope#142]
I've noticed that some native games, for example [Northgard](https://store.steampowered.com/app/466560/Northgard/), have trouble confining the pointer to their game window. I'm wondering if this is something gamescope could help with as well.

**Comment by emersion** [comment]
gamescope should already confine the pointer to the game window.

**Comment by pschichtel** [comment]
oh interesting, is that something I need to enable or does that work by default?

**Comment by emersion** [comment]
Should capture the mouse by default. Note that it's buggy on some games, see other opened issues.

**Comment by pschichtel** [comment]
Yep, can confirm this working. With `gamescope -w 2560 -h 1440 -f -- %command%` in steam it works perfectly fine.
