### ISSUE TITLE
Gamescope bloats xorg.log

### ISSUE THREAD

**Issue by Valmar33** [Plagman/gamescope#147]
Running Gamescope causes the xorg.log to bloat by about 300KiB per second.

Distro is Arch Linux
Kernel version is 5.10.4, custom, based on Arch vanilla config
Mesa master, commit 5692e2dda5c, using some custom patches

This is what gets constantly spammed to the log:

```
[ 21777.671] (II) AMDGPU(0): EDID vendor "AUS", prod id 9634
[ 21777.672] (II) AMDGPU(0): Using hsync ranges from config file
[ 21777.672] (II) AMDGPU(0): Using vrefresh ranges from config file
[ 21777.672] (II) AMDGPU(0): Printing DDC gathered Modelines:
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz eP)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080"x0.0  198.50  1920 1968 2000 2080  1080 1083 1088 1124 +hsync -vsync (95.4 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080"x0.0  235.50  1920 1968 2000 2080  1080 1083 1088 1133 +hsync -vsync (113.2 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080"x0.0  285.50  1920 1968 2000 2080  1080 1083 1088 1144 +hsync -vsync (137.3 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080"x0.0  325.08  1920 1944 1976 2056  1080 1083 1088 1098 +hsync +vsync (158.1 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080i"x0.0   74.25  1920 2008 2052 2200  1080 1084 1094 1125 interlace +hsync +vsync (33.8 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1280x720"x0.0   74.25  1280 1390 1430 1650  720 725 730 750 +hsync +vsync (45.0 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "720x480"x0.0   27.00  720 736 798 858  480 489 495 525 -hsync -vsync (31.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "720x576"x0.0   27.00  720 732 796 864  576 581 586 625 -hsync -vsync (31.2 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1280x720"x0.0   74.25  1280 1720 1760 1980  720 725 730 750 +hsync +vsync (37.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080i"x0.0   74.25  1920 2448 2492 2640  1080 1084 1094 1125 interlace +hsync +vsync (28.1 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1920x1080"x0.0  148.50  1920 2448 2492 2640  1080 1084 1089 1125 +hsync +vsync (56.2 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "640x480"x0.0   31.50  640 656 720 840  480 481 484 500 -hsync -vsync (37.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "640x480"x0.0   30.24  640 704 768 864  480 483 486 525 -hsync -vsync (35.0 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "720x400"x0.0   28.32  720 738 846 900  400 412 414 449 -hsync +vsync (31.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1280x1024"x0.0  135.00  1280 1296 1440 1688  1024 1025 1028 1066 +hsync +vsync (80.0 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1024x768"x0.0   78.75  1024 1040 1136 1312  768 769 772 800 +hsync +vsync (60.0 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1024x768"x0.0   75.00  1024 1048 1184 1328  768 771 777 806 -hsync -vsync (56.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "832x624"x0.0   57.28  832 864 928 1152  624 625 628 667 -hsync -vsync (49.7 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "800x600"x0.0   49.50  800 816 896 1056  600 601 604 625 +hsync +vsync (46.9 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "800x600"x0.0   50.00  800 856 976 1040  600 637 643 666 +hsync +vsync (48.1 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1152x864"x0.0  108.00  1152 1216 1344 1600  864 865 868 900 +hsync +vsync (67.5 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1280x960"x0.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1280x800"x0.0   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync (49.7 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1440x900"x0.0  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz e)
[ 21777.672] (II) AMDGPU(0): Modeline "1680x1050"x0.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)
```

**Comment by Valmar33** [comment]
Can post Mesa patches if they're relevant somehow.

**Comment by emersion** [comment]
Sounds like xf86-video-amdgpu is spamming the logs. I wonder what this has to do with gamescope, because gamescope is just an X11 SDL client.

**Comment by Valmar33** [comment]
Hmmmmm. Odd. `xf86-video-amdgpu` was last updated on 20th of May... no issues back then I can recall. Version is `19.1.0-2`

Could Xwayland be involved somewhere?

Arch ships Xwayland following the master branch, with this commit https://gitlab.freedesktop.org/xorg/xserver/-/commit/e4a9f0bb4e36cffe4f7021bfa27753a9f42df2ff

**Comment by emersion** [comment]
Xwayland doesn't touch the hardware, so it's unlikely it's involved.

Do you have anything interesting in dmesg? It's weird that this only happens when you run gamescope. Can you run glxgears inside gamescope to confirm it's not the client inside gamescope doing weird things?

Sorry, not really sure what's happening here.

**Comment by Valmar33** [comment]
Yeah, a plain `gamescope -- glxgears` also triggers this.

For context, I was talking with Plagman on VKx about it, and he suggested testing glxgears, and when that also caused the issue, asked me to post here about it.

**Comment by Valmar33** [comment]
On an amusing note, I can avoid the issue by deleting the `xorg.log` file. For the entire Xorg session, there's no file to spam to.

**Comment by Valmar33** [comment]
Hmmmmmmm. As a wild guess... perhaps Roman Gilg's disman and kdisplay could be involved somewhere...?

Been running Git versions of them, along with kwinft and wrapland.

**Comment by Valmar33** [comment]
Ah, right, dmesg log...

[dmesg.log](https://github.com/Plagman/gamescope/files/5780878/dmesg.log)

**Comment by Valmar33** [comment]
@emersion

Hmmmmmm. I've noticed that over time, the spam still happens without Gamescope, but at significantly slower rate.

If I open Steam, for example, it seems to get spammed at least twice.

**Comment by emersion** [comment]
>dmesg log

Nothing interesting in here.

>As a wild guess... perhaps Roman Gilg's disman and kdisplay could be involved somewhere...?

Could be related. Can you try stopping them and see if the logspam still happens? Maybe also try another X11 WM?

**Comment by Valmar33** [comment]
I can try mainstream kwin, I suppose. I don't have any other X11 WM available that I'm familiar enough with.

**Comment by Valmar33** [comment]
Nothing has changed... bloating still occurred with vanilla kwin, kscreen and libkscreen... oh well.

**Comment by Valmar33** [comment]
@emersion

This Mesa merge request seems to fix the xorg.log bloating issue:

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8492

**Comment by Valmar33** [comment]
Apparently, it was this commit that fixes it near-entirely:

https://gitlab.freedesktop.org/mesa/mesa/-/commit/42d15184d6f66e7118d9468cbaa91e64ffd37fbb

Above merge request eliminates the rest of the spam.

**Comment by Valmar33** [comment]
So... fixed. :+1:
