### ISSUE TITLE
[Feature Request] Being able to enable it globally

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#152]
I wanna use it for every program and game,so it would be cool to enable it globally with something like an env var.
I don't know if it works if you just do `gamescope --` in .profile.

**Comment by Valmar33** [comment]
You really wouldn't want to use this for every program.

It doesn't work quite how you think it does.

**Comment by emersion** [comment]
Duplicate of https://github.com/Plagman/gamescope/issues/133

**Comment by Toadfield** [comment]
@emersion 
Oh,I duplicated my own post.
I forgot that I already asked that.

**Comment by Toadfield** [comment]
@Valmar33 
I mean I could disable it if there would be an env var,by "env var="" " I think.
And does it really cause so much programs?
Cause I just wanna use it on all my games without the need to apply it manually.
