### ISSUE TITLE
[Question] How can I set that I can move the mouse out of the window?

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#153]
I sometimes wanna move the mouse out of the windows,so can I set a hotkey or something like that to enable/disable being able to move it out of the window.

**Comment by Plagman** [comment]
If you alt-tab, it should spring the cursor out of the gamescope window until focused again. It'd be cool to have a hotkey to toggle cursor capture in addition to that, probably.

**Comment by emersion** [comment]
Dup of https://github.com/Plagman/gamescope/issues/216

**Comment by Hydranet** [comment]
> If you alt-tab, it should spring the cursor out of the gamescope window until focused again. It'd be cool to have a hotkey to toggle cursor capture in addition to that, probably.

alt-tabbing to spring the cursor out of the gamescope window doesn't work on Sway or does it only work when using gamescope with specific options?

**Comment by emersion** [comment]
Sway doesn't have alt-tab. Instead, use mod+arrow keys or other keybindings, see your config file.

**Comment by Hydranet** [comment]
> Sway doesn't have alt-tab. Instead, use mod+arrow keys or other keybindings, see your config file.

Thank you I didn't realize that! I discovered it was the mod+h for me.
