### ISSUE TITLE
Mouse Cursor is sliced in the middle

### ISSUE THREAD

**Issue by awsms** [Plagman/gamescope#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

On most of the titles, the mouse cursor is sliced in the middle.

### Steps To Reproduce

1. Launch whatever game (for ex, Diablo IV from steam, `DXVK_ENABLE_NVAPI=1 gamescope -w 3840 -h 2160 --force-grab-cursor -- %command%`)
2. Mouse is spliced in two.

### Hardware information

```markdown
- Distro: EndeavourOS
- CPU: AMD Ryzen 7 8845HS
- GPU: NVIDIA RTX 4070 (laptop)
- Driver Version: NVIDIA 560.35.03
```

### Software information

```markdown
- Desktop environment: i3
- Session type: X
- Gamescope version: 3.15.9-5-gd87f6d9b
- Gamescope launch command(s): any. Both with gamescope -w 3840 -h 2160 --force-grab-cursor & gamescope -w 3840 -h 2160
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [X] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

https://forums.developer.nvidia.com/t/gamescope-mouse-cursor-is-sliced-in-the-middle/238568/

**Comment by matte-schwartz** [comment]
Nvidia driver issue, no fix released for it yet: https://github.com/ValveSoftware/gamescope/issues/1099
