### ISSUE TITLE
Get rid of EGL and GBM inside wlroots

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#16]
We just want the dma-bufs, we hsould be able to bypass all that stuff with some wlroots work.

**Comment by emersion** [comment]
The linux-dmabuf protocol implementation still needs to import DMA-BUFs and make sure we can sample from them. We can implement a very simple Vulkan-backed `wlr_renderer` that just implements the dmabuf-related things. This would depend on https://github.com/Plagman/gamescope/issues/51

**Comment by emersion** [comment]
Another issue is that Xwayland manually creates wl_drm buffers. We can only get a DMA-BUF out of these via EGL.

Xwayland needs to be updated to prefer linux-dmabuf instead of wl_drm.

**Comment by emersion** [comment]
> Xwayland needs to be updated to prefer linux-dmabuf instead of wl_drm.

Xwayland uses wl_drm when the format/modifier pair isn't advertised by linux-dmabuf. So as long as we advertise formats with MOD_INVALID via linux-dmabuf when modifiers aren't supported, we should be fine.
