### ISSUE TITLE
[Question] Does gamescope work with normal Wayland windows?

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#164]
In the description of gamescope it says that it's a xwayland compositor.
But not all windows use xwayland,many games work natively for wayland,so does gamescope work for those windows?
I wonder cause I wanna switch to Wayland.

**Comment by Plagman** [comment]
No, only X11 clients.

**Comment by soredake** [comment]
> No, only X11 clients.

Is there plans to add support for wayland clients?
