### ISSUE TITLE
Doesn't exit after child process exited

### ISSUE THREAD

**Issue by hjri** [Plagman/gamescope#167]
Commit 9b63bf7
Environment: KDE X11 session, kwin_x11
GPU:
```
00:00:00.008 [render/gles2/renderer.c:886] Using OpenGL ES 3.2 Mesa 21.0.0-rc4
00:00:00.008 [render/gles2/renderer.c:887] GL vendor: AMD
00:00:00.008 [render/gles2/renderer.c:888] GL renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.40.0, 5.10.0-3-amd64, LLVM 11.0.1)
```

running `ENABLE_VKBASALT=0 MANGOHUD=0 gamescope -f -w 2560 -h 1440 -- gzdoom` works fine, but gamescope compositor lingers after exiting gzdoom, I have to ctrl-c it. Same happens with other things I tried - reVC, running Valheim on steam (have to hit "X Close" in steam to stop it)

ksysguard shows that gamescope process doesn't have any children processes after it has exited, no zombies either.

**Comment by Plagman** [comment]
I've seen the same thing, just running eg. gamescope -- vulkaninfo on a desktop. The subreaper / wait code is supposed to be pretty straightforward, so I'm curious what's going wrong there.

**Comment by emersion** [comment]
The steamcompmgr thread was correctly exiting, but the wlserver thread (which happens to be the main thread) was staying around.
