### ISSUE TITLE
ubuntu ppa

### ISSUE THREAD

**Issue by soredake** [Plagman/gamescope#168]
Would be nice to have it.

**Comment by emersion** [comment]
Sorry, we have no plans to offer an Ubuntu PPA. Would be nice if someone stepped up to set one up, though.

**Comment by soredake** [comment]
> Sorry, we have no plans to offer an Ubuntu PPA. Would be nice if someone stepped up to set one up, though.

Maybe leave this issue open until someone is create ppa?

**Comment by fallenguru** [comment]
> I created experimental PPA https://launchpad.net/~samoilov-lex/+archive/ubuntu/gamescope currently for Ubuntu 21.10.

Would it be possible for you to add support for 18.04 (bionic), or at least 20.04 (focal)?

**Comment by Sunderland93** [comment]
>or at least 20.04 (focal)?

Done

**Comment by artistro08** [comment]
any possible way we can get 18.04?

**Comment by Bhood23** [comment]
ubuntu 18.04
