### ISSUE TITLE
Move to xres pid querying

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#17]
Right now we're getting appids through the atom set by gameoverlayrenderer. It's not super robust and there's a bunch of cases where the current hooks don't set the Atom (like Dead Cells native) - getting the pid through xres 1.2 should be robust (see keithp recent commit in xrestop), and then we can walk up /proc/ until we find the SteamChildMontior, which would give us the appid reliably

**Comment by Plagman** [comment]
I need to type up a generic 'pid to appID' routine, but as a first step we should just start tracking pids for windows. We can use this as a model for the extension I was talking about:

https://gitlab.freedesktop.org/xorg/app/xrestop/-/commit/19f72d344367a2bd250b5700f412625b249a90fd

**Comment by emersion** [comment]
PIDs are now queried via XRes.

**Comment by Plagman** [comment]
This is good to close then?
