### ISSUE TITLE
[Question] When will this program be so good,that you can use it for every application without bugs?

### ISSUE THREAD

**Issue by Toadfield** [Plagman/gamescope#178]
Enabling this program for every application would make many problems,it wouldn't work that often.
But it would be cool to be able to composite every OpenGL program in the future,so when can you do that without problems?

**Comment by Valmar33** [comment]
Would be nice if you could stop trolling...

**Comment by emersion** [comment]
We already replied to this question. Please refrain from asking it repeatedly.

**Comment by Toadfield** [comment]
@Valmar33 I'm not trolling.
@emersion When did you reply to that?

**Comment by Joshua-Ashton** [comment]
You've asked this question 3 times now.

There's a reason you're banned from the DXVK issue tracker.
