### ISSUE TITLE
issues running SaschaWillems vulkan demos

### ISSUE THREAD

**Issue by BNieuwenhuizen** [Plagman/gamescope#185]
if I run e.g. the instancing demo I just get a black screen, not sure if stuck or not rendering. Latest git gamescope.

**Comment by emersion** [comment]
Seems like it just renders a frame and then is stuck. Works fine with Mesa 21.0.2, broken on Mesa master.

**Comment by Joshua-Ashton** [comment]
Bisected to https://github.com/Plagman/gamescope/commit/df18c4081582074662d825b807f464060ffacf45

**Comment by Joshua-Ashton** [comment]
Only affects Vulkan apps, vkcube/sekiro does not work, glxgears/portal does

**Comment by Joshua-Ashton** [comment]
Might be a Mesa bug as it doesn't happen on 21.0.2 but does on Mesa-git

**Comment by emersion** [comment]
Eh, it seems like I just missed this:

```
../src/vulkan/wsi/wsi_common_x11.c:1273: Swapchain status changed to VK_ERROR_OUT_OF_DATE_KHR
```

I'm used to seeing such swapchain status changes (e.g. to SUBOPTIMAL) and they're in general not fatal, so I just didn't pay any attention to them… But it seems like OUT_OF_DATE is fatal.

The X11 WSI should not change the swapchain status this way in the first place, will investigate.

**Comment by Joshua-Ashton** [comment]
We should definitely be handling OUT_OF_DATE and SUBOPTIMAL either way.

**Comment by Joshua-Ashton** [comment]
Hm, even after fixing that, it still doesn't work for me.

**Comment by emersion** [comment]
Yes, that's because the OUT_OF_DATE is due to an X11 error:

```
000:<:0028: 72: Present-Request(146,1): Pixmap window=0x00600000 pixmap=0x00600003 serial=1 valid=0x00000000 update=0x000
00000 x_off=0 y_off=0 target_crtc=0x00000000 wait_fence=0x00000000 idle_fence=0x00600004 options=0 target_msc=4294967296 
divisor=0 remainder=0 notifies=;
000:>:0028:Error 4=Pixmap: major=146, minor=1, bad=0x00600003, seq=0028
```

**Comment by emersion** [comment]
To be clear, the OUT_OF_DATE happens in the client running inside gamescope. It doesn't happen with gamescope's own swapchain.

**Comment by Joshua-Ashton** [comment]
Yeah, but we should still handle it for our swapchain.

**Comment by emersion** [comment]
Sigh. Finally found out the issue: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1166

Funnily enough, this is fixed by the following existing PR: https://github.com/Plagman/gamescope/pull/184
