### ISSUE TITLE
Gamescope as single user session compositor Steam Link (Remote Play) broken

### ISSUE THREAD

**Issue by Samsagax** [Plagman/gamescope#189]
Hello, there! I came across this project and decided to give it a try in a couch gaming scenario (similar to what would be a SteamOS machine). I've built git [from two days ago](https://github.com/Plagman/gamescope/commit/a85c8d761c48789b1cc2055afa1d62cba382ccda) and set up a user session with systemd.

I start the compositor [via a systemd unit](https://github.com/Hjdskes/cage/wiki/Starting-Cage-on-boot-with-systemd) with basically this command in my setup:
`$ /usr/bin/gamescope -h 2160 -w 3840 -- steam -tenfoot -steamos -fulldesktopres`

All my games at least the ones I tried so far work as expected (Impressive!):
- Native Dirt 4
- Proton Dirt Rally 2.0
- Proton Relicta
- Native Kingdom new horizons

With no game started I try to connect with my phone using the SteamLink app and it connects and I can see the mouse moving and the controller (the one in my touch screen) moving things around (as I see in my pc screen) but the image on the phone is borked. Some times it appears pure white, other times I see a corrupted image of the current screen on my machine that never updates.

I think is a regression since it worked in version 3.7.1.

Note: the full setup to start gamescope and steam in BPM is [here](https://github.com/Samsagax/gameros-session). I'm impressed by the way this is moving.

**Comment by Plagman** [comment]
I'm looking at it now, but as a quick note, if you're running steam with -steamos, you probably want `-e` as well on the gamescope commandline, or it won't understand the detached SteamOS overlay.

**Comment by Samsagax** [comment]
> I'm looking at it now, but as a quick note, if you're running steam with -steamos, you probably want `-e` as well on the gamescope commandline, or it won't understand the detached SteamOS overlay.

What does the `-e` flag do? There is no documentation about it in gamescope page and could not find it in the code for handling command line inside `main.cpp`. Thanks for looking into this. Btw the Steam overlay works great (o the PC) inside games with no flag whatsoever.

**Comment by emersion** [comment]
`-e` is a "Steam mode", it should be used if you use gamescope to run Steam. It adds special-handling in gamescope for Steam windows.

**Comment by Samsagax** [comment]
Thanks @emersion for the clarification. I've added the -e flag to the startup command. Although I don't see any difference right now, maybe a little less flickering at game startup. Just ping me if you want me to test something

**Comment by MatthiasGrandl** [comment]
With a standalone gamescope session, I only get a black screen as soon as I connect any client to Steam :/ Would really love to use gamescope for my streaming box.

**Comment by hsmalley** [comment]
I'm having the same kind of problems, a blank screen on the client. In testing with a non-standalone session I can see the interface and games loading and running fine. Audio & Inputs work with the client, just no video. Not really sure what to check next or look for. If someone has an idea I'm open to testing.

**Comment by VoodaGod** [comment]
i have an issue with gamescope & remote play where i sometimes have to move the mouse for the video to start. easiest way to do that via remote play & a controller is with the steam chords to move the mouse (guide + right stick by default). worth a try to see if that also works in this use case

**Comment by Samsagax** [comment]
> 

Won't work on mobile unfortunately.

**Comment by Samsagax** [comment]
Just tested and both the SteamLink Android app and Streaming to another machine works fine on latest git. I think this one can be closed.
