### ISSUE TITLE
Gamescope doesn't start on Mesa-git

### ISSUE THREAD

**Issue by Joshua-Ashton** [Plagman/gamescope#191]
The window is made but it's never unhidden or presented to. What is broken here?

**Comment by emersion** [comment]
Seems to be due to Xwayland failing to initialize GL:

```
Supported GL version is not sufficient (required 21, found 0)
glGetString() returned NULL, your GL is broken
EGL setup failed, disabling glamor
Failed to initialize glamor, falling back to sw
```

**Comment by Joshua-Ashton** [comment]
I get a different error where it doesn't make the window and hangs, but I get that if its installed anywhere other than /use/lib and use ldconfig/LD_library_path

**Comment by emersion** [comment]
Can you share full gamescope logs?

**Comment by emersion** [comment]
I can't reproduce anymore. Please re-open if you're still hitting this.
