### ISSUE TITLE
question: does this is vulkan ONLY?

### ISSUE THREAD

**Issue by neofeo** [Plagman/gamescope#204]
Hi, i would like to use the gl wrapper for now bc on our mesa (panfrost) we dont have vulkan already, is on development.
I am compiling tons of stuff just to test this software and bc this seems a an exhaustive compilation work, every component ask the most bleeding edge stuff..i would like to know if it would work in theory at least.

**Comment by emersion** [comment]
No, gamescope requires a Vulkan driver.
