### ISSUE TITLE
refresh rate switching

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#206]
Would like to be able to make up a new mode like the current one but with different timings to select a refresh rate based on the current app's FPS limit (todo). So for now just being able to change a value in gdb and having the next frame try to set that mode in embedded would be sufficient.

**Comment by emersion** [comment]
https://github.com/Plagman/gamescope/commit/b380f3fbf24e78a039e9acfe0181f996238b2ddc allows switching the refresh rate at runtime. From a GDB console, execute `p drm_set_refresh(&g_DRM, 65)` to set the refresh rate to 65Hz.

**Comment by Plagman** [comment]
nice thanks!
