### ISSUE TITLE
support dropdowns in rockstar social club

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#207]
And probably other weird apps too. it'd be cool to actually have them as a layer, but the old steamcompmgr approach of just having a fullscreen dropdown until you're done with it would also work as a starting point. They tend to try to dismiss themselves so i've seen some be finnicky.

**Comment by emersion** [comment]
These are also used in other launchers too, e.g. when trying to register a new Origin account. They are also dismissed just before the click goes through.

Yeah, we should just ignore override-redirect windows, and add them to our scene-graph.

**Comment by Joshua-Ashton** [comment]
This can be closed now?
