### ISSUE TITLE
Multi-display in embedded mode

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#211]
Supporting multiple displays could go like that for us:

At first, just need to be a display priority setting to prioritize between different kind of displays instead of only picking the first. 

Then respond to hotplug accordingly and apply whatever priority is set.

Then let the priority be changed on the fly and have it reconfigure accordingly.

Later we could add support for multiple simultaneous displays, possibly with their own vblankmanager/composition step if appropriate, but that's more of a nice to have.

**Comment by emersion** [comment]
e5e0ebf5a433 allows selecting a connector via the `-O` CLI option. The list of available connectors is printed on startup, and can also be obtained via `ls /sys/class/drm/card0/`.

**Comment by emersion** [comment]
This is now all implemented. To switch the connector from GDB, update `g_sOutputName` and then set `g_DRM.out_of_date = true`.

Opened https://github.com/Plagman/gamescope/issues/227 for multiple simultaneous displays.

**Comment by Plagman** [comment]
Prior to full simultaneous display, can we have it just switch to external automatically on hotplug and turn off internal?

**Comment by emersion** [comment]
This is now done. A wildcard can be used to match connectors not specified in the list. So for instance `-O *,eDP-1` will try to use any external connector, then fallback to `eDP-1` if none is available.
