### ISSUE TITLE
Pipewire support

### ISSUE THREAD

**Issue by emersion** [Plagman/gamescope#213]
Would allow streaming gamescope's output.

- Link to Pipewire and offer a video node. I've considered leveraging xdg-desktop-portal-wlr to avoid all of the Pipewire complexity, but not clear it's worth the middle-man, let's try directly using Pipewire for now.
- Use Pipewire's MemFd together with the add_buffer/remove_buffer hooks. This provides better performance than MemPtr. DMA-BUF support in Pipewire is too immature for now, and consumers don't widely want/support it.
- We'll need to force compositing when screen capture is active. Can likely build on top of the existing screenshot functionality.
- Need to be careful wrt. threads.

**Comment by Plagman** [comment]
This is fine to merge if it tests good for you, broad strokes look good to me.
