### ISSUE TITLE
Upscaling with FidelityFX Super Resolution (FSR)

### ISSUE THREAD

**Issue by Firlaev-Hans** [Plagman/gamescope#215]
While adding FSR to a game after the UI and post processing effects are drawn is not recommended, the Wine patch that enables FSR in fshack for full screen games in Wine is producing surprisingly good results.
Would it be possible to implement AMD FSR as an alternative upscaling method in Gamescope to apply it to just about any game on Linux? Are there any plans already to implement this?

**Comment by emersion** [comment]
Yes, FSR is potentially something we'd be interested in.

**Comment by tgharib** [comment]
This will be useful for taking screenshots. At 1280x800, screenshots won't look great, unless they're upscaled or the game's render resolution is changed somehow.

**Comment by boniek83** [comment]
It would be great to have sharpening level exposed in UI somehow.

**Comment by lavilao** [comment]
I knew I was not the only one thinking in this! btw would it be possible to add other upscalers like RAVU, FSRCNNX or/and ACNet?
I just tried this https://github.com/Blinue/Magpie on windows and I was thinking gamescope could be its alternative in linux. Is it possible or its too much hassle? Thanks anyway!

**Comment by amazingefren** [comment]
I've recently been using FSR with gamescope (steam), however, this method is probably not a perfect solution

Using Proton-6.13-GE (6.14 might work?)

FSR relies on fshack, and fshack does not attach to wm name "steamcompmgr" so simply changing Xutf8SetWMProperties to apply a different class name does the trick (in my case in which using fshack is ok)

See: [commit](https://github.com/amazingefren/gamescope/commit/ee1a8f07e3eb1e30a754ec6bf8c93b85fc03f851)

steam launch options
```
WINE_FULLSCREEN_FSR=1 gamescope {options} -- %command%
```

do note, I'm not exactly sure in which cases this will/will-not work. I have been simply been using it to play on a 5120x1440 monitor, 2560x1440 game in the middle (window-mode-ish), game on lower res + FSR -> 2560x1440 output in gamescope

**Comment by lagseeing** [comment]
There is an open pull request on proton that adds FSR support, but I can't make it to work with gamescope, it just wont launch, any ideas as to why that would be?

**Comment by jarrard** [comment]
Tried to get FSR working with gamescope but it seems it doesn't like the fullscreen 'window' mode so doesn't engage and since gamescope doesn't have a true fullscreen mode, fsr via wine at least won't enable. :(

**Comment by lavilao** [comment]
what about wine-wayland FSR implementation? it requires the game to NOT be on fullscreen

**Comment by jarrard** [comment]
> what about wine-wayland FSR implementation? it requires the game to NOT be on fullscreen

Odd it seems FSR only works with fullscreen under XORG, it should work in windowed mode also perhaps.

**Comment by lavilao** [comment]
perhaps because xorg to scale has to change the desktop resolution (fullscreen mode) while wayland can just scale the window by stretching the frame? Im no expert so I am just guessing

**Comment by DadSchoorse** [comment]
#360

**Comment by pchome** [comment]
IMHO https://github.com/NVIDIAGameWorks/NVIDIAImageScaling should be added too, because (at least for me on NVIDIA GPU) it adds less artifacts to fonts. So users will be able to choose appropriate upscaling mechanism depending on a game, I guess.

It's hard to tell where is the difference, so here is the pre-built VK sample for Linux (along with the patch I used to build it on Linux):
[NVIDIAImageScaling-VK-Linux-bin-1.0.1.zip](https://github.com/Plagman/gamescope/files/7798092/NVIDIAImageScaling-VK-Linux-bin-1.0.1.zip)
put "low-res" screenshots into `samples/bin/VK/media/images/`

P.S. maybe FSR could be relatively easy added to this sample, if so it could be forked as upscaling comparison tool.

**Comment by emersion** [comment]
Done in https://github.com/Plagman/gamescope/pull/360#event-5984608010

**Comment by soredake** [comment]
@pchome can you create a dedicated issues about nvidia image scaling?

**Comment by pchome** [comment]
@soredake I don't think it's right making an feature request for tool I can't even use ;)

**Comment by IDDQD69** [comment]
already done! Nice! Awesome job :)
