### ISSUE TITLE
Using system libraries for wlroots and libliftoff

### ISSUE THREAD

**Issue by darix** [Plagman/gamescope#22]
Is it possible?

for https://github.com/emersion/libliftoff/issues/40 I also asked for a release

**Comment by darix** [comment]
As a follow up question: can we support building with those libs from the system and only fallback to the intree copy?

**Comment by darix** [comment]
For testing i just did this. it still lacks fallback code.

```
diff --git a/meson.build b/meson.build
index 673dbf6..e9a4e1c 100644
--- a/meson.build
+++ b/meson.build
@@ -26,9 +26,11 @@ xkbcommon      = dependency('xkbcommon')
 math           = cc.find_library('m')
 thread_dep = dependency('threads')
 sdl_dep = dependency('SDL2')
+wlroots_static_dep = dependency('wlroots')
+liftoff_dep = dependency('liftoff')
 
-wlroots_proj = subproject('wlroots')
-wlroots_static_dep = wlroots_proj.get_variable('wlroots_static_dep')
+#wlroots_proj = subproject('wlroots')
+#wlroots_static_dep = wlroots_proj.get_variable('wlroots_static_dep')
 
 shadercompiler = find_program('glslangValidator')
 extratool = find_program('xxd')
@@ -41,8 +43,8 @@ spirv_shader = custom_target('shader_target',
   install : false,
 )
 
-liftoff_proj = subproject('libliftoff')
-libftoff_dep = liftoff_proj.get_variable('liftoff')
+#liftoff_proj = subproject('libliftoff')
+#liftoff_dep = liftoff_proj.get_variable('liftoff')
 
 executable(
     'gamescope',
@@ -56,7 +58,7 @@ executable(
         dep_x11, dep_xdamage, dep_xcomposite, dep_xrender, dep_xext,
         dep_xxf86vm, pixman_dep, drm_dep, wayland_server, wayland_protos,
         libinput, xkbcommon, math, thread_dep, sdl_dep, wlroots_static_dep,
-        vulkan_dep, libftoff_dep, dep_xtst
+        vulkan_dep, liftoff_dep, dep_xtst
     ],
     install: true,
 )
```

**Comment by Plagman** [comment]
I'll remove the libliftoff one as soon as it's packaged in arch, the lack of arch package is the reason I bundled it.

The wlroots one can only be changed to system once we're not depending on patches. gamescope won't work without the patched branch referenced by the git submodule, and the subproject. We'll look at doing the wlroots patch the proper way, but for now this does fine.

**Comment by darix** [comment]
well I have a basic git based package for libliftoff right now. and try to convince the upstream dev to actually do releases. (see last 2 comment in the bug above). we could even use the [OBS](https://build.opensuse.org/) to provide packages for libliftoff and gamescope (like we do for [dino](https://build.opensuse.org/package/show/network:messaging:xmpp:dino/dino) e.g., directly hooked up to github)

the wlroot patch looked minor. what does the removal of the xwm support actually do and why does it break gamescope if it is still there?

**Comment by eli-schwartz** [comment]
Slightly related to this, would it be possible to use meson's wrap-git feature instead of using git submodules?

Using *.wrap files would mean meson doesn't mysteriously fail if you didn't init the submodules. meson would just check them out for you.

**Comment by darix** [comment]
cool thank you! i will update my package asap :)
