### ISSUE TITLE
Support wlroots 0.14.x

### ISSUE THREAD

**Issue by Scrumplex** [Plagman/gamescope#222]
Currently gamescope-git on the Arch Linux User Repository is not buildable, as there is no wlroots below 0.14.x available to build against.

This issue is there to track progress to support or rather update to wlroots 0.14.x.

**Comment by emersion** [comment]
https://github.com/Plagman/gamescope/pull/202 helps with that.

**Comment by emersion** [comment]
#202 is merged and requires wlroots master. I expect things to settle down now that we don't hack into EGL anymore to grab DMA-BUFs.
