### ISSUE TITLE
 [bisected] `-O` option breaks embedded mode (Steam client can't start from TTY)

### ISSUE THREAD

**Issue by Samsagax** [Plagman/gamescope#241]
Using gamescope-session running steam client from TTY as a systemd unit with this command line:
````
$ /usr/bin/gamescope -e -f -- steam -tenfoot -steamos -fulldesktopres
````
Steam client does not start and gamescope outputs this:
````
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
00:00:00.000 [INFO] [backend/session/logind.c:572] Selecting session from XDG_SESSION_ID: c21
00:00:00.002 [INFO] [backend/session/logind.c:706] Successfully loaded logind session
drm: Connectors:
drm:   DP-1 (disconnected)
drm:   DP-2 (disconnected)
drm:   DP-3 (disconnected)
drm:   HDMI-A-1 (connected)
````
And nothing more.

Works with gamescope commit https://github.com/Plagman/gamescope/commit/8f733a415540131b3bd62501bf6767400010c049.

Bisect log:
````
$ git bisect log 
git bisect start
# bad: [3b14c21afc90884f7cbe8f5205cfe76af86528db] Simplify errorf_errno a bit
git bisect bad 3b14c21afc90884f7cbe8f5205cfe76af86528db
# good: [8f733a415540131b3bd62501bf6767400010c049] rendervulkan: add error logging to init_device
git bisect good 8f733a415540131b3bd62501bf6767400010c049
# bad: [a54b5c9ee010c1c87dfc4c3c0b9c2d04297d60da] Introduce basic logging module
git bisect bad a54b5c9ee010c1c87dfc4c3c0b9c2d04297d60da
# bad: [cba189d389c42dbeb0a18a5072def97ac89179b5] drm: allow wildcard in connector priority list
git bisect bad cba189d389c42dbeb0a18a5072def97ac89179b5
# bad: [51cfc0df061c83fb546dd43ffc8f386de8264810] Implement priority list for -O
git bisect bad 51cfc0df061c83fb546dd43ffc8f386de8264810
# first bad commit: [51cfc0df061c83fb546dd43ffc8f386de8264810] Implement priority list for -O
````

**Comment by Plagman** [comment]
Does it require -O to select any connectors now @emersion ? @Samsagax , can you try `-O *` and `-O HJDMI-A-1` to see both unblock you?

**Comment by Samsagax** [comment]
Thanks for the response @Plagman. `-O *` seems to be required. Adding it to my startup command passes that message but still the session won't start.

[Here is the output](https://gist.github.com/Samsagax/465714938874db5f442e731999f32391)

Maybe the `-O` option needs to default to `*`?

Still won't start though. Reverting to the mentioned last good commit fixes the issue.

**Comment by emersion** [comment]
Yes, gamescope should do the Right Thing by default, will fix!

**Comment by Samsagax** [comment]
On further inspection, from [this line](https://gist.github.com/Samsagax/465714938874db5f442e731999f32391#file-steam-stdout-log-L341) of the output seems to be failing in the `execvp` step of the `steamcompmgr`. How I would go about debugging this?

**Comment by emersion** [comment]
Hm, that's weird. `execvp` will fail if the command doesn't exist.

**Comment by Plagman** [comment]
I can also confirm -O * is needed on master, and then it runs into the same `execvp failed: No such file or directory` error.

**Comment by Samsagax** [comment]
Maybe is an error in parsing input? The command `steam` most certainly exist on my machine :)

**Comment by emersion** [comment]
Ah, I think this happens because of shell expansion shenanigans. Can you try quoting with `-O '*'`?

**Comment by Samsagax** [comment]
Current git build worked great for me with no `-O` option. So that issue is solved. However if I quote the `*` like `-O '*'` (even escaping the single quotes) still get the execvp error. Wouldn't it be better just removing that option entirely since is the default behaviour anyway?

**Comment by emersion** [comment]
`-O` is useful for other things, setting a preference for the KMS output to use.

**Comment by Samsagax** [comment]
> `-O` is useful for other things, setting a preference for the KMS output to use.

Yeah, I'm sure it is. That's not what I meant. I meant to remove the `*` argument for the `-O` option, not the `-O` option entirely. As it causes problems , maybe is better to change `*` for a generic term like `any`.

**Comment by Plagman** [comment]
I can repro the execvp spew and gamescope getting SIGINT when any -O is passed, trying to debug.. at first glance execvp doesn't seem to be happening in gamescope itself.

**Comment by Samsagax** [comment]
> I can repro the execvp spew and gamescope getting SIGINT when any -O is passed, trying to debug.. at first glance execvp doesn't seem to be happening in gamescope itself.

Seems to be happening when spawning the client (in this case Steam itself) circa this line: https://github.com/Plagman/gamescope/blob/8782dc2cd110ef169e7d5abf5e40c94763bf7a05/src/steamcompmgr.cpp#L3182

**Comment by emersion** [comment]
Should be fixed with https://github.com/Plagman/gamescope/commit/5e66e9cee0208dbe0ad4724c36df0a6efb2b86ec.
