### ISSUE TITLE
Screenshots should trigger a new frame repaint

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#247]
Otherwise you can wait for them a long time, if you're sitting on a UI screen that doesn't move.

Note: the screenshot code gets moved by https://github.com/Plagman/gamescope/pull/219/files, so might be worth merging that before fixing this bug.

**Comment by Plagman** [comment]
Capture shouldn't trigger new frame repaints that I know of, however. Will ask Sam if remote play needs a fixed cadence of if it's fine with infrequent updates in UI scenarios.

**Comment by emersion** [comment]
Note, if the PipeWire stream can come from other Wayland compositors such as GNOME or KDE, then the stream won't have a fixed refresh rate.
