### ISSUE TITLE
Add commandline switch to load custom ARGB cursor

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#248]
Source code example to load said cursor:

https://github.com/ValveSoftware/steamos-compositor/blob/master/src/loadargbcursor.c

gamescope should take an optional switch to a PNG file on disk and load it first thing, so people don't have to see the X cross for certain sessions.

In nested mode it should set the same as the default host desktop cursor,but there's already a bug for that maybe.

**Comment by emersion** [comment]
> In nested mode it should set the same as the default host desktop cursor,but there's already a bug for that maybe.

Yup, ref https://github.com/Plagman/gamescope/issues/10

**Comment by Scrumplex** [comment]
Kinda late to the party, but shouldn't this rely on Xcursors instead of arbitrary image files? We could use libxcursor to handle loading the cursors themselves. We would then also not need to pull in STB as a build-time-dependency.

**Comment by emersion** [comment]
@Scrumplex Xcursors are nice when using one of the existing themes. But the intention here is to use a custom cursor image. Xcursor files are a pretty terrible file format, better avoided if we can.
