### ISSUE TITLE
Stretched output with 16:10 aspect ratio and external display hotplug

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#258]
If running gamescope with 1280x800 internal res (16:10), and starting with a 16:9 display, the output is properly pillarboxed. If unplugging the display to fall back to the internal 16:10 display, then re-plugging it, output will be stretched with no pillarboxed, losing proper aspect.

**Comment by Plagman** [comment]
I think we just need to always pick native mode of the display and handle scaling ourselves for now. Later we could have a list of OK non-native modes, like 1080p and 4k.

**Comment by emersion** [comment]
This fixes it for me: https://github.com/Plagman/gamescope/commit/5ac5a1ea2905fc05e37bcc0091641a1d9868f0b4

**Comment by Plagman** [comment]
Still does scaling on a TV we have here and shows a "please use 1080p nag on screen". I think we do need to use native timings always.

**Comment by Plagman** [comment]
I was actually about to push this just when you pushed yours:

```
diff --git a/src/drm.cpp b/src/drm.cpp
index 9aaa8e3..c767bbd 100644
--- a/src/drm.cpp
+++ b/src/drm.cpp
@@ -500,15 +500,9 @@ static bool setup_best_connector(struct drm_t *drm)
                return false;
        }
 
-       const drmModeModeInfo *mode = nullptr;
-       if ( g_nOutputWidth != 0 || g_nOutputHeight != 0 || g_nNestedRefresh != 0 )
-       {
-               mode = find_mode(best->connector, g_nOutputWidth, g_nOutputHeight, g_nNestedRefresh);
-       }
-
-       if (!mode) {
-               mode = find_mode(best->connector, 0, 0, 0);
-       }
+       // TODO add a switch to try to find exact mode, and allow an optional list of good TV modes
+       // For now, always pick native or best available timings, as those tend to yield best results scaling-wise
+       const drmModeModeInfo *mode = find_mode(best->connector, 0, 0, 0);
 
        if (!mode) {
                drm_log.errorf("could not find mode!");
```

Your change is also good in isolation, do you want to put the logic that prefers native in there by default and add an option to prefer exact timings?

**Comment by emersion** [comment]
Yes, that makes sense, will do!
