### ISSUE TITLE
Steam client flickers over games in embedded mode

### ISSUE THREAD

**Issue by Samsagax** [Plagman/gamescope#260]
As described in this issue (https://github.com/ValveSoftware/steam-for-linux/issues/7966) now the same bug propagated out of beta client.

@alkazar found the issue and made a workaround for steamos-compositor-plus here: https://github.com/ValveSoftware/steam-for-linux/issues/7966#issuecomment-917305591

Current steam client can't play any games with Gamescope in embedded session.

**Comment by alkazar** [comment]
I could probably whip up a patch to fix this, however, I feel like the fix might be better done in the Steam client? I am not sure if what is happening there is part of some intentional change or not.

**Comment by Plagman** [comment]
Yeah I think this is just accidentally broken due to work-in-progress changes for the new environment. Will look at whether we can easily unbreak.

**Comment by Plagman** [comment]
Gamescope is out of scope with BP for now and things will keep changing there, so let's track fixing Steam to work on SteamOS 2 / steamcompmgr there in the short term:

https://github.com/Plagman/gamescope/issues/260

**Comment by valentindavid** [comment]
For those who want to get it to work now, I have been using this patch since this weekend, and I have not seen flickers since: https://gitlab.com/valentindavid/experimental-gaming-os/-/blob/c09c4c90fbce4ef5b9eb84e2869bad7d6e6703c0/patches/gamescope/gamescope-flicker-workaround.patch

**Comment by Samsagax** [comment]
I can confirm @valentindavid 's patch fixes the issue. I know it is not a definitive solution but, @Plagman, since it is a small patch and clearly identifiable (and revertable) would you consider merging it as a quick fix until the client gets sorted out?

**Comment by Plagman** [comment]
That would break our internal development, unfortunately. There is a fix in the Steam client that is scheduled to release to Beta this week.

**Comment by Plagman** [comment]
Can you confirm the current Beta fixes this?

**Comment by Plagman** [comment]
Thanks for confirming!
