### ISSUE TITLE
Build issue missing wayland-protocols

### ISSUE THREAD

**Issue by theterk** [Plagman/gamescope#276]
I've installed Wayland 1.19 and wayland-protocols through pacman and hit this fail.  I then manually pulled wayland-protocols from git. made, ninja, installed, and still hit this error.  Is this another submodule that needs to be included?
[meson-log.txt](https://github.com/Plagman/gamescope/files/7178138/meson-log.txt)

**Comment by emersion** [comment]
No, it just seems you still have an old wayland-protocols installed.

**Comment by theterk** [comment]
Thanks, got confused by what Manjaro installed by default and the github install.  went ahead and downloaded the 1.22-1 version from AUR
