### ISSUE TITLE
Certain games and elements do not update until input

### ISSUE THREAD

**Issue by mason1920** [Plagman/gamescope#294]
Certain games (Planetary Annihilation: Titans) and elements (opening the map in GTFO) do not update the frame(s) until a mouse is moved over the window or a key is pressed.

**Comment by ppascher** [comment]
Possibly duplicate of #277

**Comment by mason1920** [comment]
Hm! Redraw: Probably a good word to describe it; I should've searched for that. Well, thanks for expanding my vocab, I'm going to close this now, it looks like the same problem I'm having.
