### ISSUE TITLE
Vulkan applications/games do not work in Gamescope

### ISSUE THREAD

**Issue by DavidHusicka** [Plagman/gamescope#308]
When I try to run applications or games that use Vulkan API then the applications do not either start gamescope window at all or gamescope window appears but remains black with nothing in it. Setting `R600_DEBUG=nodcc` does not help. I can confirm that OpenGL works (needs `R600_DEBUG=nodcc`). I am running AMD Renoir iGPU with Mesa 21.2.5-1 from Arch repositories.

[vulkaninfo.txt](https://github.com/Plagman/gamescope/files/7555171/vulkaninfo.txt)
[gamescope-vkcube.log](https://github.com/Plagman/gamescope/files/7555323/gamescope-vkcube.log) (killed with ctrl+c in the terminal)

**Comment by Joshua-Ashton** [comment]
Works fine for me on Renoir. Does it work with Mesa git?

**Comment by DavidHusicka** [comment]
> Works fine for me on Renoir. Does it work with Mesa git?

I installed mesa-git from AUR and tried again (`./gamemode -- vkcube`) and still the same.

**Comment by Joshua-Ashton** [comment]
Are you on Gnome Wayland? If so, there is no modifier support there so it probably won't work.

**Comment by DavidHusicka** [comment]
It doesn't work on sway either. Changing the kernel from lts to the latest one solves the issue.
