### ISSUE TITLE
X-side synthetic input broken with latest commits

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#32]
can be reproduced in nested:

./gamescope -e -- steam -tenfoot -steamos

Connect a Steam controller or any controller, launch Factorio or any game that uses the normal OS cursor, configure a mouse mode on the trackpad, observe that cursor doesn't move when mouse input is issues despite the game properly reacting to the X-side cursor position.

**Comment by subdiff** [comment]
Some observations:
At 95caa5c2fc8c it still works in the following way:

* On nested the Steam controller moves the cursor and when using the mouse afterwards the cursor begins movement from the last position the cursor was moved to by the controller.
* On DRM the mouse cursor moves with the controller but as soon as the mouse is moved the cursor jumps back to the position the cursor was before moving it with the controller.

The first bad commit is 0f8d67999. But at this point I am still able to move the cursor with the controller after either clicking once with the controller touchpad or moving the cursor with the mouse.

This is then also not possible anymore with be1ff3d.

Tested games: Portal, CS GO.

**Comment by subdiff** [comment]
I have reverted some commits now from master. Needs to be tested some more if this is enough to solve the issue.

They are reapplied on the following branch to further look for a solution within that concept: https://github.com/Plagman/gamescope/tree/direct-wl-cursor
