### ISSUE TITLE
[Flatpak] Linux Graphical Issues on AMD

### ISSUE THREAD

**Issue by pyamsoft** [Plagman/gamescope#320]
I apologize in advance if this issue is not supported by gamescope, as it may be a flatpak issue.

--

I am observing what I believe so far is an issue with gamescope on my AMD system.

Some background context, I am using a flatpak of gamescope running in a flatpak of Steam. Both flatpaks are pulled off of Flathub. My host system is an Arch Linux system with an AMD 5500XT GPU and a Ryzen R5 1600 CPU.

The issue I am observing seems to affect any game I try on Steam, though it is not always consistent. It has so far been consistent in the game "Don't Starve Together'.

When running the game via gamescope using the following launch command
`vblank_mode=0 gamescope -- %command%`

The game loads and appears as follows:
![dont-starve-gamescope](https://user-images.githubusercontent.com/7267458/144963619-efbaad9d-3d66-4e57-8ea3-27f423b93386.png)

When I launch the game without gamescope, using the following launch command though, the issue goes away
`vblank_mode=0 %command%`.
![dont-starve](https://user-images.githubusercontent.com/7267458/144963684-5fdf95bf-a770-44ed-82e7-9b39787874d5.png)

Gamescope is version `3.9.5` and Steam is running on the Linux runtime `steam-runtime_0.20211102.0`

Please let me know if there is anymore information you need from me, or if I should take this issue up with the flatpak maintainer for gamescope instead. Thank you.

**Comment by Joshua-Ashton** [comment]
Looks like DCC. If your system mesa is different to the environment gamescope is running in and you are running on X or Wayland without modifiers (ie. mutter), then this is unavoidable.

I imagine RADV_DEBUG=nodcc + AMD_DEBUG=nodcc fixes it?

If so, should probably take this up with your compositor to implement modifiers or on X... I guess xf86-amdgpu to implement modifiers :frog:

**Comment by pyamsoft** [comment]
What a wizard.

Thank you for your quick and helpful response. Your suspicion was correct, adding both `RADV_DEBUG=nodcc` and `AMD_DEBUG=nodcc` fixed the problem immediately!

For any future readers, the launch line changes to 

`vblank_mode=0 AMD_DEBUG=nodcc RADV_DEBUG=nodcc gamescope -- %command%`

Thank you for your help and this great project!
