### ISSUE TITLE
Support several Xwaylands

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#328]
So we get proper virtualized focus, resolutions and refresh rates across different clients in embedded.

We'd have several steamcompmgr threads, one per, each contributing their focused window(s) for one output thread to composite/present. Good opportunity to pave the way for multiple output threads, one per display.

**Comment by emersion** [comment]
I'd advise against adding more threads. They're already causing enough pain, and they don't add any benefit. A proper event loop should be enough.

**Comment by Joshua-Ashton** [comment]
Started work on this here: https://github.com/Plagman/gamescope/tree/multiple-xwaylands
