### ISSUE TITLE
exiting 'duke nukem 3d megaton edition (classic)' crashes xwayland

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#34]

**Comment by Plagman** [comment]
also same with wizardry 7, either exiting normal or starting 'dosbox baum' mode

**Comment by kode54** [comment]
I find it's crashing every time it exits, in libc's `__run_exit_handlers`

**Comment by emersion** [comment]
Note, this is a gamescope crash, not an Xwayland crash.

Gamescope crashing on exit is a known separate issue, see e.g. https://github.com/Plagman/gamescope/issues/46

**Comment by Plagman** [comment]
I suspect this will be fixed by the same fix as https://github.com/Plagman/gamescope/issues/39, which I'm currently trying to write.

**Comment by Plagman** [comment]
Can't seem to repro this symptom with that fixed.
