### ISSUE TITLE
Uplay does not work with Gamescope

### ISSUE THREAD

**Issue by Odelpasso** [Plagman/gamescope#35]
Hello Mister Plag',

When i launch UPlay with gamescope `gamescope -- wine Uplay.exe`, it does not work.
I attach the output log + a screenshot from gamescope window.

![Capture du 2020-04-11 20-30-24](https://user-images.githubusercontent.com/3606036/79052036-f5f6f400-7c33-11ea-9721-07935089db54.png)
[Uplay_gamescope.txt](https://github.com/Plagman/gamescope/files/4465159/Uplay_gamescope.txt)

cheers,
Odelpasso/Babaowhisky

**Comment by Plagman** [comment]
Think you need  R600_DEBUG=nodcc. I'll probably just make gamescope set it on itself before loading Mesa until we don't need it anymore.

**Comment by Plagman** [comment]
Can you try again on latest?

**Comment by Odelpasso** [comment]
Hi,

I can't try unfortunatly. I'm in holiday for the 3 next weeks.
I could try when i'm back.

**Comment by emersion** [comment]
Closing for now, please re-open if it still doesn't work.
