### ISSUE TITLE
Not an issue: Build dependencies for Fedora 35

### ISSUE THREAD

**Issue by rbjorklin** [Plagman/gamescope#371]
Leaving this here because it would have saved me a couple of minutes.

Fedora 35 only packages wayland 1.19 at the time of me writing this which means I was unable to build the latest version of gamescope. I was however able to build `git checkout 3.10.3`

```
dnf install -y meson \
cmake \
libX11-devel \
libXdamage-devel \
libXcomposite-devel \
libXrender-devel \
libXext-devel \
libXxf86vm-devel \
libXtst-devel \
libXres-devel \
libdrm-devel \
mesa-vulkan-devel \
wayland-devel \
wayland-protocols-devel \
libxkbcommon-devel \
libcap-devel \
SDL2-devel \
mesa-libgbm-devel \
systemd-devel \
pixman-devel \
libinput-devel \
libseat-devel \
libxcb-devel \
xcb-util-wm-devel \
glslang \
pipewire-devel \
stb-devel
```

PS. If `meson` has a built in way of enumerating and/or installing build dependencies I'd be happy to know about it and maybe there could be a note in the readme?

**Comment by eli-schwartz** [comment]
> PS. If `meson` has a built in way of enumerating and/or installing build dependencies I'd be happy to know about it and maybe there could be a note in the readme?

```
meson wrap install wayland
```

This project already has a couple of subprojects installed in `subprojects/`, but meson makes it trivial (one ini file) to add any dependency as a vendored subproject as long as it already uses meson or has been ported to meson and added to the meson WrapDB.

**Comment by emersion** [comment]
Updated https://github.com/Plagman/gamescope/wiki/Distribution-specific-instructions, thanks
