### ISSUE TITLE
Recent modifier-related activity in Mesa breaks us (further)

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#40]
Usually we'd just have to set R600_DEBUG=nodcc to avoid format mismatch for OpenGL clients, but Vulkan clients would be fine. As of recent Mesa this is no longer the case and this commit has to be reverted for Vulkan clients to work:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/2801

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4298

**Comment by emersion** [comment]
No need to apply my Mesa patch anymore now that https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/6274 has been merged.
