### ISSUE TITLE
Gamescope process hangs after game closes

### ISSUE THREAD

**Issue by adolfintel** [Plagman/gamescope#406]
With the current master, the gamescope process doesn't close when the game ends. The process doesn't respond to signals either and needs to be killed with SIGKILL to end it. Other than that, it works perfectly.

Tested with multiple games on multiple hardware configurations.

Command: `gamescope -f -- anything`

Gamescope version: >=3.11, including current master
OS: Manjaro 21.2 (Linux 5.16 kernel)
DE: KDE Plasma 5.23, Xorg
GPU: Both AMD and Intel

**Comment by Samsagax** [comment]
Did it happened before? Are you able to bisect the issue?

**Comment by massatt212** [comment]
Didn't happen before, but I'm not home.

**Comment by Samsagax** [comment]
> Didn't happen before, but I'm not home.

In which version? I'm not able to reproduce the issue. When the game exits, gamescope just finishes.

**Comment by adolfintel** [comment]
Bisected to commit c5ab6f388b20aae388d543b9f1879471e3b17df9

**Comment by massatt212** [comment]
https://www.youtube.com/watch?v=xZ69WADj4wM

A video to show whats going on

**Comment by adolfintel** [comment]
Awesome, the new commit works. Thanks for your work!
