### ISSUE TITLE
games won't show up if tried to launch with steam overlay. fixes after reboot.

### ISSUE THREAD

**Issue by IDDQD69** [Plagman/gamescope#407]
gamescope 3.11.9 
archlinux
kde 
amd gpu

1. game is working
2. toggle on steam overlay
3. game crashes 
4. toggle of steam overlay
5. game shows as running, but doesn't show up
6. reboot (tried restarting steam, logging out, but only reboot seems to work)
7. game works again.

Every time if i try to use steam overlay i have to reboot my computer to make it work again. Does not happen with all of the games, but does for wrechfest, withcer3 etc.

**Comment by GithubUser5462** [comment]
Probably related to https://github.com/Plagman/gamescope/issues/382

**Comment by bg2908** [comment]
>     5. game shows as running, but doesn't show up
> 
>     6. reboot (tried restarting steam, logging out, but only reboot seems to work)
>
> Every time if i try to use steam overlay i have to reboot my computer to make it work again.

After the game is crashed, there are still some lingering processes of the game and wine. Use htop or system-monitor to find and kill all those processes off. Then you can run the game again. No need for reboot.
