### ISSUE TITLE
Heavy flickering on gamescope standalone mode

### ISSUE THREAD

**Issue by mercuriete** [Plagman/gamescope#412]
**Description:**

When opening steam big picture using gamescope as standalone and then opening a game. The game starts to flicker as if that game is not focused and fighting for the focus against big picture.

**Steps to reproduce**

there are two ways to reproduce:
A
1. open konsole
2. launch the following command ```/usr/bin/gamescope -U -w 1920 -h 1080 -W 1920 -H 1080 -f -- steam steam://open/bigpicture```
3. open a game from library
4. see a big flicker that makes imposible to play the game

B
1. drop the following file to xsessions
```
cat /usr/share/xsessions/gamescope.desktop 
[Desktop Entry]
Name=SteamOS
Comment=SteamOS
Exec=/usr/bin/gamescope -U -w 1920 -h 1080 -W 1920 -H 1080 -f -- steam steam://open/bigpicture
TryExec=/usr/bin/gamescope
Type=Application
X-LightDM-DesktopName=SteamOS
DesktopNames=SteamOS
Keywords=windowmanager;window;manager;
```
2. reboot the computer
3. go to your desktop display manager (sddm in my case)
4. select SteamOS session on the drop down
5. login
6. open a game from the library
7. see a big flicker that makes imposible to play the game

**Aditional Info**
distro: Gentoo Linux
gamescope: 3.11.10 compiled by me
```
inxi -GSC -xx
System:    Host: msi-b450 Kernel: 5.15.23-gentoo x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: KDE Plasma 5.23.5
           tk: Qt 5.15.2 wm: kwin_x11 dm: SDDM Distro: Gentoo Base System release 2.7
CPU:       Info: 8-Core model: AMD Ryzen 7 2700X bits: 64 type: MT MCP arch: Zen+ rev: 2 cache: L2: 4 MiB
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 118394
           Speed: 2027 MHz min/max: 2200/3700 MHz boost: enabled Core speeds (MHz): 1: 2027 2: 2024 3: 1987 4: 1903 5: 2447
           6: 2548 7: 2389 8: 2744 9: 2357 10: 2300 11: 3951 12: 2429 13: 2974 14: 2394 15: 2651 16: 2782
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] vendor: Sapphire Limited
           driver: amdgpu v: kernel bus-ID: 1e:00.0 chip-ID: 1002:73bf
           Device-2: Focusrite-Novation Scarlett 2i2 Camera type: USB driver: snd-usb-audio bus-ID: 1-1:2 chip-ID: 1235:8210
           Device-3: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-1:2 chip-ID: 046d:0825
           Display: x11 server: X.Org 1.21.1.3 compositor: kwin_x11 driver: loaded: amdgpu resolution: 1: 1920x1080~72Hz
           2: 1920x1080~60Hz s-dpi: 96
           OpenGL: renderer: AMD Radeon RX 6900 XT (sienna_cichlid LLVM 13.0.0 DRM 3.42 5.15.23-gentoo) v: 4.6 Mesa 22.0.0-rc2
           direct render: Yes
```

**Comment by Samsagax** [comment]
I think you should add `-e` option to gamescope call. Is a special mode for embedded working along the steam client.

Here is a working call without flickering (it will flicker a lot without `-e`:

`/usr/bin/gamescope -e -f -W $SCREEN_W -H $SCREEN_H -w $RENDER_W -h $RENDER_H -- steam -tenfoot -sfeamos`

Taken from https://github.com/Samsagax/gamescope-session

**Comment by mercuriete** [comment]
Thank @Samsagax I will try it as soon as possible
:)

**Comment by mercuriete** [comment]
Thanks @Samsagax 
It works perfectly for me.

I will close this issue.
