### ISSUE TITLE
GAMESCOPE_FOCUSED_APP behavior in Steam mode / non-Steam mode

### ISSUE THREAD

**Issue by rbernon** [Plagman/gamescope#416]
We're tracking GAMESCOPE_FOCUSED_APP in Proton to decide whether we should drop input events or not, when running under gamescope, and when Steam mode isn't used the property seems to be set to the Window IDs instead of App IDs.

I wondered if it could be possible for gamescope to not set that property at all when not running in Steam mode. It would make things simpler, and after all, there's no APP ID when not running with Steam.

Another easy option would be to tell use whether Steam mode is used or not, for instance with an environment variable, assuming gamescope spawns the Wine process, or another X11 property.

**Comment by massatt212** [comment]
With the new 7.0-1 proton gamescope won't run in steam is compositor
