### ISSUE TITLE
DOOM Eternal black buffers in embedded

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#42]
But is consistently fine for me on a desktop or nested. DOOM 2016 is fine too. Maybe Vega vs. Raven? Haven't tried nested on Raven, maybe good next step.

**Comment by emersion** [comment]
Getting black buffers on a RX 580 as well.

When compositing is used (e.g. when drawing a cursor or with `-c`) I get completely black buffers. However when using direct scan-out the game buffer appears very small (perhaps 200x200px) on the top left corner. The KMS properties (`SRC_*` and `CRTC_*`) seem to be fine.

**Comment by emersion** [comment]
Actually, on my Ryzen 5 3500U, I'm able to reproduce the black buffers and the flickering very small image:

![20200611_16h51m32s_grim](https://user-images.githubusercontent.com/506932/84402853-4cb58580-ac05-11ea-8b7e-8b8c49b12bf9.png)

The game sometimes silently crashes, sometimes uses 100% CPU and sometimes stays black.

**Comment by Plagman** [comment]
Black buffers running the Origin setup process (possible after https://github.com/Plagman/gamescope/issues/62 was fixed) as well, can be observed doing first time setup for Crysis 3. This is more blocking than DOOM Eternal as it affects a bunch of different games.

**Comment by emersion** [comment]
With https://github.com/Plagman/gamescope/pull/73 I noticed this issue also happens when painting the texture using wlroots and OpenGL. That means the bug isn't related to the way we import buffers or to Vulkan: the client submits a bad buffer.

The bug doesn't happen when running the game outside of gamescope, so I'd bet on an XWM bug maybe.

**Comment by emersion** [comment]
Here's an `xwininfo` dump when the game runs inside gamescope (and is buggy):

```
     0x3400001 "DOOMEternal": ("doometernalx64vk.exe" "steam_app_782330")  1280x720+0+0  +0+0
        1 child:
        0x3001d6c (has no name): ()  160x24+0+0  +0+0
```

And here's the same when the game runs inside Sway (works as expected):

```
     0x2600001 "DOOMEternal": ("doometernalx64vk.exe" "steam_app_782330")  1920x1080+0+0  +0+0
        1 child:
        0x2200145 (has no name): ()  1920x1080+0+0  +0+0
```

**Comment by emersion** [comment]
Can reproduce with Detroit too, with a similar `xwininfo` dump:

```
     0x2e00001 "Detroit: Become Human": ("detroitbecomehuman.exe" "steam_app_1224230")  1280x720+0+0  +0+0
        1 child:
        0x2c00033 (has no name): ()  160x24+0+0  +0+0
```

**Comment by Plagman** [comment]
Apparently caused by: https://github.com/Plagman/gamescope/issues/79
