### ISSUE TITLE
Doesn't work with amdgpu(foss driver)+5300U vega gpu.

### ISSUE THREAD

**Issue by kubast2** [Plagman/gamescope#440]
```
$ gamescope
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'Unknown AMD GPU'
vulkan: physical device does not support DRM format modifiers
vulkan: vkAllocateDescriptorSets failed
Failed to initialize Vulkan
```

**Comment by kubast2** [comment]
Also tried with a native linux steam game;

**Comment by kubast2** [comment]
[vulkaninfo.txt](https://github.com/Plagman/gamescope/files/8199547/vulkaninfo.txt)

**Comment by Samsagax** [comment]
> [vulkaninfo.txt](https://github.com/Plagman/gamescope/files/8199547/vulkaninfo.txt)

From the first lines of your file seems you are using amdvlk instead of radv driver. Maybe there is a free+non-free mixup?

**Comment by kubast2** [comment]
Allright gonna try it out everything seems to be looking fine.

**Comment by Samsagax** [comment]
Seems like the Amdvlk driver doesn't support most features gamescope relies upon. If you have both drivers installed you can force radv with `AMD_VULKAN_ICD=RADV` environment variable.
