### ISSUE TITLE
gamescope throttles fps when workspace is unfocused

### ISSUE THREAD

**Issue by bgkillas** [Plagman/gamescope#441]
it seems that while my workspace that gamescope is on is unfocused the fps of the game is throttled
wm:sway
distro:arch
how to test: open btop or something in 1 workspace and game with gamescope in another see cpu usage go down alot while it is unfocused
this makes so if i am the host in say risk of rain 2 and switch workspace the clients see extreme lag from the monsters

**Comment by Joshua-Ashton** [comment]
This is inherently unfixable from our end. Sway (intentionally) doesn't send frame callbacks for windows on other workspaces.

I attempted to fix it with something like https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/99 but people seemed not very interested in it.

At this point, I am kind of of the opinion that we should just start shipping useful protocols like this and others to end users and have them be supported in Mesa + Plasma, etc without all the months->years of bikeshedding of the wayland-protocols repo.

**Comment by bgkillas** [comment]
> This is inherently unfixable from our end. Sway (intentionally) doesn't send frame callbacks for windows on other workspaces.
> 
> I attempted to fix it with something like https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/99 but people seemed not very interested in it.
> 
> At this point, I am kind of of the opinion that we should just start shipping useful protocols like this and others to end users and have them be supported in Mesa + Plasma, etc without all the months->years of bikeshedding of the wayland-protocols repo.

then why if i dont run the game in gamescope it seems to act fine? i think this is on gamescopes end somehow

**Comment by Joshua-Ashton** [comment]
Do you have vsync disabled in the game when you run it without gamescope?

**Comment by bgkillas** [comment]
> Do you have vsync disabled in the game when you run it without gamescope?

i did sure is weird, why not just give an option to disable vsync in gamescope or would that cause issues?

**Comment by rhoot** [comment]
I found this issue while looking to see if gamescope could help with this exact problem in a game actually. Specifically: I turned off vsync in that game (Final Fantasy XIV) to avoid it locking up when switching workspaces. But now my game renders at 300 FPS, which is 3x more than I need. So I was thinking I could run it in gamescope and limit its FPS that way.

But given this issue I'm back to square one on that. It'd be neat if you could forcefully disable vsync for gamescope when run nested to allow it to be part of the solution: I could disable vsync for gamescope to not have it stall when I switch workspaces, but still limit the game inside gamescope to a reasonable FPS. Giving me the best of both worlds.

**Comment by MithicSpirit** [comment]
I know this is necroposting by two years (maybe I should just open a new issue?), but this issue is still present for me and I think that this

> why not just give an option to disable vsync in gamescope or would that cause issues?

could fix it. I've found that disabling vsync for games not running in gamescope fixes the issue entirely, but has no effect if they are inside gamescope. I believe that this is because gamescope itself has a limited fps since it is itself vsynced.
