### ISSUE TITLE
Borderlands 3, mouse look doesn't work when gamescope is launched;

### ISSUE THREAD

**Issue by kubast2** [Plagman/gamescope#442]
Launch options in steam:
``gamescope -h 486 -H 1080 -U -- %command%``

Proton settings:
* In all other games
* Proton 7.0-1

**Comment by MrKingMichael** [comment]
Please try adding `-e` to that command and letting us know how it goes.

**Comment by kubast2** [comment]
Oh

**Comment by kubast2** [comment]
Oh
