### ISSUE TITLE
Failed to initialize Vulkan on RX 6700 XT

### ISSUE THREAD

**Issue by SaphiraKai** [Plagman/gamescope#447]
I can't launch gamescope on my system. I assume simply running `gamescope` should result in an error telling me I haven't selected a game or just do nothing, but instead I get:
```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'AMD Radeon RX 6700 XT'
vulkan: physical device does not support DRM format modifiers
vulkan: vkAllocateDescriptorSets failed
Failed to initialize Vulkan
zsh: segmentation fault (core dumped)  gamescope
```

Prior to running `gamescope` in the terminal, I also tried various combinations of `gamescope -- %command% -nojoy -novid -high` in the Steam launch options for CS:GO, but the game failed to launch and I assume this error is the reason.

There isn't much information in the README about the necessary driver setup, is there something I'm missing?

**Comment by rurigk** [comment]
Can you add system info?

Kernel version, AMDGPU driver version
Mesa version if you are using RADV (mesa)
Or if you are using AMDGPU_PRO or AMDVLK

You have libdrm and lib32-libdrm installed?

**Comment by SaphiraKai** [comment]
`linux 5.16.11-zen1-2-zen`
`mesa 21.3.7-2`
`amdvlk 2022.Q1.3-1`

Yes, I have both `libdrm`s installed

**Comment by Samsagax** [comment]
> `linux 5.16.11-zen1-2-zen` `mesa 21.3.7-2` `amdvlk 2022.Q1.3-1`
> 
> Yes, I have both `libdrm`s installed

I think the amdvlk driver doesn't support some Vulkan extensions. You should be using radv driver from mesa.

**Comment by SaphiraKai** [comment]
That seems to have fixed it, it's launching now. Thanks!

**Comment by shadow7412** [comment]
> You should be using radv driver from mesa.

What do you install for that? Uninstalling amdvlk makes vulkaninfo error for me...
