### ISSUE TITLE
Unable to set higher than native resolution for most games

### ISSUE THREAD

**Issue by SaphiraKai** [Plagman/gamescope#451]
The main reason I looked at gamescope is its ability to render games at higher resolutions and downscale to 1080p for my monitor, because I have a powerful graphics card and a lot of games just really suck at antialiasing.

Unfortunately, neither CS:GO nor Apex Legends seem to work properly when I set a higher than native resolution. I've tried all kinds of variations of `gamescope -h 2160 -H 1080 -- %command%`, but CS:GO seems to see right through it somehow and only lets me select 1080p, while Apex *sees* 2160p but when I try to select it, gets really bugged and resets to 720p, and both games have a blurry picture even when running at 1080p..

I managed to get BallisticNG working at 4K without issue.

```
distro: Arch Linux
kernel: 5.16.15-zen1-1-zen
gpu:    AMD Radeon RX 6700 XT
driver: mesa/radv 21.3.7
```

**Comment by sonic2kk** [comment]
I've tested CS:GO (native Linux) and I can run it just fine with Gamescope at a higher resolution. Plasma reports my scaled 4k display as 1440p so I use Gamescope to force games to run at 4k. It's not the same use-case exactly but the premise should be the same. I can select 4k in CS:GO when using Gamescope. I cannot test Apex Legends or BallisticNG so I'm not sure about them.

What desktop environment are you using? And not that it should really make too much of a difference, are you using X11 or Wayland? I tested on KDE Plasma Wayland. I'm also using Mesa 21.3.7 on a 5700XT.

If problems persist, you can try installing and building Gamescope from source if you haven't already, and failing that you could take a look at [SteamTinkerLaunch](https://github.com/frostworx/steamtinkerlaunch) as a way of configuring and running games with Gamescope to see if you have any more luck - Though this isn't so much a fix as a long-shot partial workaround for what might be a wider issue.

**Comment by SaphiraKai** [comment]
Sorry for the late response!

I'm using instantWM, which is a fork of dwm, and runs on X11.
I've also tried running it in embedded mode from the tty, but that flat out didn't work. Started a display for a second or two but then crashes back to the tty.

I'll try building gamescope from source, and let you know how that goes.

**Comment by SaphiraKai** [comment]
Okay... I'm not sure what changed, but suddenly it just works. Bizarre
