### ISSUE TITLE
Total Warhammer 3 not using -H resolution

### ISSUE THREAD

**Issue by raaffaaeell** [Plagman/gamescope#470]
Hello, I'm not sure if I understand this correctly. but I'ld like to use FSR upscaling like so

`gamescope -h 720 -H 1080 -f -e -U  -- %command%`

and 

`gamescope  -w 1280 -W 1980 -h 720 -H 1080 -f -e -U  -- %command%`

When I get into the game and check the resolution it says 720p and the UI is like it's still 720, not 1080p

Am I doing something wrong ? 

Cheers

**Comment by Samsagax** [comment]
I think you misunderstood the pipeline there. `-h` and `-w` lie to the game telling it is run on a smaller screen size. Then `-H` and `-W` are the output gamescope will upscale to. The FSR thecnique (or nearest neighbors by default) is applied by gamescope to upscale between the lowercase and uppercase options. The game doesn't see that and doesn't care about it.

**Comment by raaffaaeell** [comment]
Sorry, but I still dont understand how I'ld go about using fsr with gamescope. How would I be able to have the 1080p being upscaled from a lower resolution.

Currently I have just  720p blurry UI, not 1080p blurry UI (if that makes any sense)

**Comment by raaffaaeell** [comment]
This is how the game looks when I use the flags like in my first post and the resolution available

![image](https://user-images.githubusercontent.com/6959662/164778336-1ed6990a-b7ac-4f37-8caf-832b85a361fa.png)

![image](https://user-images.githubusercontent.com/6959662/164778424-9965aa32-a279-4100-8c01-4c18034c4170.png)

This is 1080p (without gamescope, fullscreen)

![image](https://user-images.githubusercontent.com/6959662/164778893-59c1e73a-046c-4570-93cf-aa978118d53e.png)

The unit cards in the gamescope are smaller than the ones without gamescope, despite being the same resolution. Does it make sense now ?

I understand why the UI is blurry, what I'm trying to understand is why I'm getting 720p blurry instead of 1080p blurry, or if I misunderstood how the gamescope implementation works

Thanks in advance, guys

**Comment by pmartiner** [comment]
@raaffaaeell gamescope is behaving as expected: you're telling it to upscale a 720p UI to a 1080p resolution. The reason why you're seeing it so sharp without gamescope is because you're running it at native resolution, not upscaled from 720p

**Comment by raaffaaeell** [comment]
@pmartiner It's not about the sharpness. The width of the unit cards is not the same between the screenshots, for example.

**Comment by Samsagax** [comment]
> @pmartiner It's not about the sharpness. The width of the unit cards is not the same between the screenshots, for example.

I see your issue and that's nothing gamescope could help. Is a decision made from the game to render in 720 that UI element based on what the developer thought was right for that screen resolution. Since the game thinks the screen is 720, then it will render at 720 UI elements. Some games are more clever than it and provide a slide to scale UI elements, but I'm afraid this time the developer took the decision from you.
