### ISSUE TITLE
Desktop Entries created for Programs ignore launch options

### ISSUE THREAD

**Issue by jaylittle** [Plagman/gamescope#479]
I discovered today while configuring an older game with Bottles that if I setup a programs entry for the game, apply launch options to it (e.g. gamescope scaling options) and then create a desktop entry... that using the desktop entry to launch the game appears to ignore the launch options.  The launch options are only used when I open bottles, go into the bottle, go into the list of programs and launch the program from that list.

**Comment by Joshua-Ashton** [comment]
I don't think this bug is related to Gamescope at all. You should forward this to the Bottles developers.

**Comment by jaylittle** [comment]
Oh ffs - I totally posted this in the wrong repo.  Please accept my apologies.
