### ISSUE TITLE
Nvidia 515.43.04 30 FPS hard limit

### ISSUE THREAD

**Issue by StayBlueee** [Plagman/gamescope#490]
It seems as though that Gamescope is artificially limiting the refresh rate of the game to 30, no matter what I set the refresh rate to using -r. This causes terrible screen tearing and horrible performance.

Reproducible on both Xorg and Wayland.

**Comment by gnusenpai** [comment]
I think this is a performance issue with the current beta driver. Maybe try a really low resolution like 360p or 480p. Anything higher, and I get strange back-and-forth frame timing issues.

**Comment by tmespe** [comment]
I'm having the same issues. The performance is fine without gamescope.

**Comment by StayBlueee** [comment]
> I think this is a performance issue with the current beta driver. Maybe try a really low resolution like 360p or 480p. Anything higher, and I get strange back-and-forth frame timing issues.

This only happens when gamescope is in use, so I don't think it matters what resolution I use if the performance I get on gamescope is objectively worse.

**Comment by kodatarule** [comment]
Ok there's more than meets the eye here as gpu is barely being used by gamescope...

**Comment by kodatarule** [comment]
Alright further testing gpu usage is fixed by setting - sudo setcap 'cap_sys_nice=eip' /usr/bin/gamescope   however this still doesn't fix the lock to 31fps and very weird I wouldn't say frame timing as that's not the indication of mangohud but there's definitely something like - back-and-forth timing going on, will debug more

**Comment by RyzenDew** [comment]
i will test your fix

**Comment by RyzenDew** [comment]
> sudo setcap 'cap_sys_nice=eip' /usr/bin/gamescope

yes this fix does work

**Comment by RyzenDew** [comment]
![image](https://user-images.githubusercontent.com/84041391/168099364-121e0396-25d4-45ac-b3a5-9d600a769733.png)
it's in slow mo

**Comment by gnusenpai** [comment]
> Anything higher, and I get strange back-and-forth frame timing issues.
I believe latest master has resolved the weird frame timing issues I was having, but performance is about the same.

**Comment by kodatarule** [comment]
Doesn't resolve for me, performance like you noted in the previous session goes into CPU, it's like it doesn't use the GPU at all, even with cap_sys_nice it goes to some higher like 60% usage but totally improper clocks and everything being weird.

**Comment by Joshua-Ashton** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/21316711/168938593-5d6e2db2-c120-4d18-b933-c1ba753bac00.png)

Can you give the output of `gamescope -- glxinfo | grep version`? Perhaps you are ending up using LLVMPipe for something?

**Comment by Joshua-Ashton** [comment]
Okay, I tried running Steam Deck UI + HL2 and wow it does run bad yeah.

**Comment by StayBlueee** [comment]
> Cannot reproduce with glxgears.
> 
> ![image](https://user-images.githubusercontent.com/21316711/168938593-5d6e2db2-c120-4d18-b933-c1ba753bac00.png)
> 
> Can you give the output of `gamescope -- glxinfo | grep version`? Perhaps you are ending up using LLVMPipe for something? Were you using embedded or nested? Does it only happen in more intensive apps?

You already mentioned how you tested it in HL2 and the performance is worse but I would like to also mention that glxgears doesn't seem to have this frame limit issue on X11 (haven't tested Wayland but I imagine it's the same on Wayland as well). Any game with remotely any level of intensity seems to be suffering from this issue.

Maybe the issue is not present on OpenGL?

**Comment by StayBlueee** [comment]
Another observation is no matter how intensive the game is, the resolution seems to be the biggest determining factor as to what frame rate the game is capped at (higher resolution = lower FPS). Maybe there is some sort of buffer of some kind that is being maxed out on the Nvidia driver? Not sure.

**Comment by StayBlueee** [comment]
Issue fixed with the [latest Nvidia driver, 515.48.07](https://www.nvidia.com/Download/driverResults.aspx/189809/en-us)
