### ISSUE TITLE
Poor performance on Nvidia 515.43.04

### ISSUE THREAD

**Issue by sad-goldfish** [Plagman/gamescope#492]
I'm opening this issue because it's not quite the same as #490. Running Gamescope latest git with Nvidia 515.43.04 produces poor performance and significant screen tearing on both X and Wayland.
`gamescope -W 1920 -H 1080 -w 3840 -h 2160 -f -- glxgears -fullscreen`
On a GTX 1080 glxgears runs at 50fps, well below the monitor framerate. And clearly shows screentearing.
Logs:
```
vulkan: selecting physical device 'NVIDIA GeForce GTX 1080'
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x558a29a0bff0 (res 0x558a2a3d5460)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 75
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
pipewire: renegotiating stream params (size: 2560x1440)
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x558a29815300 (res 0x558a2a3dbe70)
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
(EE) failed to read Wayland events: Broken pipe
X connection to :1 broken (explicit kill or server shutdown)
```
EDIT: Monitor reported 50fps, glxgears reports ~8fps

**Comment by sad-goldfish** [comment]
I get similar results doing `gamescope -W 1920 -H 1080 -w 3840 -h 2160 -f -- glxgears -fullscreen` although the framerate is slightly better.

**Comment by sad-goldfish** [comment]
Could it be because it's a [pascal card](https://github.com/HansKristian-Work/vkd3d-proton/issues/465#issuecomment-752636506)?

**Comment by kodatarule** [comment]
No I experience 31fps hard fps limit on an RTX 3070

**Comment by hashworks** [comment]
Same here with glxgears @ RTX 3070, ~21 FPS on 1080p and ~12 FPS on 1440p.

**Comment by notpentadactyl** [comment]
> Same here with glxgears @ RTX 3070, ~21 FPS on 1080p and **~12 FPS on 1440p.**

I get 12fps locked in Bloons TD 6 on a 3080 at 1440p.

**Comment by mkaito** [comment]
`gamescope -W 1920 -H 1080 -w 3840 -h 2160 -f -- mangohud glxgears -fullscreen` gives me 3 fps on a 3080 Ti. I also get exactly 3 fps in a few random games I tried, some native, some not: Factorio, Stationeers, Stellaris, Space Engineers.

**Comment by sad-goldfish** [comment]
Running `gamescope -W 1920 -H 1080 -w 3840 -h 2160 -f -- glxgears -fullscreen` again, I see that my monitor reports a framerate of about 65fps but the stdout of `glxgears` reports a framerate of:
`42 frames in 5.0 seconds =  8.388 FPS`

**Comment by Glog78** [comment]
Maybe some hint -> i just played gunlocked while the performance in fullscreen was horrible , the performance in a windowed scalled was fine. Same experience with Death Stranding.

![image](https://user-images.githubusercontent.com/7598856/168164602-e1726a95-5970-4670-a2d2-42f65bd9774b.png)
![image](https://user-images.githubusercontent.com/7598856/168164667-3d943da9-054d-4bad-9198-563773d62c3f.png)

But even in windowed mode the fps in Death Stranding is below what i get with WINE_FULLSCREEN_FSR=1 + Desktop Mode in wine (stable 60 fps).

**Comment by gnusenpai** [comment]
I think it is worth noting that this seems to be heavily CPU-bound for some reason. Everything that I've tried causes the process running in gamescope to use 100% CPU. For reference, `gamescope -W 1920 -H 1080 -w 3840 -h 2160 -f -- glxgears -fullscreen` runs at ~5.5 FPS on 5900x+3080, with glxgears using 100% of 1 CPU thread. I get exactly the same performance playing games like vkQuake with a similar command (~5fps @ 100% CPU).

**Comment by kakra** [comment]
> `gamescope -W 1920 -H 1080 -w 3840 -h 2160 -f -- glxgears -fullscreen`
> On a GTX 1080 glxgears runs at 50fps, well below the monitor framerate. And clearly shows screentearing.

Are you guys sure you wanted to use `-W 1920 -H 1080 -w 3840 -h 2160` instead of `-W 3840 -H 2160 -w 1920 -h 1080`?

The first would run present a resolution of 3840x2160 to the game which may render at a lower resolution, then upscale to 4k (or in this case, glxgears rendering natively to 4k without upscaling), then gamescope downscales that again to FHD, finally upscaling it back to your screen. This sounds very inefficient.

It works fine the other way around, letting gamescope upscale with FSR if you also use `-U`. The lower case resolution letters are what the nested client sees as the resolution.

I still can confirm the tearing issue with nvidia. But in contrast to glxgears, games run at 60 fps instead of 55-57 fps (glxgears, looks jittery). The strange thing is: I didn't even enable vsync. Also, for some reason, running glxgears within gamescope enabled it vertical sync feature unconditionally while it doesn't when running without gamescope.

**Comment by gnusenpai** [comment]
Sure it may not be efficient (I agree that it is a weird test), but it should definitely run better than 5 FPS on high end hardware.. ;p
The point is even doing more sane scaling still results in the same level of performance (i.e. horrible).

**Comment by kakra** [comment]
Ok thanks for clarification. It wasn't pointed out in the first post so I guessed it may confuse people blindly following the example and thinking it would do proper upscaling while it actually is downscaling.

**Comment by sad-goldfish** [comment]
> Are you guys sure you wanted to use `-W 1920 -H 1080 -w 3840 -h 2160` instead of `-W 3840 -H 2160 -w 1920 -h 1080`?
Yes. I wanted to increase the gpu load by rendering it at 4k and downscale to 1080p because, afaik, it's the most common monitor resolution. And rendering glxgears at 4k should not be a problem for a gtx 1080.

**Comment by Diridibindy** [comment]
Can attest to that, running Mordhau with `gamescope -f -- mangohud %command%` yielded a nice 9 fps instead of the usual 200-250 fps on a 1660 ti with the latest drivers

**Comment by ancorehraq** [comment]
The slowdown is caused by nvidia's GBM library in Xwayland failing a PixmapFromBuffers call:

000:<:0026: 64: DRI3-Request(146,7): PixmapFromBuffers pixmap=0x00600006 window=0x00600002 num_buffers=0x01 width=0x012c height=0x012c stride0=0x00000500 offset0=0x00000000 s
tride1=0x00000000 offset1=0x00000000 stride2=0x00000000 offset2=0x00000000 stride3=0x00000000 offset3=0x00000000 depth=0x18 bpp=0x20 modifier1=0x00000000 modifier2=0x00000000
000:>:0026:Error 11=Alloc: major=146, minor=7, bad=0x00600002, seq=0026

and then the nvidia userspace inside glxgears falls back to XPutImage instead of using direct rendering. Transmitting each frame over the X socket causes glxgears to spent most of its time in unix_stream_sendmsg you see in perf traces in https://github.com/Plagman/gamescope/issues/495#issuecomment-1126940607

This doesn't happen under weston or kwin in x11 backend mode for some reason. The only difference I noticed is DRM modifiers declared by Xwayland:

gamescope:
000:<:0023: 12: DRI3-Request(146,6): GetSupportedModifiers window=0x00600002 depth=0x18 bpp=0x20
000:>:0023:88: Reply to GetSupportedModifiers: num_window_modifiers=0x00000000 num_screen_modifiers=0x00000007 modifiers=0x00606015,0x03000000,0x00606014,0x03000000,0x0060601
3,0x03000000,0x00606012,0x03000000,0x00606011,0x03000000,0x00606010,0x03000000,0x00000000,0x00000000;

weston:
000:<:0023: 12: DRI3-Request(146,6): GetSupportedModifiers window=0x00600002 depth=0x18 bpp=0x20
000:>:0023:88: Reply to GetSupportedModifiers: num_window_modifiers=0x00000000 num_screen_modifiers=0x00000007 modifiers=0x00606015,0x03000000,0x00606014,0x03000000,0x0060601
3,0x03000000,0x00606012,0x03000000,0x00606011,0x03000000,0x00606010,0x03000000,0x00000000,0x00000000;

Under weston, glxgears requests modifier 0x0300000000e08014 which isn't present under gamescope.


@cubanismo please help!

**Comment by gnusenpai** [comment]
> This doesn't happen under weston or kwin in x11 backend mode for some reason.

I gave kwin on X11 a try, but it didn't change anything for me.

**Comment by pchome** [comment]
BTW, Zink actually works, but not changing much regarding performance. Also, AFAIKT, all tearing/flickering/etc. bugs still present. I guess it can be interesting as additional test case (eg. no single CPU core at 100%).
`__GLX_VENDOR_LIBRARY_NAME=mesa MESA_LOADER_DRIVER_OVERRIDE=zink  glxgears`
Tested on mesa-22.1.0_rc5

P.S. off topic
One good thing -- you can use Vulkan layers for OpenGL applications.
Lets say vkBasalt, which is not available for OpenGL, but is a good helper if you want to force additional AA before image will be upscaled (e.g. by FSR).
`gamescope -U -W 1920 -H 1080 -- env __GLX_VENDOR_LIBRARY_NAME=mesa MESA_LOADER_DRIVER_OVERRIDE=zink  VK_ADD_LAYER_PATH="." VK_INSTANCE_LAYERS=VK_LAYER_VKBASALT_post_processing glxgears`
_(for this test I copied libvkbasalt.so, vkBasalt.conf, vkBasalt.json from its build directory into current directory, changed `effects = smaa` in config and `"library_path": "./libvkbasalt.so",` in json)_

**Comment by ancorehraq** [comment]
That's awesome, I get full performance with Zink on Unigine Superposition.

**Comment by cubanismo** [comment]
> Under weston, glxgears requests modifier 0x0300000000e08014 which isn't present under gamescope.

Thanks for tracking down the modifier discrepancy.
From the definition of DRM_FORMAT_MOD_NVIDIA_BLOCK_LINEAR_2D, 0x0300000000e08014 decodes to Kind Generation = 2 (Turing+), PageKind  = 0x8 (Turing compressed). Obviously that isn't supposed to work on a Pascal card, so something's wrong with the modifiers Xwayland is advertising, likely meaning something is wrong with the modifiers it's getting from EGL. I'll take a look.

**Comment by KuKuRuZ1337** [comment]
> BTW, Zink actually works, but not changing much regarding performance.

![изображение](https://user-images.githubusercontent.com/65289168/169043576-eee44ff5-25b8-4942-ab8c-4f65ffa6f645.png)
Mom, I'm not a cheater, I just have nvidia)

**Comment by ppergame** [comment]
> > Under weston, glxgears requests modifier 0x0300000000e08014 which isn't present under gamescope.
> 
> Thanks for tracking down the modifier discrepancy. From the definition of DRM_FORMAT_MOD_NVIDIA_BLOCK_LINEAR_2D, 0x0300000000e08014 decodes to Kind Generation = 2 (Turing+), PageKind = 0x8 (Turing compressed). Obviously that isn't supposed to work on a Pascal card, so something's wrong with the modifiers Xwayland is advertising, likely meaning something is wrong with the modifiers it's getting from EGL. I'll take a look.

Thank you! FWIW I have a 3080 Ti and gamescope's enumeration doesn't include 0x0300000000e08014. Maybe modifier capabilities are different between Vulkan (gamescope) and EGL (weston and Xwayland) in this driver release?

**Comment by cubanismo** [comment]
Quick update: I was able to track down the issue in the driver and write up a fix. I misunderstood the comment above as I assume it was data collected on a Pascal-class GPU. The problem is actually that Vulkan doesn't advertise compressed DRM format modifiers, which means Gamescope doesn't either, which means Xwayland also doesn't when running on Gamescope, which in turn confuses our GLX driver when running on this configuration, as it was expecting both compressed and uncompressed modifiers to be available when running on Xwayland.

Thanks again for the help from the community in debugging this issue.

**Comment by ghtesting2020** [comment]
> Quick update: I was able to track down the issue in the driver and write up a fix. I misunderstood the comment above as I assumed it was data collected on a Pascal-class GPU. The problem is actually that Vulkan doesn't advertise compressed DRM format modifiers, which means Gamescope doesn't either, which means Xwayland also doesn't when running on Gamescope, which in turn confuses our GLX driver when running on this configuration, as it was expecting both compressed and uncompressed modifiers to be available when running on Xwayland.
> 
> Thanks again for the help from the community in debugging this issue.

Thanks @cubanismo, you have no idea how excited I am for this to be fixed. No longer will my monitor resolutions be messed up by retro PC games that only support 640x480. As an Nvidia user, seeing all the AMD folks with Gamescope had me mad jealous. It will be nice to play those retro games in little virtual windows using Gamescope and still being able to use my other stuff when alt+tabbing without being blinded by rainbow graphics or 1000px text.

**Comment by pchome** [comment]
I quick-tested current master branch (b1c3859) and now not only glxgears at 100% but also gamescope at 100% on another core. Output also a bit different:
```
vulkan: selecting physical device 'NVIDIA GeForce GTX 750 Ti': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: The vulkan driver does not support foreign queues, disabling modifier support.
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
```
I googled a bit and I guess from Maxwell cards only Maxwell2 supports ["foreign queues"](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_queue_family_foreign.html#_description) (only on Windows, according to gpuinfo.org). 

<details><summary>VK_EXT_queue_family_foreign</summary>

> This extension defines a special queue family, VK_QUEUE_FAMILY_FOREIGN_EXT, which can be used to transfer ownership of resources backed by external memory to foreign, external queues. This is similar to VK_QUEUE_FAMILY_EXTERNAL_KHR, defined in [VK_KHR_external_memory](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_external_memory.html). The key differences between the two are:
>   * The queues represented by VK_QUEUE_FAMILY_EXTERNAL_KHR must share the same physical device and the same driver version as the current [VkInstance](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstance.html). VK_QUEUE_FAMILY_FOREIGN_EXT has no such restrictions. It can represent devices and drivers from other vendors, and can even represent non-Vulkan-capable devices.
>   * All resources backed by external memory support VK_QUEUE_FAMILY_EXTERNAL_KHR. Support for VK_QUEUE_FAMILY_FOREIGN_EXT is more restrictive.
>   * Applications should expect transitions to/from VK_QUEUE_FAMILY_FOREIGN_EXT to be more expensive than transitions to/from VK_QUEUE_FAMILY_EXTERNAL_KHR.

</details>

I'm not expert, for me it looks like this extension is something for cross-device/cross-vendor. Is it really a requirement now, should I even hope to use gamescope with this GPU?

Out of curiosity I replaced everything related to "foreign queues" with "external_memory" in gamescope's new code and got back to single core at 100% by glxgears.
<details>
<summary>"Get rid of the goat" effect.</summary>

> Danny was living in a small house with five other people, and the stress was getting to him. He went to the town elder to ask for advice.
> "Buy a goat", said the town elder, "and let it live in your apartment. If that doesn't help, come see me again in a month."
> A month later, Danny came back and said "now I've got six people and a goat in my tiny apartment, and I'm more stressed than ever before!"
> "Get rid of the goat", said the town elder.

</details>

**Comment by kodatarule** [comment]
Please check this - https://forums.developer.nvidia.com/t/request-for-gamescope-and-the-vk-ext-image-drm-format-modifier/208614

`Just to close the loop here, the poor performance issue was reproduced and a fix is in the process of being integrated into our driver.` -- it's an nvidia driver issue

**Comment by NoXPhasma** [comment]
Performance seems to be fixed with [515.48.07](https://www.nvidia.com/download/driverResults.aspx/189817/), but now gamescope freezes when going into fullscreen. No matter if with the option `-f` or by using the window manager.

**Comment by Sporif** [comment]
> Performance seems to be fixed with [515.48.07](https://www.nvidia.com/download/driverResults.aspx/189817/), but now gamescope freezes when going into fullscreen. No matter if with the option `-f` or by using the window manager.

Which window manager? I have no fullscreen problems with i3.

**Comment by pchome** [comment]
Earlier I said
> gamescope at 100%

Seems shader compilation, lol. It takes more than ten seconds, but after that everything is ok.
Fullscreen is ok for me on KDE.

**Comment by sad-goldfish** [comment]
When `gamescope` runs, it seems to run with good performance. There seems to be a few games where it does not run though e.g. Gwent, Apex Legends. Closing this because the performance issue seems to be fixed.

Although current HEAD does not work at all for me. I am using e4892543a04637aa32dfac336762c22cfff880db

**Comment by Bananaman** [comment]
@sad-goldfish 

> Although current HEAD does not work at all for me. I am using [e489254](https://github.com/Plagman/gamescope/commit/e4892543a04637aa32dfac336762c22cfff880db)

Hi.

I tried today with the following:

- NVIDIA driver 515.57
- gamescope version: latest git as of July 7th, 2022 - [1b3ad77](https://github.com/Plagman/gamescope/commit/1b3ad771817bc3e7e68c53fb26c3da889f9ddd12)
- Command: `gamescope -r 30 -- vkcube`

Result:

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'NVIDIA GeForce RTX 3090': queue family 2
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan: physical device queue doesn't support presenting on our surface
vulkan_make_output failed
[1]    222469 segmentation fault (core dumped)  gamescope -r 30 -- vkcube
```

There's a long ticket where people mention the same error:

https://github.com/Plagman/gamescope/issues/497

My question is if you see the same error on the latest GIT version of gamescope? Trying to determine if the hassle of building an older commit has a chance of fixing it for me.

**Comment by Bananaman** [comment]
Right, I build the commit that worked for you ([e489254](https://github.com/Plagman/gamescope/commit/e4892543a04637aa32dfac336762c22cfff880db))...

Result with that commit is almost identical to latest master:

```
$ build/gamescope -r 30 -- vkcube
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'NVIDIA GeForce RTX 3090'
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan: physical device queue doesn't support presenting on our surface
vulkan_make_output failed
[1]    357082 segmentation fault (core dumped)  build/gamescope -r 30 -- vkcube
```

So unfortunately that was a waste of time. :(

**Comment by cubanismo** [comment]
Aside from this being completely unrelated to this issue, do you by chance have DISPLAY or WAYLAND_DISPLAY set in your environment?

**Comment by Bananaman** [comment]
> Aside from this being completely unrelated to this issue, do you by chance have DISPLAY or WAYLAND_DISPLAY set in your environment?

```
 ~ echo $DISPLAY
:0
 ~ echo $WAYLAND_DISPLAY
wayland-0
```
