### ISSUE TITLE
Window never opens on NVIDIA beta 515.43

### ISSUE THREAD

**Issue by Techwizz-somboo** [Plagman/gamescope#493]
Hi,
The window for the app never opens with Gamescope. In this case it was glxgears. Thanks!
[video](https://www.youtube.com/watch?v=u4DIfcFsAnA)
[log.txt](https://github.com/Plagman/gamescope/files/8683396/log.txt)

Graphics card: RTX 2070
NVIDIA version: 515.43.04
Gamescope version: current master, around 3.11.31-beta4
Distribution: Holoiso, based on SteamOS 3.0

**Comment by NoXPhasma** [comment]
Make sure you have set this Kernel parameter and reboot: `nvidia-drm.modeset=1`

**Comment by Techwizz-somboo** [comment]
That fixed it. Thanks again!
