### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by GFOXSH** [Plagman/gamescope#525]
Good afternoon! What about external keyboard support? When will it be possible to open the overlay without a joystick? Or add new layouts for input? Or hide the on-screen keyboard?

**Comment by parkerlreed** [comment]
Would this not be directed at https://github.com/ValveSoftware/SteamOS/issues ?

gamescope itself is mainly for getting the game's visuals to your screen, rather than handling input method on the Steam Deck.

**Comment by GFOXSH** [comment]
Sorry, I was wrong. Thank you!
