### ISSUE TITLE
Failed to initialize Vulkan on RX 6700 XT

### ISSUE THREAD

**Issue by gibsonjareds** [Plagman/gamescope#529]
Hello all!

Let me start off with saying that I am aware of [this issue](https://github.com/Plagman/gamescope/issues/447). My configuration seems to match their working configuration so I'm not sure where to go.

Here's my system info as requested in the other thread: 
```
libdrm 2.4.110-1
lib32-libdrm 2.4.110-1
linux 5.17.9.arch1-1
mesa 22.1.0-1
vulkan-radeon 22.1.0-1
```
and here's the output if I run `gamescope` on its own:
```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'AMD Radeon RX 6700 XT'
vulkan: physical device does not support DRM format modifiers
vulkan: vkAllocateDescriptorSets failed
Failed to initialize Vulkan
[1]    63021 segmentation fault (core dumped)  gamescope
```

Is there something I'm missing? Thanks for any help.

**Comment by parkerlreed** [comment]
Don't use AMDVLK. Same crash when using AMDVLK on RX 480

RADV works perfectly fine.

**Comment by parkerlreed** [comment]
If amdvlk isn't installed, check `/usr/share/vulkan/icd.d/` to make sure the file isn't lingering.

Same for lib32

**Comment by gibsonjareds** [comment]
Damn I did not remember installing that. I thought it and vulkan-radeon conflicted so that one would uninstall the other. Uninstalled AMDVLK manually and it worked.

**Comment by parkerlreed** [comment]
Yeah that's the beauty of ICD layers and Vulkan. You can use the proprietary driver on top of the open source stack so whichever one loads first just works. Same reason you can have both AMD and Intel on one laptop and just tell it to use one of the files.
