### ISSUE TITLE
trying to build gamescope on pop os 22

### ISSUE THREAD

**Issue by givname** [Plagman/gamescope#532]
/gamescope-3.11.31-beta8$ meson build/
The Meson build system
Version: 0.61.2
Source dir: /home/usr/Programme/gamescope-3.11.31-beta8
Build dir: /home/usr/Programme/gamescope-3.11.31-beta8/build
Build type: native build
Project name: gamescope
Project version: undefined
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.2.0 "c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency x11 found: YES 1.7.5
Run-time dependency xdamage found: YES 1.1.5
Run-time dependency xcomposite found: YES 0.4.5
Run-time dependency xrender found: YES 0.9.10
Run-time dependency xext found: YES 1.3.4
Run-time dependency xfixes found: YES 6.0.0
Run-time dependency xxf86vm found: YES 1.1.4
Run-time dependency xtst found: YES 1.2.3
Run-time dependency xres found: YES 1.2.1
Run-time dependency libdrm found: YES 2.4.110
Run-time dependency vulkan found: YES 1.3.204
Run-time dependency wayland-server found: YES 1.20.0
Run-time dependency wayland-protocols found: YES 1.25
Run-time dependency xkbcommon found: YES 1.4.0
Run-time dependency threads found: YES
Run-time dependency libcap found: YES 2.44
Run-time dependency sdl2 found: YES 2.0.20
Run-time dependency libpipewire-0.3 found: YES 0.3.52
Library rt found: YES
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency stb found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency stb
﻿
Executing subproject stb 
﻿
stb| Project name: stb
stb| Project version: 0.1.0
stb| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
stb| C linker for the host machine: cc ld.bfd 2.38
stb| Build targets in project: 0
stb| Subproject stb finished.
﻿
Dependency stb found: YES 0.1.0 (overridden)
Looking for a fallback subproject for the dependency wlroots because:
Use of fallback dependencies is forced.
﻿
meson.build:50:0: ERROR: Subproject exists but has no meson.build file
﻿
ninja -C build/
ninja: Entering directory `build/'
ninja: error: loading 'build.ninja': No such file or directory

libs used
sudo apt install meson cmake libx11-dev libxdamage-dev libxcomposite-dev libxrender-dev libxxf86vm-dev libxtst-dev libxres-dev libdrm-dev libvulkan-dev libwayland-dev wayland-protocols libxkbcommon-dev libcap-dev libsdl2-dev libpipewire-0.3-dev

any hints?

**Comment by KaiserCalm** [comment]
Hey, I tried doing this recently, so I'm gonna type out what I can remember that I did. The way I did it was to keep trying to compile it and then download the packages that seemed to be missing by looking them up on https://packages.ubuntu.com/ then typing in the console `sudo apt install (package name)` go for the versions that have _dev in them, also you need to download the latest versions of https://gitlab.freedesktop.org/emersion/libliftoff/ and https://gitlab.freedesktop.org/wlroots/wlroots/ and put the repository files into their empty folders in the subprojects folders and then install their dependencies by trying to compile gamescope again and once again looking the missing ones up on https://packages.ubuntu. I hope I could help.

**Comment by givname** [comment]
Hi there, thanks for the tip now i hang on this one:
wlroots| Run-time dependency libseat found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency libseat

subprojects/wlroots/backend/session/meson.build:1:0: ERROR: Neither a subproject directory nor a seatd.wrap file was found.
i installed libseat-dev but it doesnt solve the issue.

**Comment by KaiserCalm** [comment]
Have you installed libwlroots-dev? If not try that one.

**Comment by givname** [comment]
tyvm now im stuck with this
Dependency wlroots found: NO found 0.16.0-dev but need: '>= 0.15.0', '< 0.16.0' (overridden)

meson.build:50:0: ERROR: Dependency 'wlroots' is required but not found.
i tried all major gs versions (even the one im using via ppa)

**Comment by KaiserCalm** [comment]
Could I get more of the terminal output, to see where this is happening?

**Comment by givname** [comment]
Build type: native build
Project name: gamescope
Project version: undefined
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.2.0 "c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency x11 found: YES 1.7.5
Run-time dependency xdamage found: YES 1.1.5
Run-time dependency xcomposite found: YES 0.4.5
Run-time dependency xrender found: YES 0.9.10
Run-time dependency xext found: YES 1.3.4
Run-time dependency xfixes found: YES 6.0.0
Run-time dependency xxf86vm found: YES 1.1.4
Run-time dependency xtst found: YES 1.2.3
Run-time dependency xres found: YES 1.2.1
Run-time dependency libdrm found: YES 2.4.110
Run-time dependency vulkan found: YES 1.3.204
Run-time dependency wayland-server found: YES 1.20.0
Run-time dependency wayland-protocols found: YES 1.25
Run-time dependency xkbcommon found: YES 1.4.0
Run-time dependency threads found: YES
Run-time dependency libcap found: YES 2.44
Run-time dependency sdl2 found: YES 2.0.20
Run-time dependency libpipewire-0.3 found: YES 0.3.52
Library rt found: YES
Run-time dependency stb found: YES 0.0
Looking for a fallback subproject for the dependency wlroots because:
Use of fallback dependencies is forced.

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.16.0-dev
wlroots| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
wlroots| C linker for the host machine: cc ld.bfd 2.38
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Dependency wayland-server found: YES 1.20.0 (cached)
wlroots| Dependency libdrm found: YES 2.4.110 (cached)
wlroots| Dependency xkbcommon found: YES 1.4.0 (cached)
wlroots| Run-time dependency libudev found: YES 249
wlroots| Run-time dependency pixman-1 found: YES 0.40.0
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Dependency wayland-protocols found: YES 1.25 (cached)
wlroots| Found pkg-config: /usr/bin/pkg-config (0.29.2)
wlroots| Build-time dependency wayland-scanner found: YES 1.20.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Dependency pixman-1 found: YES 0.40.0 (cached)
wlroots| Run-time dependency gbm found: YES 22.0.1
wlroots| Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES
wlroots| Run-time dependency libinput found: YES 1.20.0
wlroots| Run-time dependency wayland-client found: YES 1.20.0
wlroots| Run-time dependency libseat found: YES 0.6.4
wlroots| Found CMake: /usr/bin/cmake (3.22.1)
wlroots| Run-time dependency xwayland found: NO (tried pkgconfig and cmake)
wlroots| Program Xwayland found: YES (/usr/bin/Xwayland)
wlroots| Run-time dependency xcb found: YES 1.14
wlroots| Run-time dependency xcb-composite found: YES 1.14
wlroots| Run-time dependency xcb-icccm found: YES 0.4.1
wlroots| Run-time dependency xcb-render found: YES 1.14
wlroots| Run-time dependency xcb-res found: YES 1.14
wlroots| Run-time dependency xcb-xfixes found: YES 1.14
wlroots| Run-time dependency xcb-errors found: NO (tried pkgconfig and cmake)
wlroots| Message: Required for printing X11 errors.
wlroots| Message: Required for printing X11 errors.
wlroots| Checking for function "xcb_xfixes_set_client_disconnect_mode" with dependencies xcb, xcb-composite, xcb-icccm, xcb-render, xcb-res, xcb-xfixes, xcb-errors: NO
wlroots| Configuring config.h using configuration
wlroots| Configuring version.h using configuration
wlroots| Configuring config.h using configuration
wlroots| Build targets in project: 106
wlroots| Subproject wlroots finished.

Dependency wlroots found: NO found 0.16.0-dev but need: '>= 0.15.0', '< 0.16.0' (overridden)

meson.build:50:0: ERROR: Dependency 'wlroots' is required but not found.

**Comment by givname** [comment]
found the error, i pulled wlroots and libliftoff master instead of tagged versions, im still wondering about this:
wlroots 0.15.1

    drm-backend     : NO
    x11-backend     : NO
    libinput-backend: YES
    xwayland        : YES
    gles2-renderer  : NO
    vulkan-renderer : NO
    xcb-errors      : NO

when trying this step 'build/gamescope -- <game>' i get a syntax error nor do i understand its meaning

**Comment by givname** [comment]
i was able to install it in the end but its not working very well. now i wonder if can just install another version over it or how can i remove it (using meson uninstall didnt work)

**Comment by tartley** [comment]
I'm also trying this, but not having success yet. Wondering whether it would be useful to add a text documentation of this, or to keep an issue updated with the latest known-good process. My own status:

I'm on Pop!OS 22.04. It is 2022/12/23. I'm running nvidia v525.60.11, on a laptop 3060.

1. Install build tools:

```
sudu apt install meson cmake ninja-build
```

2. Dependency 'libdrm' needs manual compilation on, since 'apt' does not provide a new enough version:

      Dependency libdrm found: NO. Found 2.4.110 but need: '>= 2.4.113'

To compile & install from source:

```
cd .. # ie not in the gamescope tree
git clone git@github.com:freedesktop/mesa-drm.git
cd mesa-drm
git checkout main # not master
meson builddir/
ninja -C builddir/ install
```

3. Dependency 'wayland-server' requires manual compile, since 'apt' does not provide new enough version:

        Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'

I personally noped out here. Will compiling my own Wayland end well?

4. Apart from the above, I was having success running `meson builddir/` and searching for the required dependencies [here](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=libdrm&searchon=names), yielding this list:

`sudo apt install libx11-dev libxdamage-dev libxcomposite-dev libxrender-dev libxxf86vm-dev libxtst-dev libxres-dev libvulkan-dev libwayland-dev libwayland-server0`

**Comment by Ambient-Impact** [comment]
@tartley I'm also on Pop!_OS 22.04 LTS; the `sudo apt install` list helped fix a bunch of the compile errors but I also had to `sudo apt install wayland-protocols`, but it's probably too old and results in:

> protocol/meson.build:41:1: ERROR: File //usr/share/wayland-protocols/stable/linux-dmabuf/linux-dmabuf-v1.xml does not exist.

We'll probably have to wait for the upcoming Pop!_OS 24.04 LTS to get this working, unless someone more clever than I has some ideas.
