### ISSUE TITLE
Gamescope and Intel XE graphics

### ISSUE THREAD

**Issue by nex86** [Plagman/gamescope#550]
does it currently work? or is there any other steps involved to get it working?

**Comment by euclidaze** [comment]
It doesn'work，there only work for X11

**Comment by ruineka** [comment]
> does it currently work? or is there any other steps involved to get it working?

An older version of gamescope will work. https://github.com/plagman/gamescope/commit/861435aebae39db1bf3caf552e9fff221b7d3424

**Comment by ruineka** [comment]
The fix for this hasn't been merged into mesa-git so this has not been "fixed" yet. Holoiso simply took the branch with the fix and bundled it with the install independent from the upstream mesa.

Even with the patch issues remain where when you move the cursor the screen goes black.

**Comment by Samsagax** [comment]
I can confirm the issue still persists. Gamescope can't run embedded on Intel.
