### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by 4e554c4c** [Plagman/gamescope#551]
I have a HiDPI screen, with 2x scaling. Because of this, gamescope windows show up in half the resolution they should.

This would be a very useful feature, because it would effectively allow one to use X applications with native DPI in gamescope, while also allowing an ordinary 2x scaling for wayland clients.

**Comment by bblacher** [comment]
Would love to see this implemented as well :)

**Comment by MatthiasGrandl** [comment]
@lolzballs I see this is closed, but on gamescope-git nested in Hyprland with 2x scaling I still get a lot of bluriness. Do I need to set any specific arguments for this to work as expected? Currently I am launching gamescope like this:

```
gamescope -f -e -w 3840 -W 3840 -H 2160 -h 2160 -r 120 -- steam -steamos -tenfoot -fulldesktopres -nointro 
```

**Comment by 4e554c4c** [comment]
@MatthiasGrandl this is the follow up issue https://github.com/Plagman/gamescope/issues/796

**Comment by stacyharper** [comment]
I still can't pick a higher resolution than my logical one. With a 2x scaling value, I should be able to `-w 1920 -h 1080`, and the game should render exactly the same as if the scaling was 1. At the moment, we don't even list the 1920x1080 option, and can't force it.

**Comment by stacyharper** [comment]
as of today, it seems to be solved
