### ISSUE TITLE
Games not launching since latest commit

### ISSUE THREAD

**Issue by italoghost** [Plagman/gamescope#553]
Hi!

I have installed gamescope through the gamescope-git package from AUR and since the latest commit, no game would launch with gamescope. I tested both on Steam and Lutris.

**Comment by grimshins** [comment]
This happens for me as well. Compiled successfully, but games won't run through it. Compiled and tested 3.11.33-beta1 successfully afterward.

**Comment by Joshua-Ashton** [comment]
https://github.com/Plagman/gamescope/pull/554 should fix

**Comment by writequit** [comment]
Still broken here on current git:
$ gamescope glxgears
vulkan: selecting physical device 'AMD RADV SIENNA_CICHLID': queue family 1
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
gamescope: backend/multi/backend.c:192: wlr_multi_backend_add: Assertion `_multi && backend' failed.

**Comment by writequit** [comment]
1b34a570a51d0a65451d1f2a990487add8cde40a works ok.

**Comment by arzeth** [comment]
> #554 should fix

Resolved the issue for me too. NVIDIA 515.49.06, Arch Linux [testing] [chaotic-aur], i3 WM, `gamescope -b -f -w 1472 -h 828  -r 75 -o 4 -W 1920 -H 1080 -U --fsr-sharpness 8`
