### ISSUE TITLE
Error opening directory '/sys/class/drm/card0-HDMI-A-1/device/hwmon

### ISSUE THREAD

**Issue by starduxt** [Plagman/gamescope#564]
OS: Debian testing/bookworm(upcoming Debian stable). OS is latest updated.
GPU: RX 5700 XT.
Mesa 22.0.5.
Monitor: 21.5" 1080p connected via HDMI.
DE: Gnome + Wayland + gdm

I am getting following error inside terminal upon launching any game from Wine. All Steam games appears to be crashing (i mean not starting at all) as well if I use gamescope. 

```
vulkan: selecting physical device 'AMD RADV NAVI10': queue family 1
vulkan: physical device supports DRM format modifiers
[2022-07-26 14:40:33.856] [MANGOHUD] [error] [file_utils.cpp:43] Error opening directory '/sys/class/drm/card0-HDMI-A-1/device/hwmon/': No such file or directory
[2022-07-26 14:40:33.856] [MANGOHUD] [error] [file_utils.cpp:43] Error opening directory '/sys/class/drm/card0-DP-2/device/hwmon/': No such file or directory
[2022-07-26 14:40:33.857] [MANGOHUD] [info] [overlay.cpp:718] Uploading is disabled (permit_upload = 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
Segmentation fault
```

[ Speculation from my side ]: Following info may help you.
(1). The directory that Gamescope is trying to look inside "/sys/class/drm/card0-HDMI-A-1/device/hwmon/" doesn't contain information about my GPU at all.

Following seems to be the correct directory for my GPU:
/sys/class/drm/card0/device/hwmon/hwmon2
That contains following files and I have check parameters like power cap etc, everything is showing from the RX 5700 XT settings:
```
freq2_label	 pwm1		  temp2_crit_hyst
..	     in0_input		 pwm1_enable	  temp2_emergency
device	     in0_label		 pwm1_max	  temp2_input
fan1_enable  name		 pwm1_min	  temp2_label
fan1_input   power		 subsystem	  temp3_crit
fan1_max     power1_average	 temp1_crit	  temp3_crit_hyst
fan1_min     power1_cap		 temp1_crit_hyst  temp3_emergency
fan1_target  power1_cap_default  temp1_emergency  temp3_input
freq1_input  power1_cap_max	 temp1_input	  temp3_label
freq1_label  power1_cap_min	 temp1_label	  uevent
freq2_input  power1_label	 temp2_crit
```

(2). xrandr --props shows my monitor is connected on XWAYLAND0. On Xorg + XFCE + lightdm, I used to see HDMI-0, DP-0 something. This XWAYLAND0 is the first time I am seeing.
result of "xrandr --props":
```
Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
XWAYLAND0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 480mm x 270mm
	RANDR Emulation: 1 
	non-desktop: 0 
		supported: 0, 1
   1920x1080     74.91*+
   1440x1080     74.92  
   1400x1050     74.87  
   1280x1024     74.90
```

PS. I am very noob on github, this is the first time I am posting something here on this site. Pardon me if I did something wrong.

**Comment by starduxt** [comment]
Update: 
My apologies, the first part of error is from mangohud that has probably nothing to do with this context.

Following is the main error I believe:
```
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
Segmentation fault
```

**Comment by Samsagax** [comment]
Do you have mangohud enabled? If that's the case, disable it. Gamescope doesn't work with mangohud. There is a special binary for it (mangoapp) to work with gamescope.

**Comment by starduxt** [comment]
Ah thank you for that. Yes I have it enabled globally. That should be the issue I am facing.

**Comment by starduxt** [comment]
Issue resolved.
