### ISSUE TITLE
wlserver_set_xwayland_server_mode sets no mode to X now

### ISSUE THREAD

**Issue by Joshua-Ashton** [Plagman/gamescope#571]
Sometimes when we call wlserver_set_xwayland_server_mode to try to get the first xwayland server to resize to the output size, we never find any resources that match the client of the xserver so it never gets updated.

`if ( wl_resource_get_client( resource ) == client )` always returns false.
Seems to persist across a instance of running gamescope. We either end up doing it every time or never.

I am not sure why yet. Maybe @emersion would have an idea?

**Comment by Joshua-Ashton** [comment]
Nvm, this is actually 100% consistent if you plug in after... Wonder if it's related to us setting the output info and calling `	wlr_output_create_global(wlserver.wlr.output);` now or whatever.

**Comment by Joshua-Ashton** [comment]
Commenting out the `wlserver_set_output_info` in `drm.cpp` fixes it.

Not sure how to properly fix it though and retain the property updating.

**Comment by Joshua-Ashton** [comment]
Yeah this makes sense, `wlr_output_destroy_global` does this:
```
	// Make all output resources inert
	struct wl_resource *resource, *tmp;
	wl_resource_for_each_safe(resource, tmp, &output->resources) {
		wl_resource_set_user_data(resource, NULL);
		wl_list_remove(wl_resource_get_link(resource));
		wl_list_init(wl_resource_get_link(resource));
	}
```

**Comment by emersion** [comment]
Hm. Maybe we can install a global filter and create one `wl_output` global per Xwayland, instead of sending fake events?
