### ISSUE TITLE
No game screen but it runs in background

### ISSUE THREAD

**Issue by DocMAX** [Plagman/gamescope#584]
What could be the problem if i can hear the game but just see the Steam logo? I can see in the log:
```
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x56435b385c70 (res 0x56435b305850)
xwm: error 3: BadWindow (invalid Window parameter) request 18 minor 0 serial 80086
xwm: error 3: BadWindow (invalid Window parameter) request 42 minor 0 serial 80087
xwm: error 3: BadWindow (invalid Window parameter) request 12 minor 0 serial 80098
xwm: error 3: BadWindow (invalid Window parameter) request 12 minor 0 serial 80099
xwm: error 3: BadWindow (invalid Window parameter) request 15 minor 0 serial 80100

```

**Comment by DocMAX** [comment]
I think i fixed this i don't know how.

**Comment by lemonzest79** [comment]
I'm having this issue myself, it used to work a few days ago when I last tried but now even a simple "gamescope glxgears" does not display an image, I'm using Fedora 36 GNOME with glorious eggrolls gamescope (it does not work with fedoras either, I tested) using mesa git, but also tried mesa 22.1.7 with no luck.

wlserver: [backend/headless/backend.c:82] Creating headless backend
vulkan: selecting physical device 'AMD Radeon RX 6600 XT (RADV NAVI23)': queue family 1
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/server.c:92] Starting Xwayland on :2
dri_create_context: requested glthread but driver is missing backgroundCallable V2 extension
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86EmojiPicker
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55955065be50 (res 0x55954ff40d80)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 101
pipewire: renegotiating stream params (size: 1280x720)
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x5595506dd6f0 (res 0x5595501ffcf0)
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
