### ISSUE TITLE
gamescope-session doesn't run on tty

### ISSUE THREAD

**Issue by manmbalu** [Plagman/gamescope#585]
Hi, I'm tryna make gamescope working at startup on an old HD 7850. I've alredy switched from radeon driver to amdgpu driver. If i try to start gamescope-session under a wm, it starts windowed without problem. If i try to login to gamescope session from sddm, I've black screen, and then goes back to login. If I try to run it on tty, I get this output:
```
ATTENTION: default value of option vk_xwayland_wait_ready overridden by enviroment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: selecting physical device 'AMD RADV PITCAIRN'
vulkan: physical device does not support DRM format modifiers
drm: opening DRM node '/dev/dri/card0'
drm: drmSetClientCap(ATOMIC) failed
Failed to initialize output
```

**Comment by Joshua-Ashton** [comment]
Gamescope embedded needs modifiers like the log says. There is no support for DRM modifiers on that card atm.
