### ISSUE TITLE
Update documentation for gamecope.

### ISSUE THREAD

**Issue by ruineka** [Plagman/gamescope#588]
I'm seeing that there have been a lot of functions added to gamescope which I feel should be added to the possible options on the Github page with a brief explanation of the usage.

A few examples..
-O output device
-R
--prefer-vk-device
-T

and if possible things like $stats and $sockets being explained for people looking to use sessions. It would appear that $stats is what allows projection to the external monitor when you hook up a device.

This was pulled from the Steam Deck:
`gamescope \
	--generate-drm-mode fixed \
	--xwayland-count 2 \
	-w 1280 -h 800 \
	--default-touch-mode 4 \
	--hide-cursor-delay 3000 \
	--max-scale 2 \
	--fade-out-duration 200 \
	-e -R "$socket" -T "$stats" \
	-O '*',eDP-1 \
	--cursor-hotspot 5,3 --cursor /usr/share/steamos/steamos-cursor.png \`

**Comment by emersion** [comment]
`gamescope --help` has complete docs. The README just lists a few, by design: keeping all docs in sync is tedious.

**Comment by ruineka** [comment]
> `gamescope --help` has complete docs. The README just lists a few, by design: keeping all docs in sync is tedious.

Fair enough. :)
