### ISSUE TITLE
Pacman conflicting files (libliftoff)

### ISSUE THREAD

**Issue by KawaiiDinosaur** [Plagman/gamescope#590]
I'm trying to install gamescope in my Arch system via pacman but `sudo pacman -S gamescope` gives me the following error

```
error: failed to commit transaction (conflicting files)
/usr/include/libliftoff.h existe tanto em "libliftoff" como em "gamescope"
/usr/lib/pkgconfig/libliftoff.pc existe tanto em "libliftoff" como em "gamescope" 
Errors occurred, no packages were upgraded.
```

**Comment by Joshua-Ashton** [comment]
Sounds like your gamescope package is installing libliftoff too, maybe take that up with the maintainers of the package.

Could be something wrong in our script too! Because we shouldn't be shipping libliftoff headers anyway.

**Comment by KawaiiDinosaur** [comment]
`pacman -Si gamescope` lists only **libliftoff.so** as a dependecy. I can't tell why it's trying to install libliftoff.h and libliftoff.pc.

**Comment by PickMeNow** [comment]
Having the exact same issue:

error: failed to commit transaction (conflicting files)
/usr/include/libliftoff.h exists in both 'libliftoff' and 'gamescope'
/usr/lib/pkgconfig/libliftoff.pc exists in both 'libliftoff' and 'gamescope'
Errors occurred, no packages were upgraded.



Depends On      : gcc-libs  glibc  libcap.so=2-64  libdrm  libliftoff.so  libpipewire-0.3.so=0-64
                  libvulkan.so=1-64  libwlroots.so=10-64  libx11  libxcomposite  libxdamage  libxext
                  libxfixes  libxkbcommon.so=0-64  libxrender  libxres  libxtst  libxxf86vm  sdl2
                  vulkan-icd-loader  wayland  wayland-protocols  wlroots  xorg-server-xwayland

**Comment by Scrumplex** [comment]
Someome already opened a ticket in the Arch Linux bug tracker: https://bugs.archlinux.org/task/75631

**Comment by Samsagax** [comment]
This issue should be closed as it is a packager's responsibility to fix.
