### ISSUE TITLE
Issue with latest SDL2 2.0.24

### ISSUE THREAD

**Issue by lemonzest79** [Plagman/gamescope#592]
Hiya

Have had an issue the past few days of gamescope not working on Fedora 36 GNOME Wayland session, a person on the fedora discord pointed me to https://github.com/Plagman/gamescope/issues/543#issue-1294502074 and after adding SDL_VIDEODRIVER=x11 to my wrapper script it worked again, so just a heads up really.

**Comment by emersion** [comment]
Nothing we can do about this, sorry. gamescope only supports X11 clients right now. Forcing Wayland via the env will break clients.
