### ISSUE TITLE
Implement vt-switching in the embedded case

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#6]
Looks easy, get xkb_keysym_t from input, then if it XKB_KEY_XF86Switch_VT_* call wlr_session_change_vt(). xkb handles the Ctrl-Alt-F* chording for us.

**Comment by Plagman** [comment]
@emersion I think I saw a change from you to that effect in the backlog - has that been tested successfully in embedded?

**Comment by emersion** [comment]
https://github.com/Plagman/gamescope/commit/dced8a88da9888a9a65ddcbae2707b55f7899c5f does perform the switch, however it doesn't properly pause the DRM device (ie. gamescope still incorrectly submits buffers).

The current situation is just enough to switch to another VT and kill gamescope, but last time I tried I couldn't switch to another graphical session.
