### ISSUE TITLE
Dependency x11 not found

### ISSUE THREAD

**Issue by KiingWatermelon** [Plagman/gamescope#600]
im trying to compile the source code but i get this error

`The Meson build system
Version: 0.61.2
Source dir: /home/kiing/gamescope
Build dir: /home/kiing/gamescope/build
Build type: native build
Project name: gamescope
Project version: undefined
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.2.0 "c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency x11 found: NO (tried pkgconfig and cmake)

meson.build:27:0: ERROR: Dependency "x11" not found, tried pkgconfig and cmake

A full log can be found at /home/kiing/gamescope/build/meson-logs/meson-log.txt
`

I'm using linux mint (venessa i think [the latest one]) and i double checked that x11 and even wayland and xwayland were installed but it didn't fix it

[meson-log.txt](https://github.com/Plagman/gamescope/files/9425795/meson-log.txt)

**Comment by eli-schwartz** [comment]
> i double checked that x11 and even wayland and xwayland were installed but it didn't fix it

Which packages did you check to see if they are installed?

Since you are using a Debian-like distro, you cannot just check to see if libx11 is installed, you need to see if the "-dev" package is installed, which contains the build dependencies such as headers, library symlinks, and pkg-config files.

**Comment by KiingWatermelon** [comment]
thanks. this worked

**Comment by Milor123** [comment]
> > i double checked that x11 and even wayland and xwayland were installed but it didn't fix it
> 
> Which packages did you check to see if they are installed?
> 
> Since you are using a Debian-like distro, you cannot just check to see if libx11 is installed, you need to see if the "-dev" package is installed, which contains the build dependencies such as headers, library symlinks, and pkg-config files.

Thanks bro! for my ubuntu is:
```sudo apt install libx11-xcb-dev```

**Comment by epeay** [comment]
To supplement and further document the fix.
Building from tag 3.16.4 on Ubuntu 24.04.2 LTS

```
Dependency vkroots found: YES undefined (overridden)
Run-time dependency xcb found: YES 1.15
Run-time dependency x11-xcb found: NO (tried pkgconfig and cmake)

layer/meson.build:3:14: ERROR: Dependency "x11-xcb" not found, tried pkgconfig and cmake
```

This does do the trick, as noted above. There's more build errors later, but it clears this one at least.
`sudo apt install libx11-xcb-dev`
