### ISSUE TITLE
Req: Add option to set environment variables

### ISSUE THREAD

**Issue by xiota** [Plagman/gamescope#601]
Gamescope crashes when I run it with:

    MESA_LOADER_DRIVER_OVERRIDE=zink gamescope -- game_exec

However, If I add the environment variable in a subshell, gamescope runs fine:

    gamescope -- sh -c "MESA_LOADER_DRIVER_OVERRIDE=zink game_exec"

It would be nice if there were an option to apply environment variables only to the game process.  Something like:

    gamescope -E "MESA_LOADER_DRIVER_OVERRIDE=zink,INTEL_DEBUG=noccs" --  game_exec

**Comment by pchome** [comment]
`$ man env`

**Comment by xiota** [comment]
@pchome I don't see your point.  Are you saying use `env` instead of `sh`?  The problem and request are still the same.  It would be convenient if Gamescope could set environment variables via a command line option to affect only the game and not itself.  Gamescope already sets various environment variables.

**Comment by pchome** [comment]
> The problem

This is not a problem, IMHO, this is users not understand how such sings work. And gamescope manipulates some variables because of this. So yes, place layers/driver/etc env vars directly BEFORE `game_exec` if your target is a game. Do not do something like "what a cool metrics overlay, let's enable it globally" shit.

**Comment by xiota** [comment]
> place layers/driver/etc env vars directly BEFORE `game_exec`

This does not work:

    gamescope -- INTEL_DEBUG=noccs glxgears

These do, but they run an extra process that is unnecessary if Gamescope can set the environment directly, which it already does internally for some variables:

    gamescope -- env INTEL_DEBUG=noccs glxgears
    gamescope -- sh -c "INTEL_DEBUG=noccs glxgears"
