### ISSUE TITLE
Stuck in "performing first time setup"

### ISSUE THREAD

**Issue by emersion** [Plagman/gamescope#62]
1. Install Mirror's Edge
2. Run it from the first time in the embedded session
3. Installer is stuck on "performing first time setup"

The first time setup actually installs NVIDIA PhysX, which requires user interaction to accept the license. The embedded session doesn't show the license window and gets stuck forever.

**Comment by Plagman** [comment]
My recent changes around obeying the normal X stacking order while out-of-game should fix that in theory.
