### ISSUE TITLE
Gamescope fails to run on the 6.0+ kernel

### ISSUE THREAD

**Issue by ruineka** [Plagman/gamescope#624]
What previously worked with the 5.19 kernel or older no longer works on kernel 6.0. Using `gamescope -- steam` results in an assert error. The same thing happens when trying to use gamescope-session to boot the "Steam Deck" experience like I've been doing for nearly a year now.

Steam running from the desktop works fine.
[gamescope-stdout.log](https://github.com/ValveSoftware/steam-for-linux/files/9583846/gamescope-stdout.log)
[steam-stdout.log](https://github.com/ValveSoftware/steam-for-linux/files/9583847/steam-stdout.log)

I originally opened a ticket for Steam itself, but I was directed here:
https://github.com/ValveSoftware/steam-for-linux/issues/8803#event-7402980486
Steps for reproducing this issue:

    Update to the 6.0 kernel
    Attempt to launch Steam using gamescope from the TTY.
    Observe how this crashes with an assert

**Comment by ruineka** [comment]
I did some testing on other devices and with two desktops using dGPUs (6700 Xt/6900 XT) it was fine. I also tested using my laptop with Radeon 680M graphics and it was also fine.

The device that suddenly broke compatibility was a OneXplayer Mini with the Ryzen 7 5800U.
Anyone else with 5000 series APUs able to test to see if gamescope broke for them using the 6.0 kernel? I'd try my Aya Neo, but it stopped working on me.

**Comment by Joshua-Ashton** [comment]
`xwm: We failed our modeset and have no mode to fall back to! (Initial modeset failed?): Invalid argument`

Do other wayland sessions work?

**Comment by ruineka** [comment]
Tested 6.0-RC7 and same thing occurs.

Here is a coredump.

[core.gamescope.1000.23cd956f6aa94aac9dd610f083b7866b.3868.zip](https://github.com/Plagman/gamescope/files/9642389/core.gamescope.1000.23cd956f6aa94aac9dd610f083b7866b.3868.zip)

**Comment by ruineka** [comment]
Tested and confirmed the issue can easily be reproduced on other operating systems and hardware specifically related to the 5000 series.

![PXL_20220928_025108159](https://user-images.githubusercontent.com/16360335/192676887-ce22cb72-2b29-4ca7-b1ca-8858949c1855.jpg)
 This is the HP Dev one running Pop OS using the Ubuntu Mainline kernel.

**Comment by ruineka** [comment]
I compiled and tested 6.0-RC1 on Pop OS 22.04 and can confirm the error also occurs here. All of the 5.19 kernel versions including 5.19.11 work as expected.

**Comment by ruineka** [comment]
I tested on 6.0 stable release and the issue remains.

**Comment by ruineka** [comment]
I tested gamescope on all the latest commits available to date with linux-next and the issue still remains. The only way gamescope works with these kernels is when nested, attempting to run it from the TTY results in something failing so it closes/aborts on it's own. Running commands like `gamescope -- vkcube` fails to execute as well.

**Comment by ruineka** [comment]
It would appear that the Aya Neo is also affected by this which uses either 4500U/4800 APUs.

**Comment by ruineka** [comment]
This was the results of a bisect, this is what broke gamescope:
```bash
ruineka@pop-os:~/bisect-attempts/linux$ git bisect bad 5d945cbcd4b16a29d6470a80dfb19738f9a4319f
5d945cbcd4b16a29d6470a80dfb19738f9a4319f is the first bad commit
commit 5d945cbcd4b16a29d6470a80dfb19738f9a4319f
Author: Rodrigo Siqueira <Rodrigo.Siqueira@amd.com>
Date:   Wed Jul 20 15:31:42 2022 -0400

    drm/amd/display: Create a file dedicated to planes
    
    [Why]
    The amdgpu_dm file contains most of the code that works as an interface
    between DRM API and DC. As a result, this file becomes very large since
    it comprises multiple abstractions such as plane manipulation.
    
    [How]
    This commit extracts the plane code to its specific file named
    amdgpu_dm_plane. This change does not change anything inside the
    functions; the only exception is converting some static functions to a
    global function.
    
    Tested-by: Daniel Wheeler <daniel.wheeler@amd.com>
    Reviewed-by: Harry Wentland <Harry.Wentland@amd.com>
    Acked-by: Alan Liu <HaoPing.Liu@amd.com>
    Signed-off-by: Rodrigo Siqueira <Rodrigo.Siqueira@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>

 drivers/gpu/drm/amd/display/amdgpu_dm/Makefile     |    7 +-
 drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c  | 2220 ++++----------------
 .../drm/amd/display/amdgpu_dm/amdgpu_dm_plane.c    | 1645 +++++++++++++++
 .../drm/amd/display/amdgpu_dm/amdgpu_dm_plane.h    |   73 +
 4 files changed, 2103 insertions(+), 1842 deletions(-)
 create mode 100644 drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm_plane.c
 create mode 100644 drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm_plane.h
```

**Comment by Samsagax** [comment]
Here is the output of running
```shell
$ gamescope -- vkcube
```
in TTY with the first bad commit of the kernel. Seems that mode set fails:

![screen](https://user-images.githubusercontent.com/798775/196183319-e25acb3b-eef9-452d-9d68-2437941576e1.png)

**Comment by Samsagax** [comment]
> `xwm: We failed our modeset and have no mode to fall back to! (Initial modeset failed?): Invalid argument`
> 
> Do other wayland sessions work?

Yes. At least GNOME (mutter) works. Not sure about any other wlroots based compositor.

**Comment by Samsagax** [comment]
Seems like removing this `abort()` gamescope works.
https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/steamcompmgr.cpp#L1925

**Comment by ruineka** [comment]
@Joshua-Ashton Removing this line gets gamescope to work on the 6.0 kernel...https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/steamcompmgr.cpp#L1925

**Comment by Samsagax** [comment]
Ok. Following @ruineka lead I came to the conclusion that something changed in the kernel behaviour that makes https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/steamcompmgr.cpp#L1914 return non-zero.

Aside from that, the other thing I discovered is that drm_set_mode() only sets `g_DRM->pending.mode_id = mode` and also sets `needs_modeset = true` triggering some properties setting inside `drm_prepare()` but the check in https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/steamcompmgr.cpp#L1922 checks for `g_DRM->current.mode_id` instead. `drm_prepare()` never sets `current.mode_id` so that will always be zero until `drm_commit()` is called and copies `drm->current = drm->pending` if the commit succeded.

According to the message in https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/steamcompmgr.cpp#L1924 the modeset fails, but is checking the wrong variable. So I can think of two solutions:
- Set `drm->current.mode_id = drm->pending.mode_id` when the property is correctly set by `drm_prepare()` below line https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/drm.cpp#L1716
- Check for both `g_DRM->current.mode_id == 0 && g_DRM->pending.mode_id == 0` in line https://github.com/Plagman/gamescope/blob/0626c7c8f8afdb95c1aa82111922f3da74ec9996/src/steamcompmgr.cpp#L1922
so the message is correct (we don´t have a mode nor a pending one and mode setting did fail).

Both were tested and work without breaking anything (as far as I tested). The thing is, that the next if statement is also triggered ("failed to prepare 1-layer flip") but is harmless and only happens once.

I can prepare any of the solutions above, but I'm not entirely sure is a propper fix.

**Comment by Samsagax** [comment]
Ok. I dug a little deeper... Seems like commit [5d945cbcd4b16a29d6470a80dfb19738f9a4319f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5d945cbcd4b16a29d6470a80dfb19738f9a4319f) did introduce some changes aside from refactoring plane functions to its own file.

I bit the bullet to see what changes were and put the functions side by side in two text files with some empty lines in between for easier diff and read:
[old_plane_funcs.txt](https://github.com/Plagman/gamescope/files/9812739/old_plane_funcs.txt)
[new_plane_funcs.txt](https://github.com/Plagman/gamescope/files/9812740/new_plane_funcs.txt)

Then some notable changes:
- Introduces the config option `CONFIG_DRM_AMD_DC_HDR` that should not interfere nor change anything if not set.
- Function `dm_plane_format_mod_supported()` replaced a bunch of code:
```c
/* Check that the modifier is on the list of the plane's supported modifiers. */
-	for (i = 0; i < plane->modifier_count; i++) {
-		if (modifier == plane->modifiers[i])
-			break;
-	}
-	if (i == plane->modifier_count)
-		return false;
```
was replaced by a big switch statement:
```c
/* check if swizzle mode is supported by this version of DCN */
+	switch (asic_id.chip_family) {
+	case FAMILY_SI:
+	case FAMILY_CI:
+	case FAMILY_KV:
+	case FAMILY_CZ:
+	case FAMILY_VI:
+		/* asics before AI does not have modifier support */
+		return false;
+	case FAMILY_AI:
+	case FAMILY_RV:
+	case FAMILY_NV:
+	case FAMILY_VGH:
+	case FAMILY_YELLOW_CARP:
+	case AMDGPU_FAMILY_GC_10_3_6:
+	case AMDGPU_FAMILY_GC_10_3_7:
+		switch (AMD_FMT_MOD_GET(TILE, modifier)) {
+		case AMD_FMT_MOD_TILE_GFX9_64K_R_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_D_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_S_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_D:
+			return true;
+		default:
+			return false;
+		}
+		break;
+	case AMDGPU_FAMILY_GC_11_0_0:
+		switch (AMD_FMT_MOD_GET(TILE, modifier)) {
+		case AMD_FMT_MOD_TILE_GFX11_256K_R_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_R_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_D_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_S_X:
+		case AMD_FMT_MOD_TILE_GFX9_64K_D:
+			return true;
+		default:
+			return false;
+		}
+		break;
+	default:
+		ASSERT(0); /* Unknown asic */
+		break;
+	}
```

From the gamescope output above seems like the 5000 series APUs iGPUs are marked as "Unknown" (They were corerectly identified on prior kernel versions) so maybe the switch is exiting with some of the false statements.

**Comment by Samsagax** [comment]
I just tested and coming back to the old logic in `dm_plane_format_mod_supported()` seems to fix gamescope.

**Comment by Samsagax** [comment]
Patch is sent. Hope this gets resolved and tanks for the feedback.
https://lkml.org/lkml/2022/10/19/1685

**Comment by Grimish-ng** [comment]
I too am also experiencing this. I run of course the holoiso image but I modded and compiled a kernel for my device (as holoiso has horrible performance for amdgpu (APU)'s and high temperatures by default. No surpirse to anyone i'm sure. I've also experienced the exact same. Anything 6.0 kernel plus and gamescope crashes. I appreciate this being looked into.

**Comment by ruineka** [comment]
> I too am also experiencing this. I run of course the holoiso image but I modded and compiled a kernel for my device (as holoiso has horrible performance for amdgpu (APU)'s and high temperatures by default. No surpirse to anyone i'm sure. I've also experienced the exact same. Anything 6.0 kernel plus and gamescope crashes. I appreciate this being looked into. 

@Samsagax has a patch waiting to be merged upstream that reverts what broke this. Hopefully it will be merged soon and backported.

**Comment by Samsagax** [comment]
The patch has been merged upstream, now to wait for it to propagate to mainline
https://gitlab.freedesktop.org/agd5f/linux/-/commit/93e28cf81406519622383ae51d6fd183b744ac46

**Comment by Grimish-ng** [comment]
Found kernel available on patchworks for those as unfamiliar with the development process as I am. https://patchwork.kernel.org/project/dri-devel/patch/20221024030832.119039-1-samsagax@gmail.com/

**Comment by Samsagax** [comment]
Ok. The patch is now in mainline and will be merge (hopefully) in stable for the next point release. Thanks to all who helped figuring this out.
