### ISSUE TITLE
is there not a way to disable wayland at build time?

### ISSUE THREAD

**Issue by wael444** [Plagman/gamescope#629]
X11 systems require wlroots, wayland, wayland-protocols for this to compile, especially if this is going to be used with Xorg why is there no meson option to disable it when building?

**Comment by Joshua-Ashton** [comment]
Gamescope is a Wayland compositor, that only supports Xwayland clients, so no.

**Comment by wael444** [comment]
huh. well maybe it should be clarified in the description more then
