### ISSUE TITLE
Games do not launch with the latest commit

### ISSUE THREAD

**Issue by italoghost** [Plagman/gamescope#634]
Hi! Since the [latest commit](https://github.com/Plagman/gamescope/commit/7c0f65e62dc88f1b29aea235e57c09e0a81bf262), no game is launching while using gamescope.

**Comment by hurricane-dorian** [comment]
Can confirm. 
0134:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
0134:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
info:  Required Vulkan extension VK_KHR_surface not supported

**Comment by emersion** [comment]
Oops, should be fixed with https://github.com/Plagman/gamescope/commit/79ad108c41c3a804664133c089a3ae12fecf1cb2
