### ISSUE TITLE
(55BX 4k LG OLED) works fine at 1080p with any refresh rate from 40Hz to 120Hz, but only if the connection is made through a 1080p 60Hz EDID HDMI passthrough plug

### ISSUE THREAD

**Issue by kanguru007** [Plagman/gamescope#635]
Without the EDID passthrough plug but still -W 1920 -H 1080, the refresh rate values of 50, 60, 100 and 120Hz do work. If the refresh rate is not one of these values, gamescope will not set the mode correctly and the TV will display a magnified quarter of the screen. (maybe the -W 1920 -H 1080 parameters are being ignored and a 4K mode with the wrong timings is set)

Setting the refresh rate to one of the allowed values and then unplugging and replugging the HDMI cable will make the TV work again.

With the EDID plug in place everything works fine, any refresh rate can be set and works well.
(Gamescope is respecting the 1080p from the passthrough plug and ignoring the 60Hz refresh rate, fine with me right now)

This happens with Steam OS 3.3.1 and the Beta

p.s. I edited the /usr/bin/gamescope-session file to limit the output resolution to 1920x1080 and allow for 40-120Hz refresh rates

p.s.2 1920x1080 upscaled and sharpened by the BX LG OLED is sweet, and hard to tell from real 4k, except on very small text.

p.s.3 Unplugging the HDMI cable when the refresh rate is set to anything higher that 72Hz will cause a blank screen on the Steam Deck, this should be avoided in the software. (Up to 72Hz the LCD on my Deck works fine.)

The EDID plug I'm using:
https://www.amazon.es/gp/product/B07C87QFNF/ref=ppx_yo_dt_b_asin_title_o03_s01?ie=UTF8&th=1

**Comment by Joshua-Ashton** [comment]
We always pick the greatest res by default for external adapters -- if there is no gamescope mode file.

Would you be able to send the output of `drm_info` without the edid adapter present?

**Comment by kanguru007** [comment]
[drm_info.txt](https://github.com/Plagman/gamescope/files/9660936/drm_info.txt)

**Comment by kanguru007** [comment]
Hi. I've upgraded my Steam Deck to 3.3.2 and I was sorry to see that the variable frame rate setting is gone for external monitors. It is a pity because it was working great and it is such a useful feature.
(The passthrough plug that I had used is passive and only modifies the initial capabilities message sent from the monitor)

**Comment by kanguru007** [comment]
Steam OS 3.3.2 build 20221003.100
Variable frame rate is now working perfectly on both internal and external monitors.
Awesome!!!
