### ISSUE TITLE
[CLOSED] Mouse sensitivity different when used in and outside gamescope.

### ISSUE THREAD

**Issue by JxJxxJxJ** [Plagman/gamescope#637]
Mouse sensitivity get's actually slower when using gamescope. Happens in CSGO, League, Overwatch, Ultrakill, so I guess it's a general behavior. 

Note than when using virtual desktops (in lutris) the sensitivity acts as expected (tested with LoL and Overwatch).

I'm using Hyprland with Proton-GE 35, League and Overwatch were installed using their Lutris' scripts, the rest from Steam.

**Comment by Neubulae** [comment]
why is this closed

**Comment by JxJxxJxJ** [comment]
ok we're open

**Comment by luni3359** [comment]
Why did you close it again?

**Comment by noobmagnet** [comment]
This is an issue that persists, why was it closed?

**Comment by tienbuigia** [comment]
I was wonder why my mouse feels weird when using gamescope. This may be the reason.

**Comment by Hasshu** [comment]
OP, are you okay?

In any case, there's #196.

**Comment by github12101** [comment]
This seems to be a duplicate of #196, admin please mark it as such, so it can be closed, and #196 left open.
