### ISSUE TITLE
Rendering issues / artifacts on sway+intel

### ISSUE THREAD

**Issue by WhyNotHugo** [Plagman/gamescope#638]
Rendering is all broked, here's steam:

![Screenshot from 2022-10-04 at 09_52_24 591172346](https://user-images.githubusercontent.com/730811/193765211-2075f911-ccb8-4c7b-a9b8-3ff529748e8e.png)

Here's `l3adpaf`:

![Screenshot from 2022-10-04 at 09_52_26 803475518](https://user-images.githubusercontent.com/730811/193765234-687b078c-5213-4da0-8021-16b186e734e2.png)

I'm ArchLinux, using sway-git, intel graphics and linux-5.19.

Any ideas what might be up?

**Comment by Samsagax** [comment]
Try setting `INTEL_DEBUG=noccs`. If that "fixes" it, then is a duplicate of #356 . That is not a fix since it will come with a severe degradation of performance.

**Comment by WhyNotHugo** [comment]
`INTEL_DEBUG=noccs` fixes it; closing as dupe.
