### ISSUE TITLE
Interger scaling does not appear to work right on non deck systems.

### ISSUE THREAD

**Issue by Bitwolfies** [Plagman/gamescope#644]
For this example I will use Shantae: Risky's Revenge - Director's Cut.

This game is a port to Steam from the original DSi game, originally running at a resolution of 256x192, in game, there is an option to set the resolution to 1024x768, which is a clean and even scale. So 1024x768 integer scaled to my monitor of 2560x1440 would bring the res to 1792x1344 for a clean and even integer scale. 

This works on my Steam Deck, setting the game to the 1024x768 resolution and changing it from linear to interger zooms the game out slightly, creating a proper scale. 

Running this however, on my KDE desktop in X or Wayland, on my GTX3080 results in this: 
![Screenshot_20220719_102528](https://user-images.githubusercontent.com/65789901/195255674-3c90a7a8-4450-4a58-91e7-7b4ec5529aad.png)

This isn't right, and im honestly not sure why, it works perfectly as expected on my Deck, but fails on desktop, the command I used was 
"gamescope -w 1024 -h 768 -W 2560 -H 1440 -i %command%" 

I originally tried only specifying monitor resolution, and not in game, but it results in the same issue.

**Comment by Samsagax** [comment]
You are using integer scaling with `-i`. Try another switch maybe?

**Comment by dobosken** [comment]
User error.
1024x768 cannot integer scale up to 2560x1440. The nearest integer scale is 2x, which would result in an output of 2048x**1536**.

**Comment by Bitwolfies** [comment]
> 

Forgot to close this, but that wasnt the issue actually, it just hated that at the time, the game would not use fullscreen mode
