### ISSUE TITLE
Vsync refresh rate factor instead of or as alternative to fps limit

### ISSUE THREAD

**Issue by lexkalin** [Plagman/gamescope#655]
This is primarily related to steam deck implementation, but can be useful in general. In games that support the feature (e.g. half Vsync) this results in far smoother frame times, power management and input lag compared to when the fps limits are being used. Also helps with games that have no vsync settings to override. For games that don’t have in-built settings can be currently managed via dxvk.conf file per game, but it’s not as handy and fast as an OSD option doing the same. Wonder if vsync override with 0, 1, 2 and 3 factor (off, normal vsync, half and third respectively) could be implemented in gamescope alongside or instead of existing fps limit.

**Comment by Joshua-Ashton** [comment]
What you are describing is exactly how the current system already works. The FPS limit value is used to determine a vsync factor.

I do have a low latency arbitrary fps limiter I want to bring back as an alternative though.

**Comment by lexkalin** [comment]
> What you are describing is exactly how the current system already works. The FPS limit value is used to determine a vsync factor.
> 
> I do have a low latency arbitrary fps limiter I want to bring back as an alternative though.

Thank you for the information, appreciate that and apologies for proposal that turned out to be not an improvement in any sense. Do I get it right then, that from input lag (and whatever other) perspective, for example, the half-vsync in-game option from GTA V should be absolutely equal to enabling 30 fps limit in Gamescope and leaving in-game vsync off? 

Also, great to find out some lower latency alternative is a potential future option.

**Comment by Joshua-Ashton** [comment]
Yes it should be equal
