### ISSUE TITLE
Gamescope broken using Arc A750

### ISSUE THREAD

**Issue by tychii93** [Plagman/gamescope#656]
Using Arch.

Had to update to mesa 22.3 devel because vkcube alone doesn't start on 22.2 from the official repos, otherwise without gamescope works fine.  GLXGears without gamescope also works but the same issue occurs once Gamescope is used.
Gamescope from repo and gamescope-git from the AUR are affected.

Before installing the Arc GPU, I used an RTX 2070 which worked with Gamescope.  All I did before replacing the GPU was uninstalled the Nvidia drivers and remove the nvidia DRM kernel parameter.

Kernel version is 6.0.1-arch2-1

![image](https://user-images.githubusercontent.com/13793605/196665064-30ff24c8-99ee-4993-bcdd-a3ccb54f7a21.png)

```
[ty@arch ~]$ gamescope vkcube
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:82] Creating headless backend
vulkan: selecting physical device 'Intel(R) Arc(tm) A750 Graphics (DG2)': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55c8ddadacc0 (res 0x55c8ddad67a0)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 121
pipewire: renegotiating stream params (size: 1280x720)
Selected GPU 0: Intel(R) Arc(tm) A750 Graphics (DG2), type: DiscreteGpu
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55c8dd7f72b0 (res 0x55c8ddadbd20)
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
```

**Comment by Samsagax** [comment]
Seems like #356 extended to Vulkan apps.

**Comment by tychii93** [comment]
Looking through the thread.  The INTEL_DEBUG=norbc seems to have fixed it.  I wonder if it's safe to set this globally in /etc/environment or if it'll break anything else.  I'll probably close the issue if it doesn't negatively affect anything else.
