### ISSUE TITLE
Move to wlroots 0.16

### ISSUE THREAD

**Issue by Joshua-Ashton** [Plagman/gamescope#667]
I started some work here a while ago, just needs to be bumped again and rebased.

https://github.com/Plagman/gamescope/tree/wlroots_16

cc: @emersion anything you are doing dependent on this?

**Comment by emersion** [comment]
The cleanup in https://github.com/Plagman/gamescope/pull/666 will depend on an even newer wlroots. Apart from that, I don't think I'm doing other stuff that depends on 0.16+. Would still be great to upgrade!
