### ISSUE TITLE
Stop using ALLOW_MODESET unconditionally

### ISSUE THREAD

**Issue by emersion** [Plagman/gamescope#67]
ALLOW_MODESET allows the driver to apply the new state with a visual glitch (e.g. black screen during 5 seconds). This isn't great while in the middle of a gaming session.

https://github.com/Plagman/gamescope/blob/453caf76728bd4bed9b3f293f97cdef173e3a2d3/src/drm.cpp#L796

Ref https://github.com/Plagman/gamescope/commit/b306714f3cddb0ee0d554fb418c99b8244ccaa77

**Comment by Valmar33** [comment]
Is all that's required is removing the `1 ||` part?

**Comment by emersion** [comment]
We need to make sure that doesn't break anything. See the comment above.

**Comment by Valmar33** [comment]
I was planning to test it, anyways. If only I can make my patch apply... :|

**Comment by Valmar33** [comment]
God, I hate whitespace-tab conflicts...

**Comment by Valmar33** [comment]
So, how do I test it, exactly?

**Comment by Valmar33** [comment]
Haven't run into any issues, personally.

RX 580
Mesa commit 605b0e8acf3

**Comment by emersion** [comment]
The comment above says it breaks when changing the destination rectangle. So the testing procedure would be:

- Run SteamOS, then a game that doesn't have the screen's aspect-ratio
- Make sure direct scan-out is used for both

Could also programmatically change the `CRTC_*` properties.

**Comment by Plagman** [comment]
Yes that was put in because amdgpu had bugs when not specifying it and wouldn't let you change rects. I reported it but it was pretty fundamental so not sure if it got fixed. I think most users here are running nested so wouldn't be impacted and won't be able to properly test the ramifications.

**Comment by emersion** [comment]
When removing `ALLLOW_MODESET`, gamescope with libliftoff enabled freezes (no atomic commit failure). amdgpu drops the commit and prints an error:

```
[16283.676840] [drm:dc_commit_updates_for_stream [amdgpu]] *ERROR* Mode validation failed for stream update!
[16293.708914] [drm:drm_atomic_helper_wait_for_flip_done [drm_kms_helper]] *ERROR* [CRTC:62:crtc-0] flip_done timed out
```
