### ISSUE TITLE
Feature Request: Have the Official FSR Resolutions within Gamescope

### ISSUE THREAD

**Issue by FaddishDisc7** [Plagman/gamescope#671]
I own a 1080p monitor but somehow I cant go for Ultra Quality (1477x831), balanced (1129x638), or performance mode (960x540). The only 2 modes that I use are near ultra quality (1472x832) with the gamescope -w 1477 -h 831 -f -U -- command and Quality (720p). Performance and Balanced resolutions are no where to be seen. Giving an option for these obscure resolutions without the launch command would definitely help those who are not tech savvy and could follow the fsr quality settings chart to find a preferred resolution.

**Comment by MCPO-Spartan-117** [comment]
What do you mean you can't go for it? GameScope itself. as far as i know, doesn't advertise any of FSR's resolutions, it's up to the user what they want and really all you need to do to get the resolution quality preset you want like ultra quality is simply 1920/1.25 = 1536 and 1080/1.25 = 1280, up the division by 0.25 and you get the next quality preset, this goes for the other upscaling methods too, this is something i guess they could put into the help argument or a man page i suppose though.
