### ISSUE TITLE
Nested: SDL touch_id is out of range for the WLSERVER_TOUCH_COUNT comparison.

### ISSUE THREAD

**Issue by jaunkst** [Plagman/gamescope#682]
WLSERVER_TOUCH_COUNT is defined as a maximum number of touch events , but its being compared against its touch_id which could be greater than 11. 

This is a log of my touch_id
```
wlserver: wlserver_touchdown: touch_id=1340, x=0.173555, y=0.148807, time=75855
```

note the `touch_id is 1340`, which is certainly greater than all my fingers and a nose which is defined here.
wlserver.hpp
```hpp
#define WLSERVER_TOUCH_COUNT 11 // Ten fingers + nose ought to be enough for anyone
````

and the comparison here. 

wlserver.ccp
```cpp
if ( touch_id >= 0 && touch_id < WLSERVER_TOUCH_COUNT )
{
	std::cout << "wlserver_touchdown > wlr_seat_touch_notify_down\n" ;
	wlr_seat_touch_notify_down( wlserver.wlr.seat, wlserver.mouse_focus_surface, time, touch_id,
								wlserver.mouse_surface_cursorx, wlserver.mouse_surface_cursory );

	wlserver.touch_down[ touch_id ] = true;
}
```

By removing this check I am able to get valid touch events on my seat for the notify motion and the touch events.  It should also be addressed for the up event.

**Comment by jaunkst** [comment]
If removing the touch_ids is good a good enough fix I've opened a PR.
https://github.com/Plagman/gamescope/pull/683

**Comment by jaunkst** [comment]
So I guess we need a solution that can recycle up too 11 wayland object ids instead of allocating up to 0xFFFFFFFF in booleans.

**Comment by jaunkst** [comment]
I think its wayland, they start at 1 and will continue to 4294967295

**Comment by emersion** [comment]
Ah, so this is about nested mode? SDL's `fingerId`?

**Comment by jaunkst** [comment]
must be it. Sint64 ?

**Comment by jaunkst** [comment]
My shallow attempt at fixing this issue by indexing the touch events.
https://github.com/Plagman/gamescope/pull/684
