### ISSUE TITLE
DMA-BUF leak in embedded

### ISSUE THREAD

**Issue by emersion** [Plagman/gamescope#69]
Embedded, no libliftoff, no direct scan-out, running Sekiro.

```
dup failed: Too many open files
gamescope: ../src/steamcompmgr.cpp:522: bool import_commit(wlr_dmabuf_attributes*, commit_t&): Assertion `commit.vulkanTex != 0' failed.
```

**Comment by Plagman** [comment]
This didn't use to be a problem and fd usage was stable over time. I saw that some recent changes had changed the logic I was using around dup()/close() to get to the point where FDs weren't leaking, so maybe something regressed there?

**Comment by emersion** [comment]
Doesn't happen anymore after https://github.com/Plagman/gamescope/commit/dd4d035808addf7c9694e0e423a12c1881e54cd9
