### ISSUE TITLE
Not working with MangoHud

### ISSUE THREAD

**Issue by ppascher** [Plagman/gamescope#70]
Trying to start a steam game using gamescope while using [MangoHud](https://github.com/flightlessmango/MangoHud/) (via MANGOHUD=1 gamescope) I get a segfault. Not sure if this is a gamescope or MangoHud issue (or something I am doing wrong).
I tried building MangoHud with "--buildtype=debug" but for some reason it is missing symbols.

[gamescope_bt_full.log](https://github.com/Plagman/gamescope/files/4801476/gamescope_bt_full.log)

**Comment by Valmar33** [comment]
Have you tried `MANGOHUD=1 gamescope -- mangohud <application>`?

**Comment by ppascher** [comment]
Thank you!
This put me on the right track though I had to modify it a little:
`MANGOHUD=0 gamescope -- mangohud  %command%`
This way the game starts with mangohud. Setting MANGOHUD=1 before the gamescope command would result in the same segfault.
