### ISSUE TITLE
Mesa commit 7406ea37e6b666d474ab62982ca333d518c84231 breaks launching of games on RX580, and possibly other gfx8 cards

### ISSUE THREAD

**Issue by Valmar33** [Plagman/gamescope#71]
https://gitlab.freedesktop.org/mesa/mesa/commit/7406ea37e6b666d474ab62982ca333d518c84231

"ac/surface: require that gfx8 doesn't have DCC in order to be displayable"

Commit breaks running any games on Gamescope on RX580, and possibly other gfx8 cards.

GPU: RX 580
Distro: Arch Linux
Linux version: 5.7.4
libdrm version: 2.4.102

Mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3190

**Comment by emersion** [comment]
Is this in embedded mode or in nested mode?

**Comment by Valmar33** [comment]
Can you remind me what the difference is?

**Comment by Valmar33** [comment]
I think it might be nested? I'm running Gamescope from within KDE.

**Comment by emersion** [comment]
Yup, that's nested.

**Comment by emersion** [comment]
How does it break gamescope?

**Comment by Valmar33** [comment]
Gamescope will freeze immediately before the game window can start rendering.

More specifically, some games will initially start in windowed mode ~ the window shows up, but nothing renders. If a game starts in fullscreen, Gamescope will just show whatever was on the screen right before the Gamescope window pops up.

In the case of Bayonetta, for some odd reason, it first renders a window with all white rendered inside, then is stuck on that.

Examples:

**Dragon's Dogma: Dark Arisen**
![Screenshot_20200628_221108](https://user-images.githubusercontent.com/5097518/85947166-65a39200-b98c-11ea-85a2-950bd62683f0.png)

**Bayonetta**
![Screenshot_20200628_221227](https://user-images.githubusercontent.com/5097518/85947194-7fdd7000-b98c-11ea-8522-d5c3b0fae9f8.png)

**Dark Souls**
![Screenshot_20200628_221328](https://user-images.githubusercontent.com/5097518/85947228-a13e5c00-b98c-11ea-8c6c-4313698fbc93.png)

**Comment by Valmar33** [comment]
Gamescope prints nothing useful logwise.

I've encountered issues with non-Steam games, too, such as with Dust: An Elysian Tail.

![Screenshot_20200628_221502](https://user-images.githubusercontent.com/5097518/85947260-e2cf0700-b98c-11ea-9e90-534d37b0ff08.png)

**Comment by Valmar33** [comment]
Closing because Mesa issue was closed with a revert.
