### ISSUE TITLE
Please add a launch option to force in windowed mode based on the -W -H  options

### ISSUE THREAD

**Issue by dPing** [Plagman/gamescope#739]
this isn't necessarily an issue but some games I prefer to start in windowed mode and not full screen. Instead of launching then pressing Ctrl+meta+f, if there was a launch option for this, I would greatly appreciate this.

**Comment by KagoraTheGrindcoreAddict** [comment]
What does using the `-b` flag not do that `Ctrl+meta+f` does?

**Comment by dPing** [comment]
> 

-b is windowed no border as in it is basically full screened. I would like to see about a windowed option that isn't tied to full screen but resizable in nature.

**Comment by dPing** [comment]
closing this since lutris forces the -f option inherently ignoring the -b option for gamescope
