### ISSUE TITLE
Cursor is visible in csgo

### ISSUE THREAD

**Issue by pranshuthegamer** [Plagman/gamescope#747]
![image](https://user-images.githubusercontent.com/61378895/212534944-c5a350c4-1163-4b9e-aee8-e18555b589c5.png)
![image](https://user-images.githubusercontent.com/61378895/212534960-415d721a-cd79-49af-a78e-a2ec60650adc.png)

**Comment by Joshua-Ashton** [comment]
Can you please give some info about your setup? What DE etc

**Comment by pranshuthegamer** [comment]
issue fixed after doing a full system upgrade

i use:
KDE plasma
Arch linux
Ryzen CPU
Radeon + Nvidia GPU
