### ISSUE TITLE
Accumulating many .foz files with Gamescope

### ISSUE THREAD

**Issue by cchulo** [Plagman/gamescope#749]
So I am running Emulationstation-DE, Resident Evil HD, and Nier Automata all with Gamescope. I have been noticing that every time I start up with gamescope it creates a new .foz file inside of the steamapps/shadercache/fozpipelinesv6 directory. It looks like the way it is creating them is a bug because the hash is the same, but it keeps making copies. Take RE HD for example:

it is executed with `gamescope -H 1440 -h 1440 -r 60 -f -- %command%`
The Foz files that are created every time look like:
![image](https://user-images.githubusercontent.com/9343504/212772998-6795a1f9-79ab-45e7-b8d7-391ac7465248.png)

With emulationstation-DE, something that's been installed longer than RE HD and has been used quite a bit:
![image](https://user-images.githubusercontent.com/9343504/212773734-08db47e1-37d2-494a-9941-87e1a934939b.png)

Note that for ES-DE the hash changed at some point, this may have been due to me installing new GPU drivers

With Nier its the same situation, a new .foz file everytime I launch the game

All the .foz files are the same size, the question is though is this a bug with gamescope or with steam? It looks as if gamescope doesn't bother to check if a foz file already exists, it just keeps creating them. Since I don't think steam is what is creating these files, I don't think steam will know how to clean these files up. ES-DE for example has 300 mb accumulated.

**Comment by cchulo** [comment]
this may not be a problem with gamescope, but fossilize, will open a PR over at that repo

**Comment by cchulo** [comment]
reopening, as I think I know what these files are. These are pre-compiled shaders, and for some reason gamescope might be making steam runtime think that the last pre-compiled shaders were invalid, and thus creating a new .foz each time a game is launched with gamescope.

**Comment by cchulo** [comment]
determined that this is not a gamescope problem, the issue is happening with Quake as well, and I have definitely never run that game with gamescope. Will open an issue with steam-runtime.

**Comment by dstrnad** [comment]
Was this ever solved? I have the same issue

**Comment by cchulo** [comment]
I have not bothered looking in a while, i will check when i get out of work. In the end i could not get support with this issue anywhere, so I more or less just ignored it
