### ISSUE TITLE
Gamescope misbehaves under wlroots compositor, Wayfire

### ISSUE THREAD

**Issue by kode54** [Plagman/gamescope#76]
Is this a known issue? Running:

```
gamescope -W 1280 -H 720 -- glxgears
```

https://f.losno.co/v/wayfire_gamescope.mp4

**Comment by Plagman** [comment]
I think this is a combination of not having the necessary Mesa PR applied and not using R600_DEBUG=nodcc.

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4885

**Comment by kode54** [comment]
I may need the merge, but wasn't aware that all cases definitely needed that R600_DEBUG=nodcc setting. It used to work for me without either of those, but then again, I was running it nested under a Gnome Xorg session, not a Wayfire (and thus Wayland) session.

**Comment by kode54** [comment]
That commit fixes the rendering issue, and the nodcc setting had no effect with or without the patch. Does that matter since I'm using an RX 480?
