### ISSUE TITLE
Fullscreening with Vulkan results in blackscreen on mouse inactivity

### ISSUE THREAD

**Issue by TSRBerry** [Plagman/gamescope#773]
We've been getting more and more reports about blackscreens using GTK and Vulkan for Ryujinx users.

We are tracking this issue [here](https://github.com/Ryujinx/Ryujinx/issues/3874) and can only offer a workaround, as the issue only occurs using gamescope.
As far as I can tell the issue occurs on mouse inactivity and as the video in the linked issue shows it can be temporarily solved by touching the screen / moving the mouse. (This can also be done programmatically and works the same way.)

For a while this was really difficult to even reproduce since it only happened on the Steam Deck preview branch for a long time.
But this [comment](https://github.com/Ryujinx/Ryujinx/issues/3874#issuecomment-1362860611) explains, when it started happening on the stable branch as well, so hopefully this helps a tiny bit in tracking down the root issue.

We spend a lot of time trying to solve this issue on our end, but this really seems to be a gamescope issue and we can't do anything about it.

If there is anything I can provide or help with to help solving / debugging this issue please let me know.
We are usually treating the Steam Deck as any other Linux machine and aside from this issue it's working very well.
Hopefully this can be resolved too.

**Comment by Joshua-Ashton** [comment]
That is very bizzare indeed... I will try and take a look.

**Comment by Joshua-Ashton** [comment]
Little mini hypothesis: when the cursor is up, we force composition as we can't use planes.
When the cursor gets hidden, we try to flip the app's buffers directly to the screen which is somehow resulting in black...

If you enable Force Composition in the SteamOS Developer Options, does it always work then?

**Comment by piplup55** [comment]
> If you enable Force Composition in the SteamOS Developer Options, does it always work then?

tested 5 times and every time it displayed the game perfectly fine

**Comment by 0xDEADCADE** [comment]
Commenting here just to say that it does not exclusively affect Ryujinx, but other applications too, just not in the same way.

From my testing, RPCS3 (PS3 Emulator) has a similar issue also mitigated by moving the mouse or showing any kind of overlay. Instead of turning completely black, the frame pacing appears to suffer greatly. I don't know if there's an existing issue to track it on their side.

On my side, the issue also appears to be resolved with enabling "Force Composition" in SteamOS developer settings.

**Comment by TSRBerry** [comment]
> If you enable Force Composition in the SteamOS Developer Options, does it always work then?

I forwarded your comment to our Steam Deck users, since I currently don't have one with me. As @piplup55 already commented, it seems to fix this issue!

Does that mean you have an idea what could be causing this issue here? I'd be curious to learn how feeding the app's buffer directly to the screen is causing blackscreens :D

**Comment by Mhytee** [comment]
> Commenting here just to say that it does not exclusively affect Ryujinx, but other applications too, just not in the same way.
> 
> From my testing, RPCS3 (PS3 Emulator) has a similar issue also mitigated by moving the mouse or showing any kind of overlay. Instead of turning completely black, the frame pacing appears to suffer greatly. I don't know if there's an existing issue to track it on their side.
> 
> On my side, the issue also appears to be resolved with enabling "Force Composition" in SteamOS developer settings.

This is incredibly interesting to hear because I have had a similar issue in Forza Horizon 5. Frame pacing will be all over the place, but when you open the “…” button overlay the frame pacing immediately smoothens right out. I wonder if this will fix the issue in that game as well. Will test and check back.

**Comment by Joshua-Ashton** [comment]
> Does that mean you have an idea what could be causing this issue here

Nope! I wish it did. It just narrows it down further...

**Comment by Joshua-Ashton** [comment]
You are correct in that regressed from 3.3 -> 3.4. I will try to narrow down what part is going wrong.

**Comment by Joshua-Ashton** [comment]
This isn't a Gamescope issue, looks to be Mesa-sided...

Downgrading from the current Mesa on Deck to the version used in 3.3 makes this work.

I will try and bisect where this broke.

**Comment by Joshua-Ashton** [comment]
Narrowed it down to this commit here: https://gitlab.freedesktop.org/mesa/mesa/-/commit/211db6d3336a05697d825cbef10f6d4fd8511315

**Comment by Joshua-Ashton** [comment]
Looks like it works fine with Mesa main.

**Comment by 1basti1** [comment]
> Looks like it works fine with Mesa main.

When will this be in SteamOS Stable? I still have black screen, without force composition.

**Comment by TSRBerry** [comment]
https://store.steampowered.com/news/app/1675200/view/3675538825744699879

Seems like this can be closed now! Although it wasn't even a gamescope issue to begin with.

Thank you again for investigating this!
