### ISSUE TITLE
Missing hwdata package, but it's installed in the system

### ISSUE THREAD

**Issue by vanfanel** [Plagman/gamescope#785]
Hi there,

Gamescope compositor fails to build on Debian 11 (Stable) because it's unable to detect the hwdata package:

```
Run-time dependency hwdata found: NO (tried pkgconfig and cmake)

../meson.build:33:0: ERROR: Dependency "hwdata" not found, tried pkgconfig and cmake
```

But the package is installed in the system:

```
root@raspberrypi:~/src/wayland/gamescope/b4# sudo apt list --installed |grep hwdata

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

hwdata/stable,stable,now 0.345-1 all [installed]
```

In fact, **hwdata is a dependency for Wlroots 0.16.2, which I can build fine on the same system, and uses the meson buildsystem too.**

But looking at the MESON logs, it seems that gamescope buildsystem is trying to do this:

`pkg-config hwdata --modversion`

...Which fails here:
```

root@raspberrypi:~/src/wayland/gamescope/b4# pkg-config hwdata --modversion
Package hwdata was not found in the pkg-config search path.
Perhaps you should add the directory containing `hwdata.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hwdata' found
```

So, either hwdata has some problem with it's pkgconfig installation, or it's a problem with the way gamescope detects it.

**Comment by emersion** [comment]
You need a new enough hwdata. hwdata has introduced a pkg-config file somewhat recently.

**Comment by jwoertink** [comment]
For anyone else that lands here, I assumed it was this repo https://github.com/vcrhonek/hwdata. Cloned it, then ran `make` and `sudo make install`. After that was done

```
❯ pkg-config hwdata --modversion
0.374
```
