### ISSUE TITLE
Possible to use system's wlroots installation instead of internal subproject?

### ISSUE THREAD

**Issue by vanfanel** [Plagman/gamescope#786]
Hi there,

Gamescope seems to have wlroots as a dependency, and it's included as a subproject with the gamescope sourcecode.

However, it's a bit of a pain to be forced to have wlroots forcibly built as a submodule, because, for example, I don't have or want ANY X11 packages on the system, and there's no way to disable xwayland support in wlroots subproject:
```

../subprojects/wlroots/xwayland/meson.build:28:3: ERROR: Problem encountered: Install "xwayland" or pass "-Dxwayland=disabled".
Required for Xwayland support.
```

Ok, so I go and pass `-Dxwayland=disabled`, but then I get an error because  `-Dxwayland=disabled` is a wlroots and not a gamescope thing:
`../meson.build:1:0: ERROR: Unknown options: "xwayland"`

So, is there a way to have gamescope my system-wide installed wlroots lib, please?

**Comment by Joshua-Ashton** [comment]
Gamescope needs XWayland. It's designed to be an XWayland compositor.
