### ISSUE TITLE
Possibility to build without massive legacy X11 dependencies

### ISSUE THREAD

**Issue by vanfanel** [Plagman/gamescope#787]
Hi there,

Is it somehow possible to build without having to install a TON of X11 related dependencies?
I have to install all this cruft in order to pass the meson configuratio for a Wayland compositor:
`
apt-get install libx11-dev libx11-xcb-dev libxdamage-dev libxcomposite-dev libxrender-dev libxxf86vm-dev libxtst-dev libxres-dev libxmu-dev`

...And even so, the build system expects me to have XWayland installed, which I don't, because it's an wlroots dependency I can't disable.

So, is there a way around all of it?

Thanks!

**Comment by mbriar** [comment]
Gamescope by default doesn't even support wayland clients and absolutely needs xwayland.

**Comment by emersion** [comment]
Yeah, gamescope is made to run games, and almost all games use X11.
