### ISSUE TITLE
Static Analysis Errors Using CodeChecker

### ISSUE THREAD

**Issue by surafel911** [Plagman/gamescope#789]
Forked the project and ran the code & build through the [CodeChecker](https://github.com/Ericsson/codechecker) static analyzer. It had found some high severity issues with gamescope and dependency code that I thought would be interesting to share. I can work on some of these and/or add these to the CI pipeline if there's further interest in this.

Extract tarball and open `./reports_html/index.html` in firefox to view issues: [reports_html.tar.gz](https://github.com/Plagman/gamescope/files/10717525/reports_html.tar.gz)

Could also make use of `-fstanatize=address` when building (I've never used meson nor ninja before so not sure how I would add that other than appending the `CXX` environment variable): https://maskray.me/blog/2023-02-12-all-about-leak-sanitizer

**Comment by Joshua-Ashton** [comment]
Is there anything specific you want to point out from that report? There doesn't seem to be much of interest pointing at any of our code.

The only thing I saw was the file open leaks in some of the DRM code in the error path.

**Comment by surafel911** [comment]
For your code, nothing specific.

I am posting the results from the submodules in their respective repos. Wasn't sure if there were any overlap in maintainers between gamescope and other projects so I just posted it here as well. Not too well versed in these projects but hopefully this is a productive entry point.
