### ISSUE TITLE
Firefox kiosk mode is broken in gamescope

### ISSUE THREAD

**Issue by hungrymonkey** [Plagman/gamescope#798]
I attempted to use firefox in kiosk mode and the whole application is bork. You cannot interact with the program

```
Target: "/usr/bin/flatpak"
Start in: "$HOME"
Launch Options: run --branch=stable --arch=x86_64 --command=firefox --file-forwarding org.mozilla.firefox --kiosk
```

LSB Version:    n/a
Distributor ID: SteamOS
Description:    SteamOS Holo
Release:        rolling
Codename:       Holo

Steam OS 3.4.4

**Comment by hungrymonkey** [comment]
` MOZ_ENABLE_WAYLAND=1 gamescope -- env WAYLAND_DISPLAY='wayland-0' firefox --kiosk`

Works

**Comment by hungrymonkey** [comment]
on the latest main branch

**Comment by hungrymonkey** [comment]
./build/src/gamescope --expose-wayland -- firefox --kiosk

**Comment by hungrymonkey** [comment]
I found the workaround for this issue

`full-screen-api.ignore-widgets = true` (Fixes fullscreen under gamescope, by enabling a sort-of borderless fullscreen mode that doesn't attempt to take over the desktop.)

https://www.reddit.com/r/SteamDeck/comments/16eiyi6/make_firefox_work_better_in_game_mode/?utm_source=share&utm_medium=web2x&context=3

Thanks [Fibbitts](https://www.reddit.com/user/Fibbitts/)

**Comment by GloriousEggroll** [comment]
just noting this is still broken. the workarounds do not allow for a native kiosk-like window such as chrome does. unfortunately native chromium shipped by fedora does not allow twitch.tv playback due to codec limitations imposed on their ffmpeg build. firefox in fedora has an h264 plugin that allows twitch playback, however as noted, --kiosk mode is broken. the workarounds above do not allow kiosk mode to work, and the most recent workaround requires several tweaks to firefox and still isn't a complete solution

**Comment by GloriousEggroll** [comment]
this appears resolved, checked today in firefox 122 on fedora and it was fine. also checked flatpak and it worked fine

**Comment by hungrymonkey** [comment]
> this appears resolved, checked today in firefox 122 on fedora and it was fine. also checked flatpak and it worked fine

I should had listed all the broken features in my original bug report. I do not remember. I do not see any obvious bugs right now in opensuse tumbleweed.

zypper info gamescope
Repository 'packman-essentials' is out-of-date. You can run 'zypper refresh' as root to update it.
Loading repository data...
Reading installed packages...


Information for package gamescope:
----------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : gamescope
Version        : 3.14.0-1.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 2.4 MiB
Installed      : Yes
Status         : up-to-date
Source package : gamescope-3.14.0-1.1.src

Mozilla Firefox 122.0
