### ISSUE TITLE
Support XEMBED to be aware of systray windows

### ISSUE THREAD

**Issue by Plagman** [Plagman/gamescope#80]
So we can ignore them in steamcompmgr and maybe eventually do something with them. Right now there's a size hack papering over it for the Origin launch flow.

**Comment by emersion** [comment]
- XEmbed: https://specifications.freedesktop.org/xembed-spec/xembed-spec-latest.html
- System Tray: https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-latest.html
