### ISSUE TITLE
If I add --hdr-enabled, the game isn't launched.

### ISSUE THREAD

**Issue by laichiaheng** [Plagman/gamescope#825]
How to properly enable HDR for Elden Ring?
Should I run Steam in DRM mode?
Or I can run the game under Gnome session?

**Comment by Xathros1** [comment]
https://wiki.archlinux.org/title/HDR_monitor_support

**Comment by laichiaheng** [comment]
I have installed DXVK2.1, gamescope-plus, gamescope-session-git, added DXVK_HDR=1 in /etc/environment.
Where should I add the `--hdr-enabled` for gamescope session?
Should I compile a custom kernel to enable it?
