### ISSUE TITLE
Is there a command to zoom/stretch the screen in game mode to the full screen of the Steam deck?

### ISSUE THREAD

**Issue by RyuSeisuke1992** [Plagman/gamescope#831]
Games with black bars like Dragons Dogma I want to zoom in so that the whole screen is filled. The HUD should remain untouched since it is very far from the edge. If that is not possible, then I would even stretch that to the outer edge. Is there already the possibility?

**Comment by Joshua-Ashton** [comment]
This is available in SteamOS Main + Client Beta

**Comment by RyuSeisuke1992** [comment]
okay thank you. I have now not known how to unlock the channel main but that only goes through the developer mode. 
https://www.reddit.com/r/SteamDeck/comments/11tq81i/metal_gear_rising_tested_using_scaling_options/

**Comment by EysseW** [comment]
Any chance of this getting implemented in gamescope? I would love to use it on non steam deck devices :D
