### ISSUE TITLE
Handle client request to set NET_WM_STATE_HIDDEN

### ISSUE THREAD

**Issue by emersion** [Plagman/gamescope#86]
We only handle client requests to set NET_WM_STATE_FULLSCREEN right now.

Ref https://github.com/swaywm/sway/pull/5566

**Comment by Plagman** [comment]
Not strictly related to HIDDEN imo, but one example of better handling requests is the launch flow of an Origin game. Near the end the Origin window will try to minimize/iconify itself. We don't really honor it right now, so Wine just resizes it to the small iconified size of 160x54 (or whatever it was) and we get to look at the top-left corner of Origin until the game starts. Instead we should properly unfocus it and go back to the Steam waiting screen until something nudges focus again, probably.

**Comment by emersion** [comment]
Yeah. winex11 will make this go through WM_CHANGE_STATE, see https://github.com/Plagman/gamescope/pull/85

**Comment by emersion** [comment]
The EWMH spec says:

> Implementation note: if an Application asks to toggle _NET_WM_STATE_HIDDEN the Window Manager should probably just ignore the request, since _NET_WM_STATE_HIDDEN is a function of some other aspect of the window such as minimization, rather than an independent state. 

Wine doesn't care about `_NET_WM_STATE_HIDDEN`.
