### ISSUE TITLE
Embedded Gamescope does not start on kernel with HDR patches

### ISSUE THREAD

**Issue by BoukeHaarsma23** [Plagman/gamescope#910]
I have had to revert the commit 9b70b3b9e38057d51e0a0bdbccf68b36a7e751a4 for a while now to run the latest gamescope  lately. I am using a kernel with the VALVE1_ prefixed color management options ( see here: https://github.com/ChimeraOS/linux-chimeraos) 

Hardware specs:
Ryzen 3200g (vega graphics)

Std out log:
https://pastebin.com/DKguj3ha

Exact kernel version:
chimeraos 6.4.2-chos1

**Comment by Joshua-Ashton** [comment]
We ship these properties on Steam Deck/SteamOS, so it definitely works...

Perhaps you have some old version of the kernel patches which is missing features or has bugs?

**Comment by Joshua-Ashton** [comment]
The VALVE1_ properties are only tested on the SteamOS kernel that we ship fwiw. Can you try with the kernel we ship in SteamOS?
