### ISSUE TITLE
Desktop crashes when fullscreen gamescope gets minimized while switching workspaces

### ISSUE THREAD

**Issue by AlexanderWKoenig** [Plagman/gamescope#92]
Hi,

since i've managed to get gamescope running, i've tested it a bit.
When i toggle fullscreen with super+f in gamescope and switch my workspace, the gamescope window gets minimized. It can happen that my whole desktop crashes and just shows a blackscreen with a white cursor. But its not consistent, sometimes it works, sometimes it crashes.

I think its an issue with **compiz**.

**As a workaround** i've added gamescope to "non minimizeable windows"  in CompizConfigSettingManager in the "Windows rules"-Plugin. No crashes anymore

**Comment by emersion** [comment]
Not sure we can do much about this. You should report this upstream.

**Comment by AlexanderWKoenig** [comment]
Alright

**Comment by Plagman** [comment]
For what it's worth, I had the same thing on an older kernel, or similar - the GPU would hang with angry amdgpu messages. I've not seen this issue now that I'm on 5.8.3.

**Comment by AlexanderWKoenig** [comment]
This is a compiz crashing issue, cause when I kill compiz, it shows just a blackscreen with a white cursor for me.
